
<?php 
  if($this->errorMessage != null && $this->errorMessage != ''){
	echo "<h4 class='alert_error'>".$this->errorMessage."</h4>";
  }
?>

<article class="module width_full">
			<header><h3>Thông tin liên hệ</h3></header>
				<div class="module_content">
						<form name="form_add" method="POST" action="/admin/index/contact" onSubmit="document.form_add.editor_contents.value  = $('#editor #edit .froala-element').html()">
							<input  type="hidden" name="contact_id" id="contact_id" value="<?php echo $this->contact['ID']?>" />
							<fieldset>
								<label>Nội dung</label>
								<textarea id="editor_contents" name="editor_contents" style="display:none;"></textarea>
								<!-- -->
								<section id="editor">
								  <div id='edit' style="margin-top: 30px;">
									 	 <?php echo $this->contact['TEXT']; ?>
								  </div>
							    </section>

							<div class="clear"></div>
							</fieldset>
							<div class="clear"></div>
							<footer>
								<div class="submit_link">
									<input type="submit" name="btnSubmit" class="alt_btn" value="Lưu">
								</div>
							</footer>
						</form>
						
				</div>
		
		</article>
