
<?php 
  if($this->errorMessage != null && $this->errorMessage != ''){
	echo "<h4 class='alert_error'>".$this->errorMessage."</h4>";
  }
?>

<article class="module width_full">
			<header><h3>Contact Info</h3></header>
				<div class="module_content">
						<fieldset>
							<label>Upload logo image(250x71)</label>
							  <form action="/admin/tour/upload" method="POST" id="uploadform">
							   <input type="file" name="file"/>
							   <input type="submit" name="btnUpload" value="Upload"/><br/><br/>
							   
							   <div id="onsuccessmsg" style="padding:15px;">
							   		<image src="<?php echo $this->setting->logo;?>" />
							   </div>
							  </form>
						</fieldset>
						<form name="form_add" method="POST" onSubmit="document.form_add.editor_contents.value  = $('#editor #edit .froala-element').html()">
							<input  type="hidden" name="img_uploaded" id="img_uploaded" value="<?php echo $this->setting->logo;?>" />
							<fieldset>
								<label>HomePage Layout</label>
								<select name="homepage" style="width: 200px;">
									<option value="TOUR" <?php echo $this->setting->homepage == 'TOUR' ? 'selected': ''?>>TOUR</option>
									<option value="VISA" <?php echo $this->setting->homepage == 'VISA' ? 'selected': ''?>>VISA</option>
								</select>
							</fieldset>
							<fieldset>
								<label>Hot line(*)</label>
								<input type="text" name="hotline" value="<?php echo $this->setting->hotline; ?>">
							</fieldset>
							<fieldset>
								<label>Email(*)</label>
								<input type="text" name="email" value="<?php echo $this->setting->email; ?>">
							</fieldset>
							<fieldset>
								<label>Address(*)</label>
								<input type="text" name="address" value="<?php echo $this->setting->address; ?>">
							</fieldset>
							<fieldset>
								<label>Contact page</label>
								<textarea id="editor_contents" name="editor_contents" style="display:none;"></textarea>
								<!-- -->
								<section id="editor">
								  <div id='edit' style="margin-top: 30px;">
									 	 <?php echo $this->setting->contact; ?>
								  </div>
							    </section>

							<div class="clear"></div>
							</fieldset>
							<div class="clear"></div>
							<footer>
								<div class="submit_link">
									<input type="submit" name="btnSubmit" class="alt_btn" value="Update">
								</div>
							</footer>
						</form>
						
				</div>
		
		</article>
