
<?php 
  if($this->errorMessage != null && $this->errorMessage != ''){
	echo "<h4 class='alert_error'>".$this->errorMessage."</h4>";
  }
?>

<article class="module width_full">
			<header><h3><?php  if($this->parent->level == 0) { 
									echo 'Thêm quận ở '.$this->parent->name;
							   } else {
									echo 'Thêm điêm bán ' .$this->parent->name;
								}
						?>
					</h3>
			</header>
				<div class="module_content">
						<form name="form_add" method="POST" action="/admin/places/add" onSubmit="document.form_add.editor_contents.value  = $('#editor #edit .froala-element').html()">
							<input  type="hidden" name="parent_id" id="parent_id" value="<?php echo $this->parent->id; ?>" />
							<fieldset>
								<label>Tên </label>
								<input type="text" name="name">
							</fieldset>
							<div class="clear"></div>
							<footer>
								<div class="submit_link">
									<input type="submit" name="btnSubmit" class="alt_btn" value="Lưu">
								</div>
							</footer>
						</form>
						
				</div>
		
		</article>
