<!-- APPLY VISA -->
<style type="text/css">
    .bs-callout {
        padding-left: 20px;
        padding-right: 20px;
        padding-bottom: 20px;
        margin: 10px 0;
        border: 1px solid #eee;
        border-left-width: 5px;
        border-radius: 3px;
    }
    
    
    .form-control {
        display: block !important;
        width: 100% !important;
        height: 34px !important;
        padding: 6px 12px !important;
        font-size: 14px !important;
        line-height: 1.42857143 !important;
        color: #555 !important;
        background-color: #fff !important;
        background-image: none !important;
        border: 1px solid #ccc !important;
        border-radius: 4px !important;
   }
   
   select, select.form-control, select.inputbox, select.input, input#thunho, input[type="text"] {
    color: #444 !important;
   }
</style>

<style>
      li {
  line-height: 2em;       
}
  </style>
<div class="home">
		<div id="bienthuy-mainbody" class="container bienthuy-mainbody one-sidebar-right">
	<div class="row">
		<!-- MAIN CONTENT -->
		<div id="bienthuy-content" class="bienthuy-content col-xs-12 col-sm-12 col-md-8">
					<!-- Content Top-->
										 

	<div class="container" id="ApplicationForm">
	<h4>  &nbsp;&nbsp;&nbsp;  </h4>
		<div id="system-message-container" style="display:none;width: 98%; ">
			<div id="system-message">
				<div class="alert alert-message">
					<a class="close" data-dismiss="alert" style="display: none">x</a>
					<div>
						<div class="alert-message">
							<h2 id="error_msg">
								Email: <font size="" color="#33cc00">122</font> is invalid
							</h2>
						</div>
					</div>
				</div>
			</div>
		</div>
		
	     <a href="/vietnam-visa-exemption" style="color:#f58634">Vietnam Visa Exemption</a>
         <h1>Apply Online</h1>

        <div id="showInfoPayment" style="display: block;">
             
        
        </div>
         
        <ul class="nav nav-tabs">
            <li id="idStep1" class="active noactive"><a href="#" style="pointer-events: none;">1.Visa Options</a></li>
            <li id="idStep2"><a href="#" style="pointer-events: none;">2.Applicant Detail</a></li>
            <li id="idStep3"><a href="#" style="pointer-events: none;">3.Review &amp; Finalize</a></li>
        </ul>
        <div class="tab-content123">
            <div id="idStep1_div">
                
                <form data-toggle="validator" role="form" id="myForm1" method="POST">
                	<input type="hidden" name="book_time" id ="book_time" value="">
                    <div class="row" style="padding-left: 20px; padding-right: 20px;">
                        <div class="col-md-5">
                            <div class="form-group">
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        Purpose of Visit
                                    </div>
                                    <div class="col-md-8">
                                        <select name="dropPurposeOfVisit" id="dropPurposeOfVisit" class="form-control" required="">
                                         	<option value="TOURIST VISA">TOURIST VISA</option>
                                         	<option value="BUSINESS VISA">BUSINESS VISA</option>
                                        </select>
                                        
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        Number of visa
                                    </div>
                                    <div class="col-md-8">
                                        <select name="dropNumberApp" id="dropNumberApp" class="form-control" required="">              
                                        	<?php for($i = 1; $i <= $this->numerOfVisa; $i++){?>
													<option value="<?php echo $i?>"><?php echo $i.($i == 1? ' Applicant' : ' Applicants')?></option>
											<?php }?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        Type of visa*
                                    </div>
                                    <div class="col-md-8">
													<select name="type_of_visa" id="type_of_visa"
														class="form-control" required="">
														<option></option>
														<?php foreach($this->visa_type as $type) {?>
															<option value="<?php echo $type->id?>"><?php echo $type->name?></option>
														<?php }?>		
													</select>

												</div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        Arrival Date*
                                    </div>
                                    <div class="col-md-8">
                                        <input name="arrival_date" id="arrival_date" class="form-control arrival_date" placeholder="Arrival date" required="">                                        
                                    </div>
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        Processing Time
                                    </div>
                                    <div class="col-md-8">
                                        <select name="processing_time" id="processing_time" class="form-control" required="">                                        
                                        		<?php foreach($this->processing_time_type as $type) {?>
															<option value="<?php echo $type->id?>"><?php echo $type->name?></option>
												<?php }?>                                            
                                        </select>
                                        <p id="msg_arrival_date" style="color:red;display:none">Please change 'Arrival Date'</p>
                                    </div>
                                    <div class="alert alert-success" id ="processing_time_alert" style="display: none">
                                        <br><br>
                                        
                                        <b>Please note: </b>The processing time from 08:00AM to 04:00PM and exludes lunch time from 11:00AM to 01:30PM
                                        <br><br> (Current Local Time in Vietnam : <?php date_default_timezone_set('Asia/Ho_Chi_Minh');echo date('Y-m-d h:i A');?>)

                                    </div>
                                    
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        Payment:
                                    </div>
                                    <div class="col-md-8">
                                        <div class="radio">
                                             <label>
                                                 <input type="radio" name="radioPay" id="radioPay1" value="Visa/Master/American Express/JCB Card" checked="">Visa/Master/American Express/JCB Card</label>
                                         </div>
                                         <div class="radio">
                                             <label>
                                                 <input type="radio" name="radioPay" id="radioPay2" value="Paypal">Paypal</label>
                                         </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="col-md-2"></div>
                        <div class="col-md-5">
                            <div class="form-group">
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        Arrival Airport
                                    </div>
                                    <div class="col-md-8">
                                        <select name="Arrival_Airport" class="form-control" id="Arrival_Airport">
                                            <option></option>
                                            <option>Noi Bai Airport (HAN)</option>
                                            <option>Tan Son Nhat Airport (SGN)</option>
                                            <option>Danang Airport (DAD)</option>
                                            <option>NhaTrang Airport (CXR)</option>
                                        </select>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        Contact Name*
                                    </div>
                                    <div class="col-md-8">
                                        <input name="contact_name" class="form-control" id="contact_name" type="text" placeholder="Type your name here" required="">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        Contact Email*
                                    </div>
                                    <div class="col-md-8">
                                        <input name="contact_email" class="form-control" id="contact_email" type="email" placeholder="email@domainname" required="">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                    </div>
                                    <div class="col-md-8">
                                        <input name="confirm_email" class="form-control" id="contact_cc_email" onpaste="return false;" type="email" placeholder="Confirm email address" required="">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-md-4">
                                        Contact Phone*
                                    </div>
                                    <div class="col-md-8">
                                        <input name="contact_phone" class="form-control" id="contact_phone" type="text" placeholder="+84 xxx xxxx" value="" required="">
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="row" style="padding-left: 20px; padding-right: 20px;">
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="radioPrivate" id="radioPrivate1" value="Shared Visa" checked=""><b>Shared Visa letter:</b> The visa approval letter may include many other customers on the same letter (recommended)</label>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="radioPrivate" id="radioPrivate2" value="Private Visa"><b>Private Visa letter:</b> Just show your (and your partner’s) details on it (plus <span id="private_visa_letter_price"><?php echo $this->private_visa_letter_price?></span> usd)</label>
                                    </div>
                                </div>
                            </div>

                            
                            

                        </div>
                    </div>
     
                    <div class="alert alert-success">
                        <div class="row">
                            <div class="col-md-2">
                               
                            </div>
                            <div class="col-md-6">
                                <div class="row" style="text-align: center;">
            <div class="col-md-4" style="text-align: right;vertical-align:central;">
                Total Estimated Service Fee<br>
                (visa stamping fee excluded) 
            </div>
            <div class="col-md-8" style="text-align: left;border-left:solid; padding-left:20px">
                <div class="row price_des" style="border-bottom:solid;">
                    1 Applicant (TOURIST VISA) * ('' fee) = 1*0
                    
                    
                </div>
                <div class="row">
                    TOTAL: <span style="color:red;font-size:20px"><strong class="price_total">0 USD</strong></span>
                    
                </div>
            </div>
        </div>
                            </div>
                            <div class="col-md-4" style="text-align:right">
                                <button type="submit" id="btnNext1" class="btn btn-primary btnNext">NEXT</button>
                            </div>
                        </div>
                    </div>
                 </form>
                 
                 
            </div>
            <div id="idStep2_div" style="display: none;">
               <form data-toggle="validator" role="form" id="myForm2" method="POST">
                   <div class="row" style="padding-left: 20px; padding-right: 20px;">
                            <div class="bs-callout bs-callout-info" id="application1" style="display: none">
                               <h5><b>APPLICATION 1:</b></h5>
            <p>
              </p><div class="row hidden-xs hidden-sm">
            <div class="col-md-2">Nationality</div>
            <div class="col-md-2">Applicant's Fullname </div>
            <div class="col-md-2">Gender</div>
            <div class="col-md-2">Date of birth</div>
            <div class="col-md-2">Passport Number</div>
            <div class="col-md-2">Passport expiry date</div>
        </div>
            <p></p>
                               <div class="row">
                                    <div class="col-md-2">
                                        <select id="nationality1" name="nationality1" class="form-control mySelectCoutry select2-hidden-accessible" style="width:150px" required="" tabindex="-1" aria-hidden="true">
                                             <option value="" selected disabled>Select Nationality</option>
                                             <?php foreach($this->nationality as $type) {?>
															<option value="<?php echo $type->id?>" data-is-diff = '<?php echo $type->is_difficult?>'><?php echo $type->name?></option>
											 <?php }?>   
                                        </select><span class="select2 select2-container select2-container--default" dir="ltr" style="width: 150px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-autocomplete="list" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-nationality1-container">
                                        <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="fullname1" id="fullname1"" class="form-control" type="text" placeholder="Applicant's fullname">
                                    </div>
                                    <div class="col-md-2">
                                        <select id="gender1" name ="gender1" class="form-control gender">
                                            <option value="">Select Gender</option>
                                            <option value="Male">Male</option><option value="Female">Female</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="dateOfBirth1" id="dateOfBirth1" type="text" placeholder="Date Of Birth" class="form-control dateOfBirth">
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passport_number1" id="passport_number1" class="form-control" type="text" placeholder="Passport number">
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passportExpiryDate1" id="passportExpiryDate1" class="form-control PPExpireDate" type="text" placeholder="Expiry Date (MMM dd, YYYY)" required="">
                                    </div>
                                </div>
                            </div>
                            <div class="bs-callout bs-callout-info" id="application2" style="display: none">
                                 <h5><b>APPLICATION 2:</b></h5>
            <p>
              </p><div class="row hidden-xs hidden-sm">
            <div class="col-md-2">Nationality</div>
            <div class="col-md-2">Applicant's Fullname </div>
            <div class="col-md-2">Gender</div>
            <div class="col-md-2">Date of birth</div>
            <div class="col-md-2">Passport Number</div>
            <div class="col-md-2">Passport expiry date</div>
        </div>
            <p></p>
                                 <div class="row">
                                    <div class="col-md-2">
                                        <select id="nationality2" class="form-control mySelectCoutry select2-hidden-accessible" style="width:150px" tabindex="-1" aria-hidden="true">
                                             <option value="" selected disabled>Select Nationality</option>
                                             <?php foreach($this->nationality as $type) {?>
											 	<option value="<?php echo $type->id?>" data-is-diff = '<?php echo $type->is_difficult?>'><?php echo $type->name?></option>
											 <?php }?>
                                        </select><span class="select2 select2-container select2-container--default" dir="ltr" style="width: 150px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-autocomplete="list" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-nationality2-container">
                                        <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="fullname2" id="fullname2" class="form-control" type="text" placeholder="Applicant's fullname">
                                    </div>
                                    <div class="col-md-2">
                                        <select id="gender2" class="form-control gender" required="">
                                            <option value="">Select Gender</option>
                                            <option value="Male">Male</option><option value="Female">Female</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="dateOfBirth2" id="dateOfBirth2" type="text" placeholder="Date Of Birth" class="form-control dateOfBirth" >
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passport_number2" id="passport_number2" class="form-control" type="text" placeholder="Passport number" >
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passportExpiryDate2" id="passportExpiryDate2" class="form-control PPExpireDate" type="text" placeholder="Expiry Date (MMM dd, YYYY)" >
                                    </div>
                                </div>
                            </div>
                            
                            <div class="bs-callout bs-callout-info" id="application3" style="display: none">
                               <h5><b>APPLICATION 3:</b></h5>
            <p>
              </p><div class="row hidden-xs hidden-sm">
            <div class="col-md-2">Nationality</div>
            <div class="col-md-2">Applicant's Fullname </div>
            <div class="col-md-2">Gender</div>
            <div class="col-md-2">Date of birth</div>
            <div class="col-md-2">Passport Number</div>
            <div class="col-md-2">Passport expiry date</div>
        </div>
            <p></p>
                               <div class="row">
                                    <div class="col-md-2">
                                        <select id="nationality3" class="form-control mySelectCoutry select2-hidden-accessible" style="width:150px" tabindex="-1" aria-hidden="true" required="">
                                            <option value="" selected disabled>Select Nationality</option>
                                            <?php foreach($this->nationality as $type) {?>
												<option value="<?php echo $type->id?>" data-is-diff = '<?php echo $type->is_difficult?>'><?php echo $type->name?></option>
											<?php }?>
                                        </select><span class="select2 select2-container select2-container--default" dir="ltr" style="width: 150px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-autocomplete="list" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-nationality3-container">
                                        <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="fullname3" id="fullname3" class="form-control" type="text" placeholder="Applicant's fullname" >
                                    </div>
                                    <div class="col-md-2">
                                        <select id="gender3" class="form-control gender" >
                                            <option value="">Select Gender</option>
                                            <option value="Male">Male</option><option value="Female">Female</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="dateOfBirth3" id="dateOfBirth3" type="text" placeholder="Date Of Birth" class="form-control dateOfBirth" >
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passport_number3" id="passport_number3" class="form-control" type="text" placeholder="Passport number" >
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passportExpiryDate3" id="passportExpiryDate3" class="form-control PPExpireDate" type="text" placeholder="Expiry Date (MMM dd, YYYY)" >
                                    </div>
                                </div>  
                               
                            </div>
                            
                            <div class="bs-callout bs-callout-info" id="application4" style="display: none">
                               <h5><b>APPLICATION 4:</b></h5>
            <p>
              </p><div class="row hidden-xs hidden-sm">
            <div class="col-md-2">Nationality</div>
            <div class="col-md-2">Applicant's Fullname </div>
            <div class="col-md-2">Gender</div>
            <div class="col-md-2">Date of birth</div>
            <div class="col-md-2">Passport Number</div>
            <div class="col-md-2">Passport expiry date</div>
        </div>
            <p></p>
                               <div class="row">
                                    <div class="col-md-2">
                                        <select id="nationality4" class="form-control mySelectCoutry select2-hidden-accessible" style="width:150px"  tabindex="-1" aria-hidden="true">
                                             <option value="" selected disabled>Select Nationality</option>
                                             <?php foreach($this->nationality as $type) {?>
												<option value="<?php echo $type->id?>" data-is-diff = '<?php echo $type->is_difficult?>'><?php echo $type->name?></option>
											<?php }?>
                                        </select><span class="select2 select2-container select2-container--default" dir="ltr" style="width: 150px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-autocomplete="list" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-nationality4-container">
                                        <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="fullname4" id="fullname4" class="form-control" type="text" placeholder="Applicant's fullname" >
                                    </div>
                                    <div class="col-md-2">
                                        <select id="gender4" class="form-control gender" >
                                            <option value="">Select Gender</option>
                                            <option value="Male">Male</option><option value="Female">Female</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="dateOfBirth4" id="dateOfBirth4" type="text" placeholder="Date Of Birth" class="form-control dateOfBirth" >
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passport_number4" id="passport_number4" class="form-control" type="text" placeholder="Passport number" >
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passportExpiryDate4" id="passportExpiryDate4" class="form-control PPExpireDate" type="text" placeholder="Expiry Date (MMM dd, YYYY)" >
                                    </div>
                                </div>
                            </div>

                            <div class="bs-callout bs-callout-info" id="application5" style="display: none">
                               <h5><b>APPLICATION 5:</b></h5>
            <p>
              </p><div class="row hidden-xs hidden-sm">
            <div class="col-md-2">Nationality</div>
            <div class="col-md-2">Applicant's Fullname </div>
            <div class="col-md-2">Gender</div>
            <div class="col-md-2">Date of birth</div>
            <div class="col-md-2">Passport Number</div>
            <div class="col-md-2">Passport expiry date</div>
        </div>
            <p></p>
                               <div class="row">
                                    <div class="col-md-2">
                                        <select id="nationality5" class="form-control mySelectCoutry select2-hidden-accessible" style="width:150px"  tabindex="-1" aria-hidden="true">
                                             <option value="" selected disabled>Select Nationality</option>
                                             <?php foreach($this->nationality as $type) {?>
												<option value="<?php echo $type->id?>" data-is-diff = '<?php echo $type->is_difficult?>'><?php echo $type->name?></option>
											<?php }?>
                                        </select><span class="select2 select2-container select2-container--default" dir="ltr" style="width: 150px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-autocomplete="list" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-nationality5-container">
                                        <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="fullname5" id="fullname5" class="form-control" type="text" placeholder="Applicant's fullname" >
                                    </div>
                                    <div class="col-md-2">
                                        <select id="gender5" class="form-control gender" >
                                            <option value="">Select Gender</option>
                                            <option value="Male">Male</option><option value="Female">Female</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="dateOfBirth5" id="dateOfBirth5" type="text" placeholder="Date Of Birth" class="form-control dateOfBirth" >
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passport_number5" id="passport_number5" class="form-control" type="text" placeholder="Passport number" >
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passportExpiryDate5" id="passportExpiryDate5" class="form-control PPExpireDate" type="text" placeholder="Expiry Date (MMM dd, YYYY)" >
                                    </div>
                                </div>
                            </div>

                            <div class="bs-callout bs-callout-info" id="application6" style="display: none">
                               <h5><b>APPLICATION 6:</b></h5>
            <p>
              </p><div class="row hidden-xs hidden-sm">
            <div class="col-md-2">Nationality</div>
            <div class="col-md-2">Applicant's Fullname </div>
            <div class="col-md-2">Gender</div>
            <div class="col-md-2">Date of birth</div>
            <div class="col-md-2">Passport Number</div>
            <div class="col-md-2">Passport expiry date</div>
        </div>
            <p></p>
                               <div class="row">
                                    <div class="col-md-2">
                                           <select id="nationality6" class="form-control mySelectCoutry select2-hidden-accessible" style="width:150px"  tabindex="-1" aria-hidden="true">
                                                <option value="" selected disabled>Select Nationality</option>
                                                <?php foreach($this->nationality as $type) {?>
													<option value="<?php echo $type->id?>" data-is-diff = '<?php echo $type->is_difficult?>'><?php echo $type->name?></option>
												<?php }?>
                                           </select><span class="select2 select2-container select2-container--default" dir="ltr" style="width: 150px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-autocomplete="list" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-labelledby="select2-nationality6-container">
                                           <span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="fullname6" id="fullname6" class="form-control" type="text" placeholder="Applicant's fullname" >
                                    </div>
                                    <div class="col-md-2">
                                        <select id="gender6" class="form-control gender" >
                                            <option value="">Select Gender</option>
                                            <option value="Male">Male</option><option value="Female">Female</option>
                                        </select>
                                    </div>
                                    <div class="col-md-2">
                                        <input name="dateOfBirth6" id="dateOfBirth6" type="text" placeholder="Date Of Birth" class="form-control dateOfBirth" >
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passport_number6" id="passport_number6" class="form-control" type="text" placeholder="Passport number" >
                                    </div>
                                    <div class="col-md-2">
                                        <input name="passportExpiryDate6" id="passportExpiryDate6" class="form-control PPExpireDate" type="text" placeholder="Expiry Date (MMM dd, YYYY)" >
                                    </div>
                                </div>
                            </div>
                        <div class="alert alert-success">
                            Please enter your exact full name with First/Given name &amp; Middle name in order as they appear in passport.
                        </div>
                       
                        
                        
                   

                       
                  
                      
                        
                   </div>
                   <div class="alert alert-success">
                       <div class="row">
                           <div class="col-md-2">
                               <button type="button" id="btnPrevious2" class="btn btn-primary" formnovalidate="">PREVIOUS</button>
                               
                           </div>
                           <div class="col-md-6">
                                 <div class="row" style="text-align: center;">
             <div class="col-md-4" style="text-align: right;vertical-align:central;">
                Total Estimated Service Fee<br>
                (visa stamping fee excluded) 
            </div>
            <div class="col-md-8" style="text-align: left;border-left:solid; padding-left:20px">
                <div class="row price_des" style="border-bottom:solid;">
                    1 Applicant (TOURIST VISA) * ('' fee) = 1*0
                    
                    
                </div>
                <div class="row">
                    TOTAL: <span style="color:red;font-size:20px"><strong class="price_total">0 USD</strong></span>
                    
                </div>
            </div>
        </div>
                            </div>
                           <div class="col-md-4" style="text-align:right">
                               <button type="submit" id="btnNext2" class="btn btn-primary btnNext">NEXT</button>
                           </div>
                       </div>
                   </div>
               </form>
            </div>
            <div id="idStep3_div" style="display: none;">
                 <h3>Review &amp; Finalize</h3>
                 <h3 style="display: none;">APPLICATION INFORMATION</h3>
                 <form data-toggle="validator" role="form">
                   <div class="row" style="padding-left: 20px; padding-right: 20px;">    
                     <ul class="list-group">
                         <li class="list-group-item">
                             <span class="badge" id="dropPurposeOfVisit_text"></span>
                             Visa type:
                         </li>
                         <li class="list-group-item">
                             <span class="badge" id="arrival_date_text"></span>
                             Arrival Date:
                         </li>
                         <li class="list-group-item">
                             <span class="badge"  id="radioPrivate_text"></span>
                             Shared Visa or Private Visa:
                         </li>
                         <li class="list-group-item">
                             <span class="badge" id="processing_time_text"></span>
                             Processing Time:
                         </li>
                         <li class="list-group-item">
                             <span class="badge" id="contact_text"></span>
                             Contact:
                         </li>
                          
                          <li class="list-group-item">
                             <span class="badge" id="radioPay_text"></span>
                             Payment:
                         </li>
                     </ul>


  			</div>
			<div class="row"
				style="padding-left: 20px; padding-right: 20px;">
				<div class="col-md-6" id="application1_text">
					<div class="bs-callout bs-callout-info">
						<div class="row">
							<div class="col-md-10">
								<h2 id="fullname1_text"></h2>
							</div>
							<div class="col-md-2" style="text-align: right">
								<span id="nationality1_text"></span>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4" style="text-align: center">
								<img id="img1" class="img-fluid" src="../imagesNew/maleU1y.png">
							</div>
							<div class="col-md-8 pull-right">
								<ul>
									<li>Date Of Birth: <strong id="dateOfBirth1_text"></strong></li>
									<li>Passport number: <strong id="passport_number1_text"></strong></li>
									<li>Expiry date: <strong id="passportExpiryDate1_text"></strong></li>
									<li>Gender: <strong id="gender1_text"></strong></li>
								</ul>
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-6" id="application2_text">
					<div class="bs-callout bs-callout-info">
						<div class="row">
							<div class="col-md-10">
								<h2 id="fullname2_text"></h2>
							</div>
							<div class="col-md-2" style="text-align: right">
								<span id="nationality2_text"></span>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4" style="text-align: center">
								<img id="img2" ="img-fluid" src="../imagesNew/maleU1y.png">
							</div>
							<div class="col-md-8 pull-right">
								<ul>
									<li>Date Of Birth: <strong  id="dateOfBirth2_text"></strong></li>
									<li>Passport number: <strong id="passport_number2_text"> </strong></li>
									<li>Expiry date: <strong id="passportExpiryDate2_text">December 06, 2018</strong></li>
									<li>Gender: <strong id="gender2_text">Female</strong></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>

<div class="row"
				style="padding-left: 20px; padding-right: 20px;">
				<div class="col-md-6" id="application3_text">
					<div class="bs-callout bs-callout-info">
						<div class="row">
							<div class="col-md-10">
								<h2 id="fullname3_text"></h2>
							</div>
							<div class="col-md-2" style="text-align: right">
								<span id="nationality3_text"></span>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4" style="text-align: center">
								<img id="img3" class="img-fluid" src="../imagesNew/maleU1y.png">
							</div>
							<div class="col-md-8 pull-right">
								<ul>
									<li>Date Of Birth: <strong  id="dateOfBirth3_text"></strong></li>
									<li>Passport number: <strong  id="passport_number3_text"></strong></li>
									<li>Expiry date: <strong  id="passportExpiryDate3_text"></strong></li>
									<li>Gender: <strong id="gender3_text"></strong></li>
								</ul>
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-6" id="application4_text">
					<div class="bs-callout bs-callout-info">
						<div class="row">
							<div class="col-md-10">
								<h2 id="fullname4_text"></h2>
							</div>
							<div class="col-md-2" style="text-align: right">
								<span id="nationality4_text"></span>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4" style="text-align: center">
								<img id="img4" class="img-fluid" src="../imagesNew/maleU1y.png">
							</div>
							<div class="col-md-8 pull-right">
								<ul>
									<li>Date Of Birth: <strong  id="dateOfBirth4_text"></strong></li>
									<li>Passport number: <strong  id="passport_number4_text"></strong></li>
									<li>Expiry date: <strong  id="passportExpiryDate4_text"></strong></li>
									<li>Gender: <strong  id="gender4_text"></strong></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			
			<div class="row"
				style="padding-left: 20px; padding-right: 20px;">
				<div class="col-md-6" id="application5_text">
					<div class="bs-callout bs-callout-info">
						<div class="row">
							<div class="col-md-10">
								<h2 id="fullname5_text"></h2>
							</div>
							<div class="col-md-2" style="text-align: right">
								<span id="nationality5_text"></span>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4" style="text-align: center">
								<img id="img5" class="img-fluid" src="../imagesNew/maleU1y.png">
							</div>
							<div class="col-md-8 pull-right">
								<ul>
									<li>Date Of Birth: <strong  id="dateOfBirth5_text"></strong></li>
									<li>Passport number: <strong id="passport_number5_text"></strong></li>
									<li>Expiry date: <strong id="passportExpiryDate5_text"></strong></li>
									<li>Gender: <strong  id="gender5_text"></strong></li>
								</ul>
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-6" id="application6_text">
					<div class="bs-callout bs-callout-info">
						<div class="row">
							<div class="col-md-10">
								<h2 id="fullname6_text"></h2>
							</div>
							<div class="col-md-2" style="text-align: right">
								<span id="nationality6_text"></span>
							</div>
						</div>
						<div class="row">
							<div class="col-md-4" style="text-align: center">
								<img id="img6" class="img-fluid" src="../imagesNew/maleU1y.png" style="display: none">
							</div>
							<div class="col-md-8 pull-right">
								<ul>
									<li>Date Of Birth: <strong id="dateOfBirth6_text"></strong></li>
									<li>Passport number: <strong  id="passport_number6_text"></strong></li>
									<li>Expiry date: <strong  id="passportExpiryDate6_text"></strong></li>
									<li>Gender: <strong id="gender6_text"></strong></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>





			<div class="row" style="padding-left: 20px; padding-right: 20px;">
                            <br>
                            <input value="termOfUse" id="termOfUse" type="checkbox" checked="checked">
                            <label for="termOfUse" style="padding: 4px 6px;">I have read and agree with the <a href="/visa-term-condition" target="_blank" style="text-decoration: underline;">Terms of Use</a></label>
                           
                            <br>
                        </div>

                   <div class="alert alert-success">
                    <div class="row">
                        <div class="col-md-2">
                             <div>
                                <button type="button" id="btnPrevious3" class="btn btn-primary btnPrevious" formnovalidate="">PREVIOUS</button>
                             </div>
                        </div>
                        <div class="col-md-6">
                                  <div class="row" style="text-align: center;">
            <div class="col-md-4" style="text-align: right;vertical-align:central;">
                Total Estimated Service Fee<br>
                (visa stamping fee excluded) 
            </div>
            <div class="col-md-8" style="text-align: left;border-left:solid; padding-left:20px">
                <div class="row price_des" style="border-bottom:solid;">
                    1 Applicant (TOURIST VISA) * ('' fee) = 1*0
                    
                    
                </div>
                <div class="row">
                    TOTAL: <span style="color:red;font-size:20px"><strong class="price_total">0 USD</strong></span>
                    
                </div>
            </div>
        </div>
                            </div>
                        <div class="col-md-4" style="text-align:right">
                           
                            <div>
                                
                                <div>
                                    <button type="button" id="btnSubmit" class="btn btn-primary btnNext">SUBMIT AND PAY</button>
                                </div>
                            </div>
                            
                            <div class="loading-spin" style="text-align: center">
                                <i class="fa fa-5x fa-spinner fa-pulse middle" id="loadingBook1" style="display: none;">.</i>
                            </div>
                        </div>
                    </div>
                </div>
                     </form>
            </div>    
        </div>
      
       
    </div>
</div>
</div>
</div>