<div id="mainbody-wr">
	<div class="orderForm">
		<form name="FormCartUpdate" method="post">
		  <table class="order_table" border="0" cellpadding="0" cellspacing="1" bgcolor="#E8E8E8" width="100%">
			<tr>
			  <td width="20px" align="center" bgcolor="#F1F1F1">
				<div style="padding-right:5px;" class="table_title">
				  STT
				</div>
			  </td>
			  <td align="center" bgcolor="#F1F1F1">
				<div class="table_title" style="text-align: left">
				  Sản phẩm
				</div>
			  </td>
			  <td width="100px" align="center" bgcolor="#F1F1F1">
				<div class="table_title">
				  Số lượng
				</div>
			  </td>
			  <td width="100px" align="center" bgcolor="#F1F1F1">
				<div class="table_title">
				  Đơn giá
				</div>
			  </td>
			  <td width="100px" align="center" bgcolor="#F1F1F1">
				<div class="table_title" style="text-align:right">
				  Tổng (VND)
				</div>
			  </td>
			  <td width="100px" align="center" bgcolor="#F1F1F1">
				<div class="table_title" style="text-align:right">
				  Chiết khấu
				</div>
			  </td>
		  </tr>
		  <tr bgcolor="#FFFFFF">
			<td align="center">
			  1
			</td>
			<td align="left">
			  <div class="cart_table_brief">
				<a href="/pb1212/034a-co-bo-mo.html" title="G034A (4 phụ kiện)">
				  G034A (4 phụ kiện)
				</a>
			  </div>
			</td>
			<td align="center">
			  <input name="quantity_1212" value="1" type="number" style="width:50px; height:16px;" />
			</td>
			<td align="right">
			  <span style="padding-right:5px;" class="cart_price">
				250.000
			  </span>
			</td>
			<td align="right">
			  <span style="padding-right:5px;" class="cart_price">
				250.000
			  </a>
			</td>
			<td align="right">
			  <span style="padding-right:5px;" class="cart_price">
				0
			  </a>
			</td>
		  </tr>
		  <tr bgcolor="#FFFFFF">
			<td align="center">
			  2
			</td>
			<td align="left">
			  <div class="cart_table_brief">
				<a href="/pb642/cap-xach-ss-3859.html" title="Cặp xách SS-3859">
				  Cặp xách SS-3859
				</a>
			  </div>
			</td>
			<td align="center">
			  <input name="quantity_642" value="2" type="number" style="width:50px; height:16px;" />
			</td>
			<td align="right">
			  <span style="padding-right:5px;" class="cart_price">
				1.750.000
			  </span>
			</td>
			<td align="right">
			  <span style="padding-right:5px;" class="cart_price">
				3.500.000
			  </a>
			</td>
			<td align="right">
			  <span style="padding-right:5px;" class="cart_price">
				-350.000
			  </a>
			</td>
		  </tr>
		  
		  <tr bgcolor="#FFFFFF">
			<td colspan="4" align="right">
			  <div class="cart_table_brief">
				Tổng giá
			  </div>
			</td>
			<td align="right">
			  <span style="padding-right:5px;" class="cart_price">
				3.750.000
			  </span>
			</td>
			<td align="right">
			  <span style="padding-right:5px;" class="cart_price">
				-350.000
			  </span>
			</td>
		  </tr>
		  <tr bgcolor="#FFFFFF">
			<td colspan="4" align="right">
			  <div class="cart_table_brief">
				Tổng đơn hàng sau chiết khấu
			  </div>
			</td>
			<td align="right" colspan="2">
			  <span style="padding-right:5px;" class="cart_price">
				3.400.000
			  </span>
			</td>
		  </tr>
		  <tr align="left" bgcolor="#FFFFFF">
			<td colspan="6" valign="middle" align="right">
			  <div style="padding:8px;">
				<font color="#FF0000">
				  Nhập số lượng 
				  <strong>
					=0
				  </strong>
				  nếu bạn muốn xóa sản phẩm khỏi giỏ hàng
				</font>
				&nbsp;
				<a href="/pa/san-pham.html" class="cartbutton">
				  Tiếp tục mua hàng
				</a>
				<a style="margin-left:10px;" href="javascript:void(0)" onclick="FormCartUpdate.submit()" class="cartbutton">
				  Cập nhật giỏ hàng
				</a>
			  </div>
			</td>
		  </tr>
		  </table>
		  <input type="hidden" name="action" value="update_cart" />
		</form>
	</div>
	<div style="height: 10px; clear: both;"></div>
	
	<div class="orderForm">
		<form name="FormOrderProduct" method="post">
		  <table border="0" cellpadding="0" cellspacing="1" bgcolor="#F1F1F1" width="100%" class="customer_table">
			<tr bgcolor="#E8E8E8">
			  <td align="left" colspan="2">
				<div style="padding:3px; color:#FF0000; font-weight:bold;">
				  Hãy nhập chính xác thông tin để chúng tôi có thể liên hệ sớm với bạn!
				</div>
			  </td>
			</tr>
			<tr bgcolor="#FFFFFF">
			  <td colspan="2">
				<div style="color:#FF0000; font-weight:bold;">
				  Thông tin người mua hàng
				</div>
			  </td>
			</tr>
			<tr bgcolor="#FFFFFF">
			  <td width="20%" align="left" valign="top">
				Họ và tên 
				<font color="#FF0000">
				  (*)
				</font>
				:
			  </td>
			  <td align="left" valign="top">
				<input name="fullname" value="" type="text" size="50" class="input_box" />
				&nbsp;			
			  </td>
			</tr>
			<tr bgcolor="#FFFFFF">
			  <td align="left" valign="top">
				Địa chỉ 
				<font color="#FF0000">
				  (*)
				</font>
				:
			  </td>
			  <td align="left" valign="top">
				<select style="margin-bottom: 5px;">
					<option value="">-Chọn tỉnh thành-</option>
					<option value="Hà Nội">Hà Nội</option>
					<option value="TP Hồ Chí Minh">TP Hồ Chí Minh</option>
					<option value="An Giang">An Giang</option>
					<option value="audi">Bắc Ninh</option>
				</select>
				</br><input name="address" value="" type="text" size="50" class="input_box" />
				&nbsp;			
			  </td>
			</tr>
			<tr bgcolor="#FFFFFF">
			  <td align="left" valign="top">
				Hòm thư 
				<font color="#FF0000">
				  (*)
				</font>
				:
			  </td>
			  <td align="left" valign="top">
				<input name="email" value="" type="text" size="50" class="input_box"  />
				&nbsp;			
			  </td>
			</tr>
			<tr bgcolor="#FFFFFF">
			  <td align="left" valign="top">
				Điện thoại 
				<font color="#FF0000">
				  (*)
				</font>
				:
			  </td>
			  <td align="left" valign="top">
				<input name="phone" value="" type="text" size="50" class="input_box" />
				&nbsp;
			  </td>
			</tr>

			<tr bgcolor="#FFFFFF">
			  <td colspan="2">
				&nbsp;
			  </td>
			</tr>
			<tr bgcolor="#FFFFFF">
			  <td align="left" valign="middle">
				Ghi chú:
			  </td>
			  <td align="left" valign="top">
				<textarea name="content" style="width:316px; height:100px;">
				</textarea>
			  </td>
			</tr>
			<tr bgcolor="#FFFFFF">
			  <td align="left" valign="top">
				&nbsp;
			  </td>
			  <td align="left" valign="top">
				<div style="padding-top:5px; padding-bottom:5px;">
				  <a href="javascript:void(0)" onclick="FormOrderProduct.submit()" class="cartbutton">
					Gửi đơn hàng
				  </a>
				</div>
			  </td>
			</tr>
		  </table>
		  <input type="hidden" name="form_product_order" value="product_order" />
		</form>
	</div>
</div>