<div id="center_cont">
	<div class="acticle_index">
		<div class="b_head"><a href="" target="_self">Điểm bán</a></div>
		<div class="news-detail">
			<div class="place-item">
				<div class="p-title"><p>Hà Nội</p></div>
				<div class="place-list">
					<div class="region"><a href="">Quận Thanh Xuân</a></div>
					<div class="region"><a href="">Quận Đống Đa</a></div>
					<div class="region"><a href="">Quận Hà Đông</a></div>
					<div class="region"><a href="">Quận Ba Đình</a></div>
					<div class="region"><a href="">Quận Hoàn Kiếm</a></div>
					<div class="region"><a href="">Quận Hai Bà Trưng</a></div>
					<div class="region"><a href="">Quận Hoàng Mai</a></div>
					<div class="region"><a href="">Quận Long Biên</a></div>
					<div class="region"><a href="">Quận Nam Từ Liêm</a></div>
					<div class="region"><a href="">Quận Bắc Từ Liêm</a></div>
					<div class="region"><a href="">Huyện Chương Mĩ</a></div>
					<div class="region"><a href="">Huyện Phú Xuyên</a></div>
					<div class="region"><a href="">Huyện Thanh Trì</a></div>
					<div class="region"><a href="">Huyện Sóc Sơn</a></div>
				</div>
			</div>
		</div>
	</div>
</div>