<!-- HUYHOA.COM -->
<div class="container bienthuy-spot bienthuy-spot-1">
	<div class="ts-slidefull">
		<div class="col-xs-12 slidehuyhoa">
			<!-- Columns start at 100% wide on mobile and bump up to 33.3% wide on desktop -->
			<!--[if lte IE 7]>
			<link href="/modules/mod_slideshowck/themes/default/css/camera_ie.css" rel="stylesheet" type="text/css" />
			<![endif]-->
			<!--[if IE 8]>
			<link href="/modules/mod_slideshowck/themes/default/css/camera_ie8.css" rel="stylesheet" type="text/css" />
			<![endif]-->
			<!-- debut Slideshow CK -->
			<div class="slideshowck camera_wrap camera_amber_skin" id="camera_wrap_90">
				<div data-src="/images/slides/bridge.jpg">
					<div class="camera_caption fadeFromBottom"> Vietnam Tour. 
						<em>DaLat</em>
					</div>
				</div>
				<div data-src="/images/slides/leaf.jpg">
					<div class="camera_caption fadeFromBottom"> Vietnam Tour, 
						<em>Sapa</em>
					</div>
				</div>
				<div data-src="/images/slides/road.jpg">
					<div class="camera_caption fadeFromBottom"> VietNam Tour
						<em>DaNang </em>
					</div>
				</div>
				<div data-src="/images/slides/sea.jpg">
					<div class="camera_caption fadeFromBottom"> VietNam Tour 
						<em> Nha Trang</em>
					</div>
				</div>
				<div data-src="/images/slides/shelter.jpg">
					<div class="camera_caption fadeFromBottom"> VietNam Tour 
						<em>Ha Noi</em> (
						<a style="color: white;" href="http://validator.w3.org/check?uri=http%3A%2F%2Fwww.pixedelic.com%2Fplugins%2Fcamera%2F&amp;charset=%28detect+automatically%29&amp;doctype=Inline&amp;group=0&amp;user-agent=W3C_Validator%2F1.2" target="_blank">have a look</a>) 
					</div>
				</div>
				<div data-src="/images/slides/tree.jpg">
					<div class="camera_caption fadeFromBottom"> VietNam Tour 
						<em>ready to go</em>
					</div>
				</div>
			</div>
			<div style="clear:both;"></div>
		</div>
	</div>
</div>
<!-- //HUYHOA.COM -->
<div class="home">
	<div id="bienthuy-mainbody" class="container bienthuy-mainbody one-sidebar-right">
		<div class="row">
			<!-- MAIN CONTENT -->
			<div id="bienthuy-content" class="bienthuy-content col-xs-12 col-sm-12 col-md-12">
				<!-- Content Top-->
				<div class="ts-content-top " style="display: none">
					<div class="t3-module module " id="Mod113">
						<div class="module-inner">
							<h2 class="module-title  h3chunho customhome">
								<span>PLAN YOUR VIETNAM TOUR</span>
							</h2>
							<div class="module-ct">
								<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.min.css">
									<script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
									<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
									<script>
  $( function() {
    $( "#datepickerhomehh" ).datepicker({ minDate:+3,
			maxDate:"+2Y +1M +10D",
			numberOfMonths:3,
			changeMonth:false,
			changeYear:false });
  } );
  </script>
									<div id="customcustomized_tour">
										<div class="form-area">
											<form action="/customized-tour.html" method="post" role="form" data-toggle="validator">
												<div class="form-group">
If you would rather create your own itinerary, we would be happy to assist you in putting together one that best suits your schedule and interest. Then send us your requests, we will respond to you within 12 hours.</div>
												<div class="form-group col-md-3 col-sm-6 khongcachtrai">
													<select name="paticipant" class="form-control batbuoc" required="">
														<option value="" selected="">Number of travelers?</option>
														<option value="1">1 Person</option>
														<option value="2">2 Persons</option>
														<option value="3">3 Persons</option>
														<option value="4">4 Persons</option>
														<option value="5">5 Persons</option>
														<option value="6">6 Persons</option>
														<option value="7">7 Persons</option>
														<option value="8">8 Persons</option>
														<option value="9">9 Persons</option>
														<option value="10">10 Persons</option>
														<option value="999">&gt; 10 Persons</option>
													</select>
												</div>
												<div class="form-group col-md-3 col-sm-6 khongcachtrai">
													<select name="lengthoftrip" class="form-control batbuoc" style="width:auto;" required="">
														<option value="">How many days?</option>
														<option value="1">1 days</option>
														<option value="2">2 days</option>
														<option value="3">3 days</option>
														<option value="4">4 days</option>
														<option value="5">5 days</option>
														<option value="6">6 days</option>
														<option value="7">7 days</option>
														<option value="8">8 days</option>
														<option value="9">9 days</option>
														<option value="10">10 days</option>
														<option value="11">11 days</option>
														<option value="12">12 days</option>
														<option value="13">13 days</option>
														<option value="14">14 days</option>
														<option value="15">15 days</option>
														<option value="16">16 days</option>
														<option value="17">17 days</option>
														<option value="18">18 days</option>
														<option value="19">19 days</option>
														<option value="20">20  days</option>
													</select>
												</div>
												<div class="form-group col-md-2 col-sm-6 khongcachtrai cachphai5">
													<select name="hotelcategory" class="form-control batbuoc" style="width:auto;" required="">
														<option value="">Hotel category</option>
														<option value="3">3 Stars</option>
														<option value="4">4 Stars</option>
														<option value="5">5 Stars</option>
														<option value="6">Top Luxury</option>
													</select>
												</div>
												<div class="form-group col-md-2 col-sm-6">
													<input type="text" class="form-control formdatehome hasDatepicker" id="datepickerhomehh" name="date" placeholder="Travel Date" required="">
													</div>
													<div class="form-group col-md-1 col-sm-6 khongcachtrai">
														<input type="hidden" name="task" value="">
															<input type="hidden" name="option" value="com_customizedtour">
																<button aria-label="Submit" type="submit" id="submit" name="submit" class="btn btn-primary khongcachtren fa fa-sign-in vongtron"></button>
															</div>
														</form>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<!-- //Content top end-->
								<!-- Content mid -->
								<div class="ts-content-mid">
									<!-- SPOTLIGHT -->
									<div class="t3-spotlight t3-contentmid  row">
										<div class=" col-md-4">
											<div class="t3-module module " id="Mod129">
												<div class="module-inner">
													<h3 class="module-title  h3chunho">
														<span>
															<a href="/vietnam-tours/culture-history-tours.html">Culture &amp; History Tours</a>
														</span>
													</h3>
													<div class="module-ct">
														<div class="nspMain  activated" id="nsp-nsp-129" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
															<div class="nspArts bottom" style="width:100%;">
																<div class="nspArtScroll1">
																	<div class="nspArtScroll2 nspPages1">
																		<div class="nspArtPage active nspCol1">
																			<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																				<h4 class="nspHeader tleft fnone has-image">
																					<a href="/vietnam-tours/culture-history-tours/vietnam-orientation-8-days.html" title="Vietnam Orientation - 8 Days" target="_self">Vietnam Orientation - 8 Days</a>
																				</h4>
																				<a href="/vietnam-tours/culture-history-tours/vietnam-orientation-8-days.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																					<img class="nspImage" src="/images/Intro-Vietnam-Orientation-Adventure_aecfd.jpg" alt="Intro Vietnam Orientation Adventure">
																					</a>
																					<p class="nspText tleft fleft">Vietnam Orientation tour starts in Hanoi - Vietnam's charming capital, passing through the&nbsp;Centre's stopover of Danang and Hoian, ends in the bustling commercial hub of Ho Chi Minh City. In...</p>
																				</div>
																			</div>
																		</div>
																	</div>
																</div>
																<div class="nspLinksWrap bottom" style="width:99.9%;">
																	<div class="nspLinks" style="margin:0;">
																		<div class="nspLinkScroll1">
																			<div class="nspLinkScroll2 nspPages1">
																				<ul class="nspList active nspCol1">
																					<li class="even">
																						<h4>
																							<a href="/vietnam-tours/culture-history-tours/best-of-north-vietnam-7-days.html" title="Best Of North Vietnam - 7 Days" target="_self">Best Of North Vietnam - 7 Days</a>
																						</h4>
																					</li>
																					<li class="odd">
																						<h4>
																							<a href="/vietnam-tours/culture-history-tours/vietnam-explorer-16-days.html" title="Vietnam Explorer - 16 Days" target="_self">Vietnam Explorer - 16 Days</a>
																						</h4>
																					</li>
																					<li class="even">
																						<h4>
																							<a href="/vietnam-tours/culture-history-tours/vietnam-vacation-13-days.html" title="Vietnam Vacation - 13 Days" target="_self">Vietnam Vacation - 13 Days</a>
																						</h4>
																					</li>
																				</ul>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class=" col-md-4">
												<div class="t3-module module " id="Mod115">
													<div class="module-inner">
														<h3 class="module-title  h3chunho">
															<span>
																<a href="/vietnam-tours/adventures.html">Vietnam Adventures</a>
															</span>
														</h3>
														<div class="module-ct">
															<div class="nspMain  activated" id="nsp-nsp-115" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																<div class="nspArts bottom" style="width:100%;">
																	<div class="nspArtScroll1">
																		<div class="nspArtScroll2 nspPages1">
																			<div class="nspArtPage active nspCol1">
																				<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																					<h4 class="nspHeader tleft fnone has-image">
																						<a href="/vietnam-tours/adventures/north-vietnam-grand-adventure-11-days.html" title="North Vietnam Grand Adventure - 11 Days" target="_self">North Vietnam Grand Adventure - 11 Days</a>
																					</h4>
																					<a href="/vietnam-tours/adventures/north-vietnam-grand-adventure-11-days.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																						<img class="nspImage" src="/images/VNTours_Photos/Intro-NorthVietnam-Grand-Adventure_0f9a6.jpg" alt="North Vietnam Grand Adventure thumbnail">
																						</a>
																						<p class="nspText tleft fleft">The Northwest of Vietnam with its breathtaking mountains landscapes and colorful hill tribes is the place for a real adventure discovery. From spectacular Karst Plateau Geopark of Dong Van up...</p>
																					</div>
																				</div>
																			</div>
																		</div>
																	</div>
																	<div class="nspLinksWrap bottom" style="width:99.9%;">
																		<div class="nspLinks" style="margin:0;">
																			<div class="nspLinkScroll1">
																				<div class="nspLinkScroll2 nspPages1">
																					<ul class="nspList active nspCol1">
																						<li class="even">
																							<h4>
																								<a href="/vietnam-tours/adventures/north-east-vietnam-adventure-11-days.html" title="North-East Vietnam Adventure - 11 Days" target="_self">North-East Vietnam Adventure - 11 Days</a>
																							</h4>
																						</li>
																						<li class="odd">
																							<h4>
																								<a href="/vietnam-tours/adventures/kayak-halong-bay-explore-cat-ba-island-4-days.html" title="Kayak Halong Bay &amp; Explore Cat Ba Island - 4 Days" target="_self">Kayak Halong Bay &amp; Explore Cat Ba Island - 4 Days</a>
																							</h4>
																						</li>
																						<li class="even">
																							<h4>
																								<a href="/vietnam-tours/adventures/hanoi-mai-chau-ninh-binh-6-days.html" title="Hanoi - Mai Chau - Ninh Binh - 6 Days" target="_self">Hanoi - Mai Chau - Ninh Binh - 6 Days</a>
																							</h4>
																						</li>
																					</ul>
																				</div>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
												<div class=" col-md-4">
													<div class="t3-module module " id="Mod115">
														<div class="module-inner">
															<h3 class="module-title  h3chunho">
																<span>
																	<a href="/vietnam-tours/adventures.html">Vietnam Adventures</a>
																</span>
															</h3>
															<div class="module-ct">
																<div class="nspMain  activated" id="nsp-nsp-115" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																	<div class="nspArts bottom" style="width:100%;">
																		<div class="nspArtScroll1">
																			<div class="nspArtScroll2 nspPages1">
																				<div class="nspArtPage active nspCol1">
																					<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																						<h4 class="nspHeader tleft fnone has-image">
																							<a href="/vietnam-tours/adventures/north-vietnam-grand-adventure-11-days.html" title="North Vietnam Grand Adventure - 11 Days" target="_self">North Vietnam Grand Adventure - 11 Days</a>
																						</h4>
																						<a href="/vietnam-tours/adventures/north-vietnam-grand-adventure-11-days.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																							<img class="nspImage" src="/images/VNTours_Photos/Intro-NorthVietnam-Grand-Adventure_0f9a6.jpg" alt="North Vietnam Grand Adventure thumbnail">
																							</a>
																							<p class="nspText tleft fleft">The Northwest of Vietnam with its breathtaking mountains landscapes and colorful hill tribes is the place for a real adventure discovery. From spectacular Karst Plateau Geopark of Dong Van up...</p>
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																		<div class="nspLinksWrap bottom" style="width:99.9%;">
																			<div class="nspLinks" style="margin:0;">
																				<div class="nspLinkScroll1">
																					<div class="nspLinkScroll2 nspPages1">
																						<ul class="nspList active nspCol1">
																							<li class="even">
																								<h4>
																									<a href="/vietnam-tours/adventures/north-east-vietnam-adventure-11-days.html" title="North-East Vietnam Adventure - 11 Days" target="_self">North-East Vietnam Adventure - 11 Days</a>
																								</h4>
																							</li>
																							<li class="odd">
																								<h4>
																									<a href="/vietnam-tours/adventures/kayak-halong-bay-explore-cat-ba-island-4-days.html" title="Kayak Halong Bay &amp; Explore Cat Ba Island - 4 Days" target="_self">Kayak Halong Bay &amp; Explore Cat Ba Island - 4 Days</a>
																								</h4>
																							</li>
																							<li class="even">
																								<h4>
																									<a href="/vietnam-tours/adventures/hanoi-mai-chau-ninh-binh-6-days.html" title="Hanoi - Mai Chau - Ninh Binh - 6 Days" target="_self">Hanoi - Mai Chau - Ninh Binh - 6 Days</a>
																								</h4>
																							</li>
																						</ul>
																					</div>
																				</div>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
														</div>
													</div>
												</div>
												<!-- SPOTLIGHT -->
											</div>
											<!-- Content mid end -->
											<!-- Content mid -->
											<div class="ts-content-mid">
												<!-- SPOTLIGHT -->
												<div class="t3-spotlight t3-contentmid  row">
													<div class=" col-md-4">
														<div class="t3-module module " id="Mod120">
															<div class="module-inner">
																<h3 class="module-title  h3chunho">
																	<span>
																		<a href="/vietnam-tours/vietnam-honeymoon.html">Vietnam Honeymoon</a>
																	</span>
																</h3>
																<div class="module-ct">
																	<div class="nspMain  activated" id="nsp-nsp-120" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																		<div class="nspArts bottom" style="width:100%;">
																			<div class="nspArtScroll1">
																				<div class="nspArtScroll2 nspPages1">
																					<div class="nspArtPage active nspCol1">
																						<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																							<h4 class="nspHeader tleft fnone has-image">
																								<a href="/vietnam-tours/vietnam-honeymoon/vietnam-for-lovers-10-days.html" title="Vietnam For Lovers - 10 Days" target="_self">Vietnam For Lovers - 10 Days</a>
																							</h4>
																							<a href="/vietnam-tours/vietnam-honeymoon/vietnam-for-lovers-10-days.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																								<img class="nspImage" src="/images/VNTours_Photos/Intro-Vietnam-for-lovers_7ade7.jpg" alt="">
																								</a>
																								<p class="nspText tleft fleft">Congratulations on your marriage and welcome to Vietnam and to this tour that is designed to wow your honeymoon holiday. It visits Ho Chi Minh City, Can Tho, Hoian, Hanoi...</p>
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																			<div class="nspLinksWrap bottom" style="width:99.9%;">
																				<div class="nspLinks" style="margin:0;">
																					<div class="nspLinkScroll1">
																						<div class="nspLinkScroll2 nspPages1">
																							<ul class="nspList active nspCol1">
																								<li class="even">
																									<h4>
																										<a href="/vietnam-tours/vietnam-honeymoon/vietnam-honeymoon-14-days.html" title="Vietnam Honeymoon - 14 Days" target="_self">Vietnam Honeymoon - 14 Days</a>
																									</h4>
																								</li>
																								<li class="odd">
																									<h4>
																										<a href="/vietnam-tours/vietnam-honeymoon/sweet-vietnam-honeymoon-11-days.html" title="Sweet Vietnam Honeymoon - 11 Days" target="_self">Sweet Vietnam Honeymoon - 11 Days</a>
																									</h4>
																								</li>
																								<li class="even">
																									<h4>
																										<a href="/vietnam-tours/vietnam-honeymoon/vietnam-ultimate-honeymoon-16-days.html" title="Vietnam Ultimate Honeymoon - 16 Days" target="_self">Vietnam Ultimate Honeymoon - 16 Days</a>
																									</h4>
																								</li>
																							</ul>
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
														</div>
														<div class=" col-md-4">
															<div class="t3-module module " id="Mod117">
																<div class="module-inner">
																	<h3 class="module-title  h3chunho">
																		<span>
																			<a href="/vietnam-tours/vietnam-beach-breaks.html">Beach Breaks</a>
																		</span>
																	</h3>
																	<div class="module-ct">
																		<div class="nspMain  activated" id="nsp-nsp-117" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																			<div class="nspArts bottom" style="width:100%;">
																				<div class="nspArtScroll1">
																					<div class="nspArtScroll2 nspPages1">
																						<div class="nspArtPage active nspCol1">
																							<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																								<h4 class="nspHeader tleft fnone has-image">
																									<a href="/vietnam-tours/vietnam-beach-breaks/phu-quoc-beach-escape.html" title="Phu Quoc Beach Escape" target="_self">Phu Quoc Beach Escape</a>
																								</h4>
																								<a href="/vietnam-tours/vietnam-beach-breaks/phu-quoc-beach-escape.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																									<img class="nspImage" src="/images/Intro-Phu-Quoc_38031.jpg" alt="">
																									</a>
																									<p class="nspText tleft fleft">A trip to Vietnam would not be complete without a few days of relaxation, and idyllic Phu Quoc rates amongst Vietnam's most secluded destinations.
</p>
																								</div>
																							</div>
																						</div>
																					</div>
																				</div>
																				<div class="nspLinksWrap bottom" style="width:99.9%;">
																					<div class="nspLinks" style="margin:0;">
																						<div class="nspLinkScroll1">
																							<div class="nspLinkScroll2 nspPages1">
																								<ul class="nspList active nspCol1">
																									<li class="even">
																										<h4>
																											<a href="/vietnam-tours/vietnam-beach-breaks/con-dao-island.html" title="Con Dao Island" target="_self">Con Dao Island</a>
																										</h4>
																									</li>
																									<li class="odd">
																										<h4>
																											<a href="/vietnam-tours/vietnam-beach-breaks/mui-ne-beach-relax.html" title="Mui Ne Beach Relax" target="_self">Mui Ne Beach Relax</a>
																										</h4>
																									</li>
																									<li class="even">
																										<h4>
																											<a href="/vietnam-tours/vietnam-beach-breaks/danang-beach-break.html" title="Danang Beach Break" target="_self">Danang Beach Break</a>
																										</h4>
																									</li>
																								</ul>
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
															<div class=" col-md-4">
																<div class="t3-module module " id="Mod117">
																	<div class="module-inner">
																		<h3 class="module-title  h3chunho">
																			<span>
																				<a href="/vietnam-tours/vietnam-beach-breaks.html">Beach Breaks</a>
																			</span>
																		</h3>
																		<div class="module-ct">
																			<div class="nspMain  activated" id="nsp-nsp-117" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																				<div class="nspArts bottom" style="width:100%;">
																					<div class="nspArtScroll1">
																						<div class="nspArtScroll2 nspPages1">
																							<div class="nspArtPage active nspCol1">
																								<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																									<h4 class="nspHeader tleft fnone has-image">
																										<a href="/vietnam-tours/vietnam-beach-breaks/phu-quoc-beach-escape.html" title="Phu Quoc Beach Escape" target="_self">Phu Quoc Beach Escape</a>
																									</h4>
																									<a href="/vietnam-tours/vietnam-beach-breaks/phu-quoc-beach-escape.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																										<img class="nspImage" src="/images/Intro-Phu-Quoc_38031.jpg" alt="">
																										</a>
																										<p class="nspText tleft fleft">A trip to Vietnam would not be complete without a few days of relaxation, and idyllic Phu Quoc rates amongst Vietnam's most secluded destinations.
</p>
																									</div>
																								</div>
																							</div>
																						</div>
																					</div>
																					<div class="nspLinksWrap bottom" style="width:99.9%;">
																						<div class="nspLinks" style="margin:0;">
																							<div class="nspLinkScroll1">
																								<div class="nspLinkScroll2 nspPages1">
																									<ul class="nspList active nspCol1">
																										<li class="even">
																											<h4>
																												<a href="/vietnam-tours/vietnam-beach-breaks/con-dao-island.html" title="Con Dao Island" target="_self">Con Dao Island</a>
																											</h4>
																										</li>
																										<li class="odd">
																											<h4>
																												<a href="/vietnam-tours/vietnam-beach-breaks/mui-ne-beach-relax.html" title="Mui Ne Beach Relax" target="_self">Mui Ne Beach Relax</a>
																											</h4>
																										</li>
																										<li class="even">
																											<h4>
																												<a href="/vietnam-tours/vietnam-beach-breaks/danang-beach-break.html" title="Danang Beach Break" target="_self">Danang Beach Break</a>
																											</h4>
																										</li>
																									</ul>
																								</div>
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																	</div>
																</div>
															</div>
															<!-- SPOTLIGHT -->
														</div>
														<!-- Content mid end -->
														<!-- Content mid -->
														<div class="ts-content-mid">
															<!-- SPOTLIGHT -->
															<div class="t3-spotlight t3-contentmid  row">
																<div class=" col-md-4">
																	<div class="t3-module module " id="Mod119">
																		<div class="module-inner">
																			<h3 class="module-title  h3chunho">
																				<span>
																					<a href="/vietnam-tours/culinary-tours.html">Culinary Tours</a>
																				</span>
																			</h3>
																			<div class="module-ct">
																				<div class="nspMain  activated" id="nsp-nsp-119" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																					<div class="nspArts bottom" style="width:100%;">
																						<div class="nspArtScroll1">
																							<div class="nspArtScroll2 nspPages1">
																								<div class="nspArtPage active nspCol1">
																									<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																										<h4 class="nspHeader tleft fnone has-image">
																											<a href="/vietnam-tours/culinary-tours/vietnamese-cooking-tour-10-days.html" title="Vietnamese Cooking Tour - 10 Days" target="_self">Vietnamese Cooking Tour - 10 Days</a>
																										</h4>
																										<a href="/vietnam-tours/culinary-tours/vietnamese-cooking-tour-10-days.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																											<img class="nspImage" src="/images/Intro-Vietnamese-Cooking_1861e.jpg" alt="">
																											</a>
																											<p class="nspText tleft fleft">This ten-day tour is designed to cover the highlights of Vietnam's must-see places and help you have unforgettable experiences in your life on Vietnam cooking holidays! Learn to prepare authentic...</p>
																										</div>
																									</div>
																								</div>
																							</div>
																						</div>
																						<div class="nspLinksWrap bottom" style="width:99.9%;">
																							<div class="nspLinks" style="margin:0;">
																								<div class="nspLinkScroll1">
																									<div class="nspLinkScroll2 nspPages1">
																										<ul class="nspList active nspCol1">
																											<li class="even">
																												<h4>
																													<a href="/vietnam-tours/culinary-tours/hanoi-cooking-class.html" title="Hanoi Cooking Class" target="_self">Hanoi Cooking Class</a>
																												</h4>
																											</li>
																											<li class="odd">
																												<h4>
																													<a href="/vietnam-tours/culinary-tours/hoian-cooking-tour.html" title="Hoian Cooking Tour" target="_self">Hoian Cooking Tour</a>
																												</h4>
																											</li>
																											<li class="even">
																												<h4>
																													<a href="/vietnam-tours/culinary-tours/saigon-cooking-class.html" title="Saigon Cooking Class" target="_self">Saigon Cooking Class</a>
																												</h4>
																											</li>
																										</ul>
																									</div>
																								</div>
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																	</div>
																	<div class=" col-md-4">
																		<div class="t3-module module " id="Mod116">
																			<div class="module-inner">
																				<h3 class="module-title  h3chunho">
																					<span>
																						<a href="/vietnam-tours/luxury-vietnam-holidays.html">Luxury Vietnam Tours</a>
																					</span>
																				</h3>
																				<div class="module-ct">
																					<div class="nspMain  activated" id="nsp-nsp-116" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																						<div class="nspArts bottom" style="width:100%;">
																							<div class="nspArtScroll1">
																								<div class="nspArtScroll2 nspPages1">
																									<div class="nspArtPage active nspCol1">
																										<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																											<h4 class="nspHeader tleft fnone has-image">
																												<a href="/vietnam-tours/luxury-vietnam-holidays/vietnam-travel-leisure-14-days.html" title="Vietnam Travel &amp; Leisure - 14 Days" target="_self">Vietnam Travel &amp; Leisure - 14 Days</a>
																											</h4>
																											<a href="/vietnam-tours/luxury-vietnam-holidays/vietnam-travel-leisure-14-days.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																												<img class="nspImage" src="/images/VNTours_Photos/Intro-Vietnam-Travel-Leisure_29b1d.jpg" alt="">
																												</a>
																												<p class="nspText tleft fleft">The two week&nbsp;Vietnam Travel &amp; Leisure package offers a luxurious &amp; alluring private-guided getaway through the vibrant &amp; ancient cities of Vietnam to high-end visitors. Stay in the most luxurious...</p>
																											</div>
																										</div>
																									</div>
																								</div>
																							</div>
																							<div class="nspLinksWrap bottom" style="width:99.9%;">
																								<div class="nspLinks" style="margin:0;">
																									<div class="nspLinkScroll1">
																										<div class="nspLinkScroll2 nspPages1">
																											<ul class="nspList active nspCol1">
																												<li class="even">
																													<h4>
																														<a href="/vietnam-tours/luxury-vietnam-holidays/luxury-vietnam-holidays-14-days.html" title="Luxury Vietnam Holidays - 14 Days" target="_self">Luxury Vietnam Holidays - 14 Days</a>
																													</h4>
																												</li>
																												<li class="odd">
																													<h4>
																														<a href="/vietnam-tours/luxury-vietnam-holidays/luxury-heritage-journey-8-days.html" title="Luxury Heritage Journey - 8 Days" target="_self">Luxury Heritage Journey - 8 Days</a>
																													</h4>
																												</li>
																												<li class="even">
																													<h4>
																														<a href="/vietnam-tours/luxury-vietnam-holidays/best-of-hanoi-halong-bay-sapa-6-days.html" title="Best Of Hanoi - Halong Bay - Sapa - 6 Days" target="_self">Best Of Hanoi - Halong Bay - Sapa - 6 Days</a>
																													</h4>
																												</li>
																											</ul>
																										</div>
																									</div>
																								</div>
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																		<div class=" col-md-4">
																			<div class="t3-module module " id="Mod116">
																				<div class="module-inner">
																					<h3 class="module-title  h3chunho">
																						<span>
																							<a href="/vietnam-tours/luxury-vietnam-holidays.html">Luxury Vietnam Tours</a>
																						</span>
																					</h3>
																					<div class="module-ct">
																						<div class="nspMain  activated" id="nsp-nsp-116" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																							<div class="nspArts bottom" style="width:100%;">
																								<div class="nspArtScroll1">
																									<div class="nspArtScroll2 nspPages1">
																										<div class="nspArtPage active nspCol1">
																											<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																												<h4 class="nspHeader tleft fnone has-image">
																													<a href="/vietnam-tours/luxury-vietnam-holidays/vietnam-travel-leisure-14-days.html" title="Vietnam Travel &amp; Leisure - 14 Days" target="_self">Vietnam Travel &amp; Leisure - 14 Days</a>
																												</h4>
																												<a href="/vietnam-tours/luxury-vietnam-holidays/vietnam-travel-leisure-14-days.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																													<img class="nspImage" src="/images/VNTours_Photos/Intro-Vietnam-Travel-Leisure_29b1d.jpg" alt="">
																													</a>
																													<p class="nspText tleft fleft">The two week&nbsp;Vietnam Travel &amp; Leisure package offers a luxurious &amp; alluring private-guided getaway through the vibrant &amp; ancient cities of Vietnam to high-end visitors. Stay in the most luxurious...</p>
																												</div>
																											</div>
																										</div>
																									</div>
																								</div>
																								<div class="nspLinksWrap bottom" style="width:99.9%;">
																									<div class="nspLinks" style="margin:0;">
																										<div class="nspLinkScroll1">
																											<div class="nspLinkScroll2 nspPages1">
																												<ul class="nspList active nspCol1">
																													<li class="even">
																														<h4>
																															<a href="/vietnam-tours/luxury-vietnam-holidays/luxury-vietnam-holidays-14-days.html" title="Luxury Vietnam Holidays - 14 Days" target="_self">Luxury Vietnam Holidays - 14 Days</a>
																														</h4>
																													</li>
																													<li class="odd">
																														<h4>
																															<a href="/vietnam-tours/luxury-vietnam-holidays/luxury-heritage-journey-8-days.html" title="Luxury Heritage Journey - 8 Days" target="_self">Luxury Heritage Journey - 8 Days</a>
																														</h4>
																													</li>
																													<li class="even">
																														<h4>
																															<a href="/vietnam-tours/luxury-vietnam-holidays/best-of-hanoi-halong-bay-sapa-6-days.html" title="Best Of Hanoi - Halong Bay - Sapa - 6 Days" target="_self">Best Of Hanoi - Halong Bay - Sapa - 6 Days</a>
																														</h4>
																													</li>
																												</ul>
																											</div>
																										</div>
																									</div>
																								</div>
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																		</div>
																		<!-- SPOTLIGHT -->
																	</div>
																	<!-- Content mid end -->
																	<!-- Content mid -->
																	<div class="ts-content-mid">
																		<!-- SPOTLIGHT -->
																		<div class="t3-spotlight t3-contentmid  row">
																			<div class=" col-md-4">
																				<div class="t3-module module " id="Mod121">
																					<div class="module-inner">
																						<h3 class="module-title  h3chunho">
																							<span>
																								<a href="/vietnam-cruises.html">Vietnam Cruises</a>
																							</span>
																						</h3>
																						<div class="module-ct">
																							<div class="nspMain  activated" id="nsp-nsp-121" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																								<div class="nspArts bottom" style="width:100%;">
																									<div class="nspArtScroll1">
																										<div class="nspArtScroll2 nspPages1">
																											<div class="nspArtPage active nspCol1">
																												<div class="nspArt nspCol1" style="padding:0 15px 15px 0;">
																													<h4 class="nspHeader tleft fnone has-image">
																														<a href="/vietnam-cruises/mekong-cruises/bassac-cruises-one-night-on-mekong-river.html" title="Bassac Cruises: One night on Mekong River" target="_self">Bassac Cruises: One night on Mekong Rive…</a>
																													</h4>
																													<a href="/vietnam-cruises/mekong-cruises/bassac-cruises-one-night-on-mekong-river.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																														<img class="nspImage" src="/images/Intro-Bassac-Cruise-Mekong-5_58191.jpg" alt="">
																														</a>
																														<p class="nspText tleft fleft">The Bassac Cruises take you into the greener areas of the Mekong Delta, overnight on the river and into the middle of the life about the river. They are entirely...</p>
																													</div>
																												</div>
																											</div>
																										</div>
																									</div>
																									<div class="nspLinksWrap bottom" style="width:99.9%;">
																										<div class="nspLinks" style="margin:0;">
																											<div class="nspLinkScroll1">
																												<div class="nspLinkScroll2 nspPages1">
																													<ul class="nspList active nspCol1">
																														<li class="even">
																															<h4>
																																<a href="/vietnam-cruises/mekong-cruises/indochine-cruise.html" title="Indochine Cruise" target="_self">Indochine Cruise</a>
																															</h4>
																														</li>
																														<li class="odd">
																															<h4>
																																<a href="/vietnam-cruises/mekong-cruises/pandaw-classic-mekong.html" title="Pandaw: Classic Mekong" target="_self">Pandaw: Classic Mekong</a>
																															</h4>
																														</li>
																														<li class="even">
																															<h4>
																																<a href="/vietnam-cruises/mekong-cruises/the-jahan-the-lost-civilization.html" title="The Jahan: The Lost Civilization" target="_self">The Jahan: The Lost Civilization</a>
																															</h4>
																														</li>
																													</ul>
																												</div>
																											</div>
																										</div>
																									</div>
																								</div>
																							</div>
																						</div>
																					</div>
																				</div>
																				<div class=" col-md-4">
																					<div class="t3-module module " id="Mod112">
																						<div class="module-inner">
																							<h3 class="module-title  h3chunho">
																								<span>
																									<a href="/southeast-asia-tours.html">Vietnam &amp; Southeast Asia Tours</a>
																								</span>
																							</h3>
																							<div class="module-ct">
																								<div class="nspMain  activated" id="nsp-nsp-112" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																									<div class="nspArts bottom" style="width:100%;">
																										<div class="nspArtScroll1">
																											<div class="nspArtScroll2 nspPages1">
																												<div class="nspArtPage active nspCol1">
																													<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																														<h4 class="nspHeader tleft fnone has-image">
																															<a href="/southeast-asia-tours/vietnam-cambodia-16-days.html" title="Vietnam &amp; Cambodia - 16 Days" target="_self">Vietnam &amp; Cambodia - 16 Days</a>
																														</h4>
																														<a href="/southeast-asia-tours/vietnam-cambodia-16-days.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																															<img class="nspImage" src="/images/VNTours_Photos/Intro-vietnam-cambodia-16days_61e22.jpg" alt="vietnam cambodia 16days thumbnail">
																															</a>
																															<p class="nspText tleft fleft">Experience the many delights of both Vietnam and Cambodia on a sixteen day journey that&nbsp;explores every side of Vietnam and two major famous cities of Cambodia, includes a speed-boat along...</p>
																														</div>
																													</div>
																												</div>
																											</div>
																										</div>
																										<div class="nspLinksWrap bottom" style="width:99.9%;">
																											<div class="nspLinks" style="margin:0;">
																												<div class="nspLinkScroll1">
																													<div class="nspLinkScroll2 nspPages1">
																														<ul class="nspList active nspCol1">
																															<li class="even">
																																<h4>
																																	<a href="/southeast-asia-tours/legend-of-mekong-9-days.html" title="Legend of Mekong - 9 Days" target="_self">Legend of Mekong - 9 Days</a>
																																</h4>
																															</li>
																															<li class="odd">
																																<h4>
																																	<a href="/southeast-asia-tours/vietnam-myanmar-holiday-20-days.html" title="Vietnam &amp; Myanmar Holiday - 20 Days" target="_self">Vietnam &amp; Myanmar Holiday - 20 Days</a>
																																</h4>
																															</li>
																															<li class="even">
																																<h4>
																																	<a href="/southeast-asia-tours/from-halong-bay-to-luang-prabang-14-days.html" title="From Halong Bay To Luang Prabang - 14 Days" target="_self">From Halong Bay To Luang Prabang - 14 Days</a>
																																</h4>
																															</li>
																														</ul>
																													</div>
																												</div>
																											</div>
																										</div>
																									</div>
																								</div>
																							</div>
																						</div>
																					</div>
																					<div class=" col-md-4">
																						<div class="t3-module module " id="Mod112">
																							<div class="module-inner">
																								<h3 class="module-title  h3chunho">
																									<span>
																										<a href="/southeast-asia-tours.html">Vietnam &amp; Southeast Asia Tours</a>
																									</span>
																								</h3>
																								<div class="module-ct">
																									<div class="nspMain  activated" id="nsp-nsp-112" data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
																										<div class="nspArts bottom" style="width:100%;">
																											<div class="nspArtScroll1">
																												<div class="nspArtScroll2 nspPages1">
																													<div class="nspArtPage active nspCol1">
																														<div class="nspArt nspCol1" style="padding:0 20px 20px 0;">
																															<h4 class="nspHeader tleft fnone has-image">
																																<a href="/southeast-asia-tours/vietnam-cambodia-16-days.html" title="Vietnam &amp; Cambodia - 16 Days" target="_self">Vietnam &amp; Cambodia - 16 Days</a>
																															</h4>
																															<a href="/southeast-asia-tours/vietnam-cambodia-16-days.html" class="nspImageWrapper tleft fleft gkResponsive" style="margin:6px 14px 0 0;" target="_self">
																																<img class="nspImage" src="/images/VNTours_Photos/Intro-vietnam-cambodia-16days_61e22.jpg" alt="vietnam cambodia 16days thumbnail">
																																</a>
																																<p class="nspText tleft fleft">Experience the many delights of both Vietnam and Cambodia on a sixteen day journey that&nbsp;explores every side of Vietnam and two major famous cities of Cambodia, includes a speed-boat along...</p>
																															</div>
																														</div>
																													</div>
																												</div>
																											</div>
																											<div class="nspLinksWrap bottom" style="width:99.9%;">
																												<div class="nspLinks" style="margin:0;">
																													<div class="nspLinkScroll1">
																														<div class="nspLinkScroll2 nspPages1">
																															<ul class="nspList active nspCol1">
																																<li class="even">
																																	<h4>
																																		<a href="/southeast-asia-tours/legend-of-mekong-9-days.html" title="Legend of Mekong - 9 Days" target="_self">Legend of Mekong - 9 Days</a>
																																	</h4>
																																</li>
																																<li class="odd">
																																	<h4>
																																		<a href="/southeast-asia-tours/vietnam-myanmar-holiday-20-days.html" title="Vietnam &amp; Myanmar Holiday - 20 Days" target="_self">Vietnam &amp; Myanmar Holiday - 20 Days</a>
																																	</h4>
																																</li>
																																<li class="even">
																																	<h4>
																																		<a href="/southeast-asia-tours/from-halong-bay-to-luang-prabang-14-days.html" title="From Halong Bay To Luang Prabang - 14 Days" target="_self">From Halong Bay To Luang Prabang - 14 Days</a>
																																	</h4>
																																</li>
																															</ul>
																														</div>
																													</div>
																												</div>
																											</div>
																										</div>
																									</div>
																								</div>
																							</div>
																						</div<
			
																					</div>
																					<!-- SPOTLIGHT -->
																				</div>
																				<!-- Content mid end -->
																				<!-- Content mid -->
																				<!-- Content mid end -->
																				<!-- Content Bottom-->
																				<!-- //Content top end-->
																				<!-- //CONTENT MAST TOP -->
																				<div class="blog-featured" itemscope="" itemtype="https://schema.org/Blog"></div>
																			</div>
																			<!-- //MAIN CONTENT -->
																		</div>
																	</div>
																</div>