
<div id="mainbody-wr">
	<div id="mainbody" class="home container">

			<div id="">
				<div class="box_skitter box_skitter_large">
					<ul>
						<li>
							<a href="#a"><img src="images/slider/S1.jpg" class="cut" /></a>
						</li>
						<li>
							<a href="#swapBlocks"><img src="images/slider/S2.jpg" class="swapBlocks" /></a>
						</li>
						<li>
							<a href="#swapBarsBack"><img src="images/slider/S3.jpg" class="swapBarsBack" /></a>
						</li>
						<li>
							<a href="#swapBars"><img src="images/slider/S4.jpg" class="swapBars" /></a>
						</li>
					</ul>
				</div>
			</div>
		
			<div style="clear: both; height: 8px"></div>
			<div class="col-xs-12 col-sm-12 col-md-8">
				<div class="ts-content-top ">
						<div class="t3-module module " id="Mod113"><div class="module-inner"><h2 class="module-title  h3chunho customhome"><span>PLAN YOUR VIETNAM TOUR</span></h2><div class="module-ct">﻿﻿﻿ 
<div id="customcustomized_tour">
<div class="form-area">  
<form action="/customized-tour.html" method="post" role="form" data-toggle="validator">
<div class="form-group">
If you would rather create your own itinerary, we would be happy to assist you in putting together one that best suits your schedule and interest. Then send us your requests, we will respond to you within 12 hours.</div>
						 <div class="form-group col-md-3 col-sm-6 khongcachtrai">
                    <select name="paticipant" class="form-control batbuoc" required="">
							<option value="" selected="">Number of travelers?</option>
							<option value="1">1 Person</option>
							<option value="2">2 Persons</option>
							<option value="3">3 Persons</option>
							<option value="4">4 Persons</option>
							<option value="5">5 Persons</option>
							<option value="6">6 Persons</option>
							<option value="7">7 Persons</option>
							<option value="8">8 Persons</option>
							<option value="9">9 Persons</option>
							<option value="10">10 Persons</option>
							<option value="999">&gt; 10 Persons</option>
							</select></div> 
<div class="form-group col-md-3 col-sm-6 khongcachtrai">
						<select name="lengthoftrip" class="form-control batbuoc" style="width:auto;" required="">
									<option value="">How many days?</option>
									<option value="1">1 days</option>
									<option value="2">2 days</option>
									<option value="3">3 days</option>
									<option value="4">4 days</option>
									<option value="5">5 days</option>
									<option value="6">6 days</option>
									<option value="7">7 days</option>
									<option value="8">8 days</option>
									<option value="9">9 days</option>
									<option value="10">10 days</option>
									<option value="11">11 days</option>
									<option value="12">12 days</option>
									<option value="13">13 days</option>
									<option value="14">14 days</option>
									<option value="15">15 days</option>
									<option value="16">16 days</option>
									<option value="17">17 days</option>
									<option value="18">18 days</option>
									<option value="19">19 days</option>
									<option value="20">20  days</option>
					</select>
					</div>
					<div class="form-group col-md-2 col-sm-6 khongcachtrai cachphai5">
					<select name="hotelcategory" class="form-control batbuoc" style="width:auto;" required="">
										<option value="">Hotel category</option>
										<option value="3">3 Stars</option>
										<option value="4">4 Stars</option>
										<option value="5">5 Stars</option>
										<option value="6">Top Luxury</option>
					</select>
					</div>
					<div class="form-group col-md-2 col-sm-6">
					<input type="text" class="form-control formdatehome hasDatepicker" id="datepickerhomehh" name="date" placeholder="Travel Date" required="">
					</div>
                   
<div class="form-group col-md-1 col-sm-6 khongcachtrai">           
		<input type="hidden" name="task" value="">
		<input type="hidden" name="option" value="com_customizedtour">
        <button aria-label="Submit" type="submit" id="submit" name="submit" class="btn btn-primary khongcachtren fa fa-sign-in vongtron"></button>

</div>
</form>
</div>
</div>
</div></div></div>
					</div>
			</div>
			
		</div>
	</div>
	
</div>