<!-- HUYHOA.COM -->
<div class="container bienthuy-spot bienthuy-spot-1">
	<div class="ts-slidefull">
		<div class="col-xs-12 slidehuyhoa">
			<!-- Columns start at 100% wide on mobile and bump up to 33.3% wide on desktop -->
			<!--[if lte IE 7]>
			<link href="/modules/mod_slideshowck/themes/default/css/camera_ie.css" rel="stylesheet" type="text/css" />
			<![endif]-->
			<!--[if IE 8]>
			<link href="/modules/mod_slideshowck/themes/default/css/camera_ie8.css" rel="stylesheet" type="text/css" />
			<![endif]-->
			<!-- debut Slideshow CK -->
			<div class="slideshowck camera_wrap camera_amber_skin"
				id="camera_wrap_90">
				<?php foreach ($this->images as $img){?>
					<?php if($img['STATUS'] == 1){?>
        				<div data-src="<?php echo $img['IMAGE']?>">
        					<div class="camera_caption fadeFromBottom">
        						Vietnam Visa Tour. <em></em>
        					</div>
        				</div>
    				<?php }?>
				<?php }?>				
			</div>
			<div style="clear: both;"></div>
		</div>
	</div>
</div>
<!-- //HUYHOA.COM -->
<div class="home">
	<div id="bienthuy-mainbody"
		class="container bienthuy-mainbody one-sidebar-right">
		<div class="row">
			<!-- MAIN CONTENT -->
			<div id="bienthuy-content"
				class="bienthuy-content col-xs-12 col-sm-12 col-md-12">
				<!-- Content Top-->
				<div class="ts-content-top " style="display: none">
					<div class="t3-module module " id="Mod113">
						<div class="module-inner">
							<h2 class="module-title  h3chunho customhome">
								<span>PLAN YOUR VIETNAM TOUR</span>
							</h2>
							<div class="module-ct">							
								<div id="customcustomized_tour">
									<div class="form-area">
										<form action="/customized-tour.html" method="post" role="form"
											data-toggle="validator">
											<div class="form-group">If you would rather create your own
												itinerary, we would be happy to assist you in putting
												together one that best suits your schedule and interest.
												Then send us your requests, we will respond to you within 12
												hours.</div>
											<div class="form-group col-md-3 col-sm-6 khongcachtrai">
												<select name="paticipant" class="form-control batbuoc"
													required="">
													<option value="" selected="">Number of travelers?</option>
													<option value="1">1 Person</option>
													<option value="2">2 Persons</option>
													<option value="3">3 Persons</option>
													<option value="4">4 Persons</option>
													<option value="5">5 Persons</option>
													<option value="6">6 Persons</option>
													<option value="7">7 Persons</option>
													<option value="8">8 Persons</option>
													<option value="9">9 Persons</option>
													<option value="10">10 Persons</option>
													<option value="999">&gt; 10 Persons</option>
												</select>
											</div>
											<div class="form-group col-md-3 col-sm-6 khongcachtrai">
												<select name="lengthoftrip" class="form-control batbuoc"
													style="width: auto;" required="">
													<option value="">How many days?</option>
													<option value="1">1 days</option>
													<option value="2">2 days</option>
													<option value="3">3 days</option>
													<option value="4">4 days</option>
													<option value="5">5 days</option>
													<option value="6">6 days</option>
													<option value="7">7 days</option>
													<option value="8">8 days</option>
													<option value="9">9 days</option>
													<option value="10">10 days</option>
													<option value="11">11 days</option>
													<option value="12">12 days</option>
													<option value="13">13 days</option>
													<option value="14">14 days</option>
													<option value="15">15 days</option>
													<option value="16">16 days</option>
													<option value="17">17 days</option>
													<option value="18">18 days</option>
													<option value="19">19 days</option>
													<option value="20">20 days</option>
												</select>
											</div>
											<div
												class="form-group col-md-2 col-sm-6 khongcachtrai cachphai5">
												<select name="hotelcategory" class="form-control batbuoc"
													style="width: auto;" required="">
													<option value="">Hotel category</option>
													<option value="3">3 Stars</option>
													<option value="4">4 Stars</option>
													<option value="5">5 Stars</option>
													<option value="6">Top Luxury</option>
												</select>
											</div>
											<div class="form-group col-md-2 col-sm-6">
												<input type="text"
													class="form-control formdatehome hasDatepicker"
													id="datepickerhomehh" name="date" placeholder="Travel Date"
													required="">
											</div>
											<div class="form-group col-md-1 col-sm-6 khongcachtrai">
												<input type="hidden" name="task" value=""> <input
													type="hidden" name="option" value="com_customizedtour">
												<button aria-label="Submit" type="submit" id="submit"
													name="submit"
													class="btn btn-primary khongcachtren fa fa-sign-in vongtron"></button>
											</div>
										</form>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!-- //Content top end-->
				<!-- Content mid -->
				<div class="ts-content-mid">
					<!-- SPOTLIGHT -->
					<?php foreach($this->hot_tour as $arr){?>
					<div class="t3-spotlight t3-contentmid  row">
										<?php foreach($arr as $hot){?>
										<div class=" col-md-4">
							<div class="t3-module module " id="Mod129">
								<div class="module-inner">
									<h3 class="module-title  h3chunho">
										<span> <a href="javascript:void(0)"><?php foreach ($this->tour_level_1 as $level_1){if($level_1->id == $hot->parent_id) echo $level_1->name; }?></a>
										</span>
									</h3>
									<div class="module-ct">
										<div class="nspMain  activated" id="nsp-nsp-129"
											data-config="{
				'animation_speed': 400,
				'animation_interval': 5000,
				'animation_function': 'Fx.Transitions.Expo.easeIn',
				'news_column': 1,
				'news_rows': 1,
				'links_columns_amount': 1,
				'links_amount': 3
			}">
											<div class="nspArts bottom" style="width: 100%;">
												<div class="nspArtScroll1">
													<div class="nspArtScroll2 nspPages1">
														<div class="nspArtPage active nspCol1">
															<div class="nspArt nspCol1"
																style="padding: 0 20px 20px 0;">
																<h4 class="nspHeader tleft fnone has-image">
																	<a
																		href="/tour/<?php echo $hot->tour_type_id?>-<?php echo str_replace(' ', '-', $hot->name)?>"																		
																		title="<?php echo $hot->name; ?>" target="_self"><?php echo $hot->name; ?></a>
																</h4>
																<a
																	href="/tour/<?php echo $hot->tour_type_id?>-<?php echo str_replace(' ', '-', $hot->name)?>"
																	class="nspImageWrapper tleft fleft gkResponsive"
																	style="margin: 6px 14px 0 0;" target="_self"> <img
																	class="nspImage" src="<?php echo $hot->image_small; ?>"
																	alt="<?php echo $hot->name; ?>">
																</a>
																<p class="nspText tleft fleft"><?php echo $hot->short_desc; ?></p>
															</div>
														</div>
													</div>
												</div>
											</div>
											<div class="nspLinksWrap bottom" style="width: 99.9%;">
												<div class="nspLinks" style="margin: 0;">
													<div class="nspLinkScroll1">
														<div class="nspLinkScroll2 nspPages1">
															<ul class="nspList active nspCol1">
																				<?php foreach($this->tour as $another){ if($another->is_hot == 0 && $another->parent_id == $hot->parent_id){?>																					
																					<li class="even">
																	<h4>
																		<a
																			href="/tour/<?php echo $another->tour_type_id?>-<?php echo str_replace(' ', '-', $another->name)?>"
																			title="<?php echo $another->name;?>" target="_self"><?php echo $another->name;?></a>
																	</h4>
																</li>
																				<?php }}?>
																				</ul>
														</div>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>																				
						<?php }?>
												
					
					<!-- SPOTLIGHT -->
				</div>
				<?php }?>
				<!-- Content mid end -->
				<!-- Content mid -->
				<!-- Content mid end -->
				<!-- Content mid -->
				<!-- Content mid end -->
				<!-- Content Bottom-->
				<!-- //Content top end-->
				<!-- //CONTENT MAST TOP -->
				<div class="blog-featured" itemscope=""
					itemtype="https://schema.org/Blog"></div>
			</div>
			<!-- //MAIN CONTENT -->
		</div>
	</div>
</div>