<div id="center_cont">
	<div class="acticle_index">
		<div class="b_head"><a href="" target="_self">Điểm bán</a></div>
		<div class="news-detail">
			<div class="place-item">
				<div class="p-title"><p>Miền bắc</p></div>
				<div class="place-list">
					<div class="region"><a href="">Hà Nội</a></div>
					<div class="region"><a href="">Nam Định</a></div>
					<div class="region"><a href="">Ninh Bình</a></div>
					<div class="region"><a href="">Hải Phòng</a></div>
					<div class="region"><a href="">Bắc Ninh</a></div>
					<div class="region"><a href="">Hòa Bình</a></div>
					<div class="region"><a href="">Hưng Yên</a></div>
					<div class="region"><a href="">Phú Thọ</a></div>
					<div class="region"><a href="">Vĩnh Phúc</a></div>
					<div class="region"><a href="">Thái Bình</a></div>
					<div class="region"><a href="">Sơn Tây</a></div>
					<div class="region"><a href="">Tuyên Quang</a></div>
					<div class="region"><a href="">Cao Bằng</a></div>
					<div class="region"><a href="">Lào Cai</a></div>
					<div class="region"><a href="">Quảng Ninh</a></div>
					<div class="region"><a href="">Sơn La</a></div>
					<div class="region"><a href="">Điện Biên</a></div>
				</div>
			</div>
			
			<div class="place-item">
				<div class="p-title"><p>Miền trung</p></div>
				<div class="place-list">
					<div class="region"><a href="">Thanh Hóa</a></div>
					<div class="region"><a href="">Nghệ An</a></div>
					<div class="region"><a href="">Hà Tĩnh</a></div>
					<div class="region"><a href="">Quảng Nam</a></div>
					<div class="region"><a href="">Thừa Thiên Huế</a></div>
					<div class="region"><a href="">Đà Nẵng</a></div>
					<div class="region"><a href="">Phú Yên</a></div>
					<div class="region"><a href="">Quảng Bình</a></div>
				</div>
			</div>
			
			<div class="place-item p-title-last">
				<div class="p-title"><p>Miền nam</p></div>
				<div class="place-list">
					<div class="region"><a href="">TP Hồ Chí Minh</a></div>
					<div class="region"><a href="">Hậu Giang</a></div>
					<div class="region"><a href="">Vũng Tàu</a></div>
					<div class="region"><a href="">Bình Dương</a></div>
					<div class="region"><a href="">Vĩnh Long</a></div>
					<div class="region"><a href="">Đắc Lắc</a></div>
					<div class="region"><a href="">Long An</a></div>
					<div class="region"><a href="">Kiên Giang</a></div>
					<div class="region"><a href="">Bạc Liêu</a></div>
					<div class="region"><a href="">Lâm Đồng</a></div>
					<div class="region"><a href="">Sóc Trăng</a></div>
					<div class="region"><a href="">Bình Thuận</a></div>
					<div class="region"><a href="">Cà Mau</a></div>
					<div class="region"><a href="">Bình Phước</a></div>
					<div class="region"><a href="">Khánh Hòa</a></div>
				</div>
			</div>
		</div>
	</div>
</div>