<div id="mainbody-wr">		
	<div id="mainbody">
		<div id="product-d-name">G034A (4 phụ kiện)</div>
		<div id="product-detail">
			<div class="product-d-right">
				<div class="p-detail-img-left">
					<script type="text/javascript">
						$(document).ready(function() {
							$('.jqzoom').jqzoom({
									zoomType: 'reverse',
									preloadImages: false,
									alwaysOn:false,
									zoomHeight: 398,
									zoomWidth: 448,
									imageOpacity: 0.8,
									lens: false
								});
							//$('.jqzoom').jqzoom();
						});
					</script>
					<div style="width: 100%; text-align: center; color: #444; font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-weight: bold; margin: 5px 0px 5px 0px;">Di chuột vào ảnh để phóng to</div>
					<div class="clearfix" id="content" style="height:400px;width:330px;" >
						<div class="clearfix">
							<a href="/images/triumph_big1.jpg" class="jqzoom" rel='gal1'  title="zoom" > <!-- zoom image -->
								<img style="width: 308px; height: 247px; border: 1px solid #666" src="/images/triumph_big1.jpg"  title="" > <!-- ảnh đại diện -->
							</a>
						</div>
						<br/>
						<div class="clearfix" >
						<ul id="thumblist" class="clearfix" >
							<li><a class="zoomThumbActive" href='javascript:void(0);' rel="{gallery: 'gal1', smallimage: '/images/triumph_big1.jpg', largeimage: '/images/triumph_big1.jpg'}"><img class="product-d-image-list" src='/images/triumph_big1.jpg'></a></li>
							<li><a href='javascript:void(0);' rel="{gallery: 'gal1', smallimage: '/images/triumph_big2.jpg',largeimage: '/images/triumph_big2.jpg'}"><img class="product-d-image-list" src='/images/triumph_big2.jpg'></a></li>
							<li><a  href='javascript:void(0);' rel="{gallery: 'gal1', smallimage: '/images/triumph_big3.jpg',largeimage: '/images/triumph_big3.jpg'}"><img class="product-d-image-list" src='/images/triumph_big3.jpg'></a></li>
						</ul>
						</div>
					</div>
				</div>
				<div class="p-detail-info">
					<div class="detail-item">
						<div class="detail-title">Mã sản phẩm:</div>
						<div class="detail-value">H399</div>
					</div>
					<div class="detail-item">
						<div class="detail-title">Màu sắc:</div>
						<div class="detail-value">Nâu</div>
					</div>
					<div class="detail-item">
						<div class="detail-title">Chất liệu:</div>
						<div class="detail-value">Da thật</div>
					</div>
					<div class="detail-item">
						<div class="detail-title">Xuất xứ:</div>
						<div class="detail-value">Hàng Việt Nam</div>
					</div>
					<div class="detail-item">
						<div class="detail-title proDetail_price">Giá:</div>
						<div class="detail-value proDetail_price"><span class="detail-old-price">250.000</span>200.000</div>
					</div>
					<div class="detail-item" style="height:auto;">
						<div class="detail-title proDetail_markRed" style="height:auto;">Khuyến mại:</div>
						<div class="detail-value" style="height:auto; width: 260px;">Tặng 1 ví da nam cao cấp khi mua sản phẩm, áp dụng cho 100 khách hàng đầu tiên trong ngày</div>
					</div>
					<div class="p-detail-order">
					<!-- order -->
						<a href=""><img style="margin-top: 10px;" src="/images/order.png" /></a>
					</div>
					<div class="detail-item" style="color: #D40000; margin-top: 10px" >
						Hotline: 098 123 45678
					</div>
					<div class="detail-item">
						<a href="" >[Hướng dẫn mua hàng]</a>
					</div>
				</div>
				
				<div class="p-detail-describe">
					<div id="TabbedPanels1" class="TabbedPanels">
					  <ul class="TabbedPanelsTabGroup">
						<li class="TabbedPanelsTab" tabindex="0">Mô tả sản phẩm</li>
						<li class="TabbedPanelsTab" tabindex="0">Thông tin chi tiết</li>
					  </ul>
					<div class="TabbedPanelsContentGroup">
						<div class="TabbedPanelsContent">Content 1</div>
						<div class="TabbedPanelsContent">Content 2</div>
					  </div>
					  </div>
					<script type="text/javascript">
					var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1");
					</script>	
				</div>
			</div>
			<div class="product-d-left">
				<div class="product-de-hotlist">
					<div style="padding-bottom: 5px; clear: both;font-size: 14px;font-weight: bold;font-family: Arial,Helvetica,sans-serif;border-bottom: 1px solid #CCC; text-align: center">SẢN PHẨM HOT</div>
					<!-- product list -->
					<div class="product-rightlist-img"><a href="#" title="#"><img src="/images/products/001.jpg" /></a><div class="discount_hotlist">-20%</div></div>
					<div class="product-rightlist-title"><a href="">Giày da nam H399</a></div>
					<div class="product-rightlist-price detail-mark-red">Giá: <span class="hotlist_old_price">250.000</span></br>200.000</div>
					<div class="product-rightlist-promotion detail-mark-red">Khuyến mại:<span style="font-size: 12px; color: #888; text-align: center; font-weight: normal">Tặng ví da nam cao cấp</span></div>
					<!-- end loop -->
					<div class="product-rightlist-img"><a href="#" title="#"><img src="/images/products/002.jpg" /></a></div>
					<div class="product-rightlist-title"><a href="">Ba lô da cao cấp</a></div>
					<div class="product-rightlist-price detail-mark-red">Giá: 700.000</div>
					
					<div class="product-rightlist-img"><a href="#" title="#"><img src="/images/products/003.jpg" /></a></div>
					<div class="product-rightlist-title"><a href="">Ví da đứng</a></div>
					<div class="product-rightlist-price detail-mark-red">Giá: 1.200.000</div>
					
					<div class="product-rightlist-img"><a href="#" title="#"><img src="/images/products/004.jpg" /></a></div>
					<div class="product-rightlist-title"><a href="">Cặp đeo chéo</a></div>
					<div class="product-rightlist-price detail-mark-red">Giá: 2.000.000</div>
					<div class="product-rightlist-promotion detail-mark-red">Khuyến mại:<span style="font-size: 12px; color: #888; text-align: center; font-weight: normal">Tặng ví da nam cao cấp</span></div>
					
				</div>
			</div>
		</div>
	</div>
</div>