<div class="acticle_index">
	<div class="b_head"><a target="_self">Chuyên gia tư vấn</a></div>
	
	<div class="late_advise_con">
		<div class="l_link"><a href="/index/question/1">Thuốc trị đau dạ dày</a></div>
		<div>
			<p><span style="font-weight: bold; color:#000; line-height: 20px;">Người hỏi: &nbsp </span>Hà Gia Cường (<i>cuonggalaxy1976@yahoo.com.vn</i>)</p>
			<p><span style="font-weight: bold; color:#000; line-height: 20px;">Ngày gửi: &nbsp </span>12/08/2014 16:05</p>
			<p><span style="font-weight: bold; color:#000;">Câu hỏi: &nbsp </span>Kính chào BS em bị bệnh đau dạ dày từ năm 2004 đến nay, em đã đi nội soi 3 lần, lần thứ 1 và thứ 2 tại Bệnh viện Đa khoa tỉnh Bình Dương, lần thứ 3 tại Trung tâm Hòa Hảo, TPHCM. Kết quả 3 lần đều như nhau: "Viêm hang vị". Từ thời gian đó đến bây giờ em uống rất nhiều loại thuốc, thuốc tây, thuốc dân gian.........nhưng bệnh không khỏi. Hiện tại em đã sử dụng được 2 hộp CumirNano, nhưng vẫn chưa thấy đỡ hơn, triệu chứng khó chịu hơn khi chưa sử dụng CumirNano như: buồn nôn, buổi sáng thì ợ ra nước chua. Bên cạnh đó em sử dụng thuốc đúng như "hướng  dẫn": ngày uống 2 lần, 1 lần 2 viên sau ăn 1 giờ. Bác sĩ cho em xin ý kiến tình trạng của em, bây giờ em đang sử dụng hộp thứ 3 nhưng rất phân vân là: không biết có nên dùng tiếp hay ngưng, hay sử dụng sao có hiệu quả hơn, Rất mong sự giúp đỡ chỉ dẫn của các Bác sĩ, em chân thành biết ơn! Bình Dương 05-08-2014</p>
			<p style="font-style: italic; color:#666;"><span style="font-style: none !important; font-weight: bold; color:#000; line-height: 18px;">Trả lời: &nbsp </span>
				<!-- answer content -->
				<br/>Chào bạn !
				<br/>Bạn bị viêm hang vị dạ dày 10 năm nay nhưng không biết có bị bệnh lý tiêu hóa gì kèm theo không như trào ngược dạ dày - thực quản... Với tình trạng bệnh của bạn thì bạn có chế độ ăn uống kiêng khem hợp lý chưa, bạn có thường xuyên lo lắng, căng thẳng, stress...không? Có đang sử dụng thuốc tây không?
			</p>
		</div>
	</div>
			
</div>