<div id="mainbody-wr">
	<div id="mainbody">
		<div id="left-cell">
			<div id="fb-box">
			<!-- 
				<iframe src="http://www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fhanaku.vn&amp;width=190&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:190px; height:290px;" allowTransparency="true"></iframe>
			-->
			</div>
			<div style="clear: both; height: 8px"></div>
			<div class="left_tab">
				<div class="left_tab_text">Loại sản phẩm</div>
			</div>
			<div class="leftmenu_box">
			<?php foreach ($this->types as $type) {?>
				<div class="leftmenu-item">
					<a href="/index/filter?type=<?php echo $type->id?>"><?php echo $type->name?></a>
				</div>
			<?php }?>
			</div>
			<div style="clear: both; height: 8px"></div>
			<div style="clear: both; height: 8px"></div>
			<div class="left_tab">
				<div class="left_tab_text">Khoảng giá</div>
			</div>
			<div class="leftmenu_box">
				<div class="leftmenu-item">
					<a href="/index/filter?min=200000">Dưới 200.000</a>
				</div>
				<div class="leftmenu-item">
					<a href="/index/filter?min=200000&max=500000">200.000 - 500.000</a>
				</div>
				<div class="leftmenu-item">
					<a href="/index/filter?min=500000&max=1000000">500.000 - 1.000.000</a>
				</div>
				<div class="leftmenu-item">
					<a href="/index/filter?min=1000000&max=1500000">1.000.000 - 1.500.000</a>
				</div>
				<div class="leftmenu-item">
					<a href="/index/filter?max=1500000">Trên 1.500.000</a>
				</div>
			</div>
		</div>

		<div id="right-cell">
			<div id="top-slider">
				<div class="box_skitter box_skitter_large">
					<ul>
						<li>
							<a href="#cut"><img src="/images/slider/S1.jpg" class="cut" /></a>
							<div class="label_text"><p>cut</p></div>
						</li>
						<li>
							<a href="#swapBlocks"><img src="/images/slider/S2.jpg" class="swapBlocks" /></a>
							<div class="label_text"><p>swapBlocks</p></div>
						</li>
						<li>
							<a href="#swapBarsBack"><img src="/images/slider/S3.jpg" class="swapBarsBack" /></a>
							<div class="label_text"><p>swapBarsBack</p></div>
						</li>
						<li>
							<a href="#swapBars"><img src="/images/slider/S4.jpg" class="swapBars" /></a>
							<div class="label_text"><p>swapBars</p></div>
						</li>
					</ul>
				</div>
			</div>
			
			<!-- loop -->
			<div style="clear:both; height: 10px"> &nbsp; </div>
			<div class="center_tab">
				<div class="center_tab_text" style="white-space: nowrap;">Tìm kiếm sản phẩm</div>
			</div>
			<div style="clear:both; height: 10px"> &nbsp; </div>
			
			<div class="productList-grid">
			<?php foreach ($this->products as $product) {?>
				<div class="productGrid" >
					<div class="box01 box02">
						<div class="product_img">
							<a href="/product/detail?id=<?php echo $product['ID']?>" title="<?php echo $product['NAME']?>"><img title="<?php echo $product['NAME']?>" alt="<?php echo $product['NAME']?>" src="<?php echo $product['IMAGE_MAIN']?>" width="180px" /></a>
							<?php if(!is_null($product['DISCOUNT_PRICE'])) {?><div class="product-discount-grid">-<?php echo floor((1 - $product['DISCOUNT_PRICE']/$product['PRICE'])*100)?>%</div><?php }?>
						</div>
						<div class="product_factory"><?php echo $product['CODE']?></div>
						<div class="product_title"><a href="" title="<?php echo $product['NAME']?>"><?php echo $product['NAME']?></a></div>
						
						<?php if(!is_null($product['DISCOUNT_PRICE'])) {?>
						<div class="product_home_price" align="center">Giá: <span style="font-size: 12px; color: #888; text-decoration: line-through;"><?php echo number_format($product['PRICE'], $decimals = 0 , $dec_point = "," , $thousands_sep = ".")?></span></div>
						<div class="product_home_price" align="center"><?php echo number_format($product['DISCOUNT_PRICE'], $decimals = 0 , $dec_point = "," , $thousands_sep = ".")?></div>
						<?php } else {?>
						<div class="product_home_price" align="center"><?php echo number_format($product['PRICE'], $decimals = 0 , $dec_point = "," , $thousands_sep = ".")?></div>
						<?php }?>
						
						<?php if(!is_null($product['PROMOTION'])) {?>
						<div class="product_home_promotional" align="center"><span style="font-weight: bold; color: #CC0000;">Khuyến mại:</span> <?php echo $product['PROMOTION']?></div>
						<?php }?>
					</div>
				</div>
			<?php }?>
				<div style="clear: both;"></div>
			</div>
		</div>
	</div>
</div>