<div class="home">
		<div id="bienthuy-mainbody" class="container bienthuy-mainbody one-sidebar-right">
	<div class="row">
		<!-- MAIN CONTENT -->
		<div id="bienthuy-content" class="bienthuy-content col-xs-12 col-sm-12 col-md-8">
					<!-- Content Top-->
			<div class="item-page clearfix">
<!-- Article -->
<article>
	<header class="article-header clearfix">
	<div class="row">
		
<div class="col-xs-12 col-md-9">
	<h1 class="article-title"><a href="/vietnam-tours/culture-history-tours/vietnam-orientation-8-days.html" title="<?php echo $this->tour->name?>"><?php echo $this->tour->name?></a></h1>
</div>
<div class="col-xs-12 col-md-3">
				<span class="blogprice pricecam chunghieng">from: $ <strong><?php echo $this->tour->price?></strong> /pp</span>
</div>
</div>
</header>


	
	<a class="label label-info" href="<?php echo $this->parent->url?>"><?php echo $this->parent->name?></a>
	<a class="label label-info" href="javascript:void(0)">Vietnam Tours</a><meta itemprop="author" content="Bien Thuy" id="author">
<meta itemprop="datePublished" content="" id="date">
<meta itemprop="dateModified" content="" id="datemodified">
<div itemtype="https://schema.org/Organization" itemscope="itemscope" itemprop="publisher">
<meta itemprop="name" content="Asia Travel and Leisure Co., Ltd">
<meta itemprop="url" href="https://asiatravelandleisure.com">
<span itemprop="logo" itemscope="" itemtype="https://schema.org/ImageObject">
<meta itemprop="url" content="https://asiatravelandleisure.com/templates/bienthuy/themes/color_blue/images/Logo-Asia-Travel-Leisure.png">
<meta itemprop="width" content="auto"><meta itemprop="height" content="auto"></span>
</div>


<div class="slider-wrapper theme-default article_images_block images-1-2-3-4-5-6-7-8-9" style="margin: 0px 0; 	">
	<style>.fotorama1542105207235 .fotorama__nav--thumbs .fotorama__nav__frame{
padding:4px;
height:66.666666666667px}
.fotorama1542105207235 .fotorama__thumb-border{
height:62.666666666667px;
border-width:2px;
margin-top:4px}</style><div class="fotorama--hidden"></div>
			<div class="slideshowck camera_wrap camera_amber_skin"
				id="camera_wrap_90">
				<?php foreach ($this->tour->image as $img){?>
        				<div data-src="<?php echo $img?>">
        				</div>
				<?php }?>
			</div>
			<div style="clear: both;"></div>	
</div>
		<script type="text/javascript" src="https://bienthuy.com/pub/fotorama/jquery.min.js"></script>
	<script type="text/javascript" src="https://bienthuy.com/pub/fotorama/jquery-migrate-1.1.0.min.js"></script>
		<script type="text/javascript" src="https://bienthuy.com/pub/fotorama/jquery.min.js"></script>
	<script type="text/javascript" src="https://bienthuy.com/pub/fotorama/jquery-migrate-1.1.0.min.js"></script>
<link href="https://bienthuy.com/pub/fotorama/foto.css'; ?&gt;" rel="stylesheet">
<script src="https://bienthuy.com/pub/fotorama/foto.js'; ?&gt;"></script>	
	
<section class="article-content clearfix">
					<div class="pull-left item-image article-image article-image-full">
			<div class="img_caption none" style="float: none; width: 1920px;"><img class="caption" title="Bitexco building" src="/images/VNTours_Photos/Saigon-8_d89bb.jpg" alt="Bitexco building - Saigon"><p class="img_caption">Bitexco building</p></div>
		</div>
	
	
	
	<div class="nomobile" style="margin-top: 20px;"><span style="line-height: 16.5px;"><?php echo $this->tour->short_desc?></span></div>
 
<p></p>
				<div class="row cachtop" itemscope="" itemtype="http://schema.org/Product">  
							<div class="col-xs-8 col-md-8">							
    							  <p class="thongtintour"><strong>Duration: </strong><?php echo $this->tour->duration?></p>
    							  <p class="thongtintour"><strong>Codes: </strong><?php echo $this->tour->code?></p>
    							  <p class="thongtintour indam"><strong>Price from : </strong><span class="cam">$<?php echo $this->tour->price?></span></p>						 
							  </div>
				</div>
				<!-- START BIENTHUY.COM DIV -->
				<div class="clearfix">&nbsp;</div>
				<div class="row cachtop">
   <div class="col-xs-12 col-md-12">
      <div class="panel-group">
         <div class="panel panel-bienthuy">
            <div class="panel-heading border-bienthuy">
               <div class="row cachtop">
                  <div class="col-xs-10">
                     <h3 class="panel-title" id="price" data-toggle="collapse" href="#panel-price">PRICE</h3>
                  </div>
                  <div class="col-xs-2 text-right">
                     <a data-toggle="collapse" href="#panel-price"><i class="fa fa-angle-double-down ht18"></i></a>
                  </div>
               </div>
            </div>
            <div id="panel-price" class="panel-collapse collapse in">
               <div class="panel-body backgroundxam">
                  <div class="alert alert-success">Prices are quoted in <strong>US Dollars per person</strong>.</div>
                  <div id="bienthuy-responsive-table">
                     <table class="col-md-12 table-striped table-condensed cf">
                        <tbody>
                        <?php if($this->tour->price_type == 1){?>
                        	<?php if(sizeof($this->type_1_group) > 0){?>
                               <tr>
                                  <th colspan="3"><?php echo $this->tour->price_type == 1 ? 'GROUP TOUR' : ''?></th>
                               </tr>
                             <?php }?>
                        	<?php $i = 0;foreach($this->type_1_group as $t){++$i;?>
                                <tr>
                                  <?php if(trim($t->to_pax) != ''){?>
                                  	<th><?php echo $t->from_pax?>-<?php echo $t->to_pax?> pax</th>
                                  <?php } else{?>
                                  	<th><?php echo $i == sizeof($this->type_1_group) ? '&gt;=' : '' ?> <?php echo $t->from_pax?> pax</th>
                                  <?php }?>
                                  <td data-title="Price" class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price);?></span></td>
                                  <td data-title="" class="numeric htcenter"><a href="<?php echo $this->tour->book_url.'/'.$t->id;?>" title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                               </tr>
                            <?php }?>
                           	<?php if(sizeof($this->type_1_private) > 0){?>
                               <tr>
                                  <th colspan="3"><?php echo $this->tour->price_type == 1 ? 'PRIVATE TOUR' : ''?></th>
                               </tr>
                             <?php }?>
                             <?php  $i = 0;foreach($this->type_1_private as $t){++$i;?>
                                <tr>
                                  <?php if(trim($t->to_pax) != ''){?>
                                  	<th><?php echo $t->from_pax?>-<?php echo $t->to_pax?> pax</th>
                                  <?php } else{?>
                                  	<th><?php echo $i == sizeof($this->type_1_private) ? '&gt;=' : '' ?><?php echo $t->from_pax?> pax</th>
                                  <?php }?>
                                  <td data-title="Price" class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price);?></span></td>
                                  <td data-title="" class="numeric htcenter"><a href="<?php echo $this->tour->book_url.'/'.$t->id;?>" title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                               </tr>
                           <?php }?>
                        <?php }?>
                        <?php if($this->tour->price_type == 2){?>
                        	<?php foreach($this->type_2 as $t){ if($t->tour_price_group_id==$this->HOMESTAY_DORM_ID){?>
                        		<tr>
                        			<th>Homestay/dorm room</th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price)?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url;?>" title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                        	<?php }else if($t->tour_price_group_id==$this->HOMESTAY_PRIVATE_ID){?>
                        		<tr>
                        			<th>Homestay/private room</th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price)?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url?>" title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                           <?php }else if($t->tour_price_group_id==$this->HOTEL_2_STAR_ID){?>
                        		<tr>
                        			<th>2* Hotel</th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price)?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url;?>" title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                        	<?php }else if($t->tour_price_group_id==$this->HOTEL_3_STAR_ID){?>
                        		<tr>
                        			<th>3* Hotel</th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price)?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url;?>" title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                        	<?php }else if($t->tour_price_group_id==$this->HOTEL_4_STAR_ID){?>
                        		<tr>
                        			<th>4* Hotel</th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price)?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url;?>" title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                           <?php }else if($t->tour_price_group_id==$this->HOTEL_5_STAR_ID){?>
                        		<tr>
                        			<th>5* Hotel</th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price)?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url;?>" title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                        	<?php }?>
                        	<?php }?>
                        	<?php foreach($this->type_2_add_price as $t){?>
                        		<tr>
                        			<th><?php echo $t->name?></th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price + $this->type_2[sizeof($this->type_2)-1]->price);?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url;?>" title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                        	<?php }?>
                        <?php }?>
                        <?php if($this->tour->price_type == 3){?>
                        	<?php foreach($this->type_3 as $t){ if($t->tour_price_group_id==$this->CRUISE_3_STAR_ID){?>
                        		<tr>
                        			<th>3* Cruise</th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price)?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url;?>"  title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                        	<?php }else if($t->tour_price_group_id==$this->CRUISE_4_STAR_ID){?>
                        		<tr>
                        			<th>4* Cruise</th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price)?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url;?>"  title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                           <?php }else if($t->tour_price_group_id==$this->CRUISE_4_PLUS_STAR_ID){?>
                        		<tr>
                        			<th>4*++ Cruise</th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price)?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url;?>"  title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                        	<?php }else if($t->tour_price_group_id==$this->CRUISE_5_STAR_ID){?>
                        		<tr>
                        			<th>5* Cruise</th>
                        			<td class="htcenter"><span class="chudam pricecam">$<?php echo number_format($t->price)?></span></td>
                        			<td data-title="" class="numeric htcenter"><a href="<?php echo $t->book_url;?>"  title="Request tour: <?php echo $this->tour->name?>">Reservation</a></td>
                        		</tr>
                        	<?php }?>
                        	<?php }?>
                        <?php }?>
                        </tbody>
                     </table>
                  </div>
               </div>
               <!-- end panel-body -->
            </div>
         </div>
         <!-- end panel-default -->
      </div>
   </div>
</div>
				<div class="panel-group">
					<div class="panel panel-bienthuy">
									<div class="panel-heading border-bienthuy">
										<div class="row cachtop">
											<div class="col-xs-10">
												<h3 class="panel-title" id="price" data-toggle="expand" href="#panel-price">TOUR DETAILS</h3>
											</div>
											<div class="col-xs-2 text-right">
												<a data-toggle="collapse" href="#panel-price"><i class="fa fa-angle-double-down ht18"></i></a>
											</div>
										</div>
									</div>
									<div id="panel-price" class="panel-collapse collapse in">
										<div class="panel-body backgroundxam">										  

									<div>
										<?php echo $this->tour->details?>
									</div>


										</div><!-- end panel-body -->
									</div>
							</div>
						<!-- end panel-default -->

</div>	
<!-- CLOSE PRICE -->
<!-- CLOSE HIGHLIGHTS DIV -->
<!-- CLOSE ITINERARY DIV -->
<!-- CLOSE TRAVEL MAPS DIV -->
<!-- CLOSE FAQS DIV -->
<div class="extranews_separator"></div>
<?php if(sizeof($this->tours) > 1) {?>
<div class="extranews_box"><h3><strong>Other <?php echo $this->parent->name?></strong></h3><div class="extranews_huyhoa">
	<ul class="huyhoa">
	<?php foreach($this->tours as $tour) {?>
		<?php if($tour->tour_type_id != $this->tour->tour_type_id){?>
		<li><a href="<?php echo $tour->url?>" title="<?php echo $tour->name?>"><?php echo $tour->name?></a></li>
	<?php }};?>
	</ul></div>
</div>
<?php }?>
	</section>
	
	
	</article>
<!-- //Article -->
</div>							 
</div>
<div
				class="bienthuy-sidebar bienthuy-sidebar-right col-xs-12 col-sm-12 col-md-4" style="padding-top: 0px;">
				<div class="t3-module module " id="Mod89">
					<div class="module-inner">
						<h3 class="module-title  h3chunho">
							<span>Recommended Tours</span>
						</h3>
						<div class="module-ct">
							<div class="nspMain  activated" id="nsp-nsp-89" data-config="">

								<div class="nspArts bottom" style="width: 100%;">
									<div class="nspArtScroll1">
										<div class="nspArtScroll2 nspPages1">
											<?php foreach($this->random as $t){?>
    											<?php if($t->name != $this->tour->name){?>
    											<div class="nspArtPage active nspCol1" style="margin-bottom: 10px;">
    												<div class="nspArt nspCol1" style="padding: 0 20px 20px 0;">
    													<h4 class="nspHeader tleft fnone has-image">
    														<a
    															href="<?php echo $t->url?>"
    															title="<?php echo $t->name?>"
    															target="_self"><?php echo $t->name?></a>
    													</h4>
    													<a href="<?php echo $t->url?>"><img class="nspImage"
    														src="<?php echo $t->image_small?>"
    														alt="<?php echo $t->name?>"></a>
    												</div>
    											</div>
											<?php }}?>
											</div>
										</div>

									</div>
								</div>


							</div>
						</div>
					</div>
				</div>
			</div>
</div>
</div>