<div class="home">
		<div id="bienthuy-mainbody" class="container bienthuy-mainbody one-sidebar-right">
	<div class="row">
		<!-- MAIN CONTENT -->
		<div id="bienthuy-content" class="bienthuy-content col-xs-12 col-sm-12 col-md-8">
					<!-- Content Top-->
			<div class="item-page clearfix">
<!-- Article -->
<article>
	<header class="article-header clearfix">
	<div class="row">
		
<div class="col-xs-12 col-md-9">
	<h1 class="article-title"><a href="/vietnam-tours/culture-history-tours/vietnam-orientation-8-days.html" title="<?php echo $this->tour->name?>"><?php echo $this->tour->name?></a></h1>
</div>
<div class="col-xs-12 col-md-3">
				<span class="blogprice pricecam chunghieng">from: $ <strong><?php echo $this->tour->price?></strong> /pp</span>
</div>
</div>
</header>


	
	<a class="label label-info" href="/tours/<?php echo $this->parent->id?>-<?php echo str_replace(' ', '-', $this->parent->name)?>"><?php echo $this->parent->name?></a>
	<a class="label label-info" href="javascript:void(0)">Vietnam Tours</a><meta itemprop="author" content="Bien Thuy" id="author">
<meta itemprop="datePublished" content="" id="date">
<meta itemprop="dateModified" content="" id="datemodified">
<div itemtype="https://schema.org/Organization" itemscope="itemscope" itemprop="publisher">
<meta itemprop="name" content="Asia Travel and Leisure Co., Ltd">
<meta itemprop="url" href="https://asiatravelandleisure.com">
<span itemprop="logo" itemscope="" itemtype="https://schema.org/ImageObject">
<meta itemprop="url" content="https://asiatravelandleisure.com/templates/bienthuy/themes/color_blue/images/Logo-Asia-Travel-Leisure.png">
<meta itemprop="width" content="auto"><meta itemprop="height" content="auto"></span>
</div>


<div class="slider-wrapper theme-default article_images_block images-1-2-3-4-5-6-7-8-9" style="margin: 0px 0; 	">
	<style>.fotorama1542105207235 .fotorama__nav--thumbs .fotorama__nav__frame{
padding:4px;
height:66.666666666667px}
.fotorama1542105207235 .fotorama__thumb-border{
height:62.666666666667px;
border-width:2px;
margin-top:4px}</style><div class="fotorama--hidden"></div>
	<div class="slideshowck camera_wrap camera_amber_skin"
				id="camera_wrap_90">
				<?php foreach ($this->tour->image as $img){?>
        				<div data-src="<?php echo $img?>">
        				</div>
				<?php }?>
			</div>
			<div style="clear: both;"></div>	
</div>
		<script type="text/javascript" src="https://bienthuy.com/pub/fotorama/jquery.min.js"></script>
	<script type="text/javascript" src="https://bienthuy.com/pub/fotorama/jquery-migrate-1.1.0.min.js"></script>
		<script type="text/javascript" src="https://bienthuy.com/pub/fotorama/jquery.min.js"></script>
	<script type="text/javascript" src="https://bienthuy.com/pub/fotorama/jquery-migrate-1.1.0.min.js"></script>
<link href="https://bienthuy.com/pub/fotorama/foto.css'; ?&gt;" rel="stylesheet">
<script src="https://bienthuy.com/pub/fotorama/foto.js'; ?&gt;"></script>	
	
<section class="article-content clearfix">
					<div class="pull-left item-image article-image article-image-full">
			<div class="img_caption none" style="float: none; width: 1920px;"><img class="caption" title="Bitexco building" src="/images/VNTours_Photos/Saigon-8_d89bb.jpg" alt="Bitexco building - Saigon"><p class="img_caption">Bitexco building</p></div>
		</div>
	
	
	
	<div class="nomobile" style="margin-top: 20px;"><span style="line-height: 16.5px;"><?php echo $this->tour->short_desc?></span></div>
 
<p>
		<!--<div id="sticky-wrapper" class="stickyhuyhoa-collapse" data-tmpl-sticky="true" data-tmpl-offset="30" style="height: 52px;">
					<ul role="tablist" class="nav stickyhuyhoa hidden-xs" id="menustop">
                        <li><a href="#price"  data-toggle="collapse" class="nav-scroll scroll-price">Tour Price</a></li>
                        <li><a href="#itinerary" data-toggle="collapse" class="nav-scroll scroll-itinerary">Full Itinerary</a></li>
                        <li><a href="#exclude" class="nav-scroll scroll-options" data-toggle="collapse">Inclusions &amp; Exclusions</a></li>
                        <li><a href="#tourmap"  data-toggle="collapse" class="nav-scroll scroll-options">Tour map</a></li>
                        <li><a href="#FAQs"  data-toggle="collapse" class="nav-scroll scroll-reviews">Questions & Answers</a></li>
                    </ul></div> -->
		</p><div class="row cachtop" itemscope="" itemtype="http://schema.org/Product">  
							<div class="col-xs-8 col-md-8">							
    							  <p class="thongtintour"><strong>Duration: </strong><?php echo $this->tour->duration?></p>
    							  <p class="thongtintour"><strong>Codes: </strong><?php echo $this->tour->code?></p>
    							  <p class="thongtintour"><strong>Price: </strong>$<?php echo $this->tour->price?></p>
    							  <p class="thongtintour"><strong>Departure: </strong>Daily, upon your request.</p>    							 
							  </div>
							<div class="col-xs-12 col-md-4">							  

							  <div class="row center">
								<div class="col-xs-12 col-md-12">
								<a href="/tour-book/<?php echo $this->tour->tour_type_id;?>-<?php echo str_replace(' ', '-', $this->tour->name)?>" title="Request tour: <?php echo $this->tour->name;?>"><span class="booktour-button">REQUEST THIS TOUR</span></a>								
								</div>
							</div>
							  
							 
							</div>
				<!-- START BIENTHUY.COM DIV -->
				<div class="clearfix">&nbsp;</div>
				<div class="row cachtop">
				<div class="col-xs-12 col-md-12">
				<div class="panel-group">
					<div class="panel panel-bienthuy">
									<div class="panel-heading border-bienthuy">
										<div class="row cachtop">
											<div class="col-xs-10">
												<h3 class="panel-title" id="price" data-toggle="expand" href="#panel-price">TOUR DETAILS</h3>
											</div>
											<div class="col-xs-2 text-right">
												<a data-toggle="collapse" href="#panel-price"><i class="fa fa-angle-double-down ht18"></i></a>
											</div>
										</div>
									</div>
									<div id="panel-price" class="panel-collapse collapse in">
										<div class="panel-body backgroundxam">										  

									<div>
										<?php echo $this->tour->details?>
									</div>


										</div><!-- end panel-body -->
									</div>
							</div>
						<!-- end panel-default -->

</div>	</div>	</div>	
<!-- CLOSE PRICE -->
<!-- CLOSE HIGHLIGHTS DIV -->
<!-- CLOSE ITINERARY DIV -->
<!-- CLOSE TRAVEL MAPS DIV -->
<!-- CLOSE FAQS DIV -->
<div class="extranews_separator"></div>
<?php if(sizeof($this->tours) > 1) {?>
<div class="extranews_box"><h3><strong>Other <?php echo $this->parent->name?></strong></h3><div class="extranews_huyhoa">
	<ul class="huyhoa">
	<?php foreach($this->tours as $tour) {?>
		<?php if($tour->tour_type_id != $this->tour->tour_type_id){?>
		<li><a href="/tour/<?php echo $tour->tour_type_id?>-<?php echo str_replace(' ', '-', $tour->name)?>" title="<?php echo $tour->name?>"><?php echo $tour->name?></a></li>
	<?php }};?>
	</ul></div>
</div>
<?php }?>
	</section>
	
	
	</article>
<!-- //Article -->
</div>							 
</div>
</div>
</div>