<div class="home">
	<div id="bienthuy-mainbody"
		class="container bienthuy-mainbody one-sidebar-right">
		<div class="row">
			<!-- MAIN CONTENT -->
			<div id="bienthuy-content"
				class="bienthuy-content col-xs-12 col-sm-12 col-md-8">
				<!-- Content Top-->
				<div id="system-message-container">
					<div id="system-message">
						<div class="alert alert-message">
							<a class="close" data-dismiss="alert">×</a>

							<h4 class="alert-heading">Message</h4>
							<div>
								<div class="alert-message">
									<center>
										<font color="#000000"><h1><?php echo $this->tour->name?></h1>
											<br>
										<p>
												<i class="fa fa-thumbs-up"></i> &nbsp;Your request has been
												sent to Vietnam Visa Tours. Thank you.<br>One of our travel
												consultants will get back to you shortly.<br>Your <b>Request
													Code</b>: <font color="#0066ff"><?php echo $this->request_code?> </font>
											</p></font>									
										<br>
										<a href="/" class="booktour-button">Go back to the
											Home page</a>
									</center>
									<i>* NOTE: If you don't receive our email reply in your inbox
										in the next 24 hours, please check your spam folder, or call
										us: <i class="fa" fa-phone=""></i> 0084999 999 999.
									</i>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>