<div>
   <p>Dear <?php echo $this->name;?>,</p>
   <p>Thanks so much for booking tours with us,</p>
   <p>Kindly inform you that we have got your request information as bellow:</p>
   Request code: <?php echo $this->request_code?><br>
   Interested in tour: <font color="green"><a href="http://vietnamvisatours.com<?php echo $this->url?>" target="_blank"><?php echo $this->tour_name?></a></font><br>Name: <font
      color="green"><?php echo $this->name;?></font><br>Email: <font color="green"><a
      href="mailto:<?php echo $this->email?>" target="_blank"><?php echo $this->email;?></a></font><br>Phone
   number: <font color="red"></font><font color="green"><?php echo $this->phone?></font><br>
  Nationality: <font color="green"><?php echo $this->nationality?></font><br>Travel
   date: <font color="green"><?php echo $this->arivaldate?></font><br>Number
   of pax: <font color="green"><?php echo $this->no_traveller?> </font>
   person(s)<br>Total Price: <font color="green"><?php echo $this->total_price?> </font>
   <br>Type: <font color="green"><?php echo $this->booking_type?> </font>
   <br>Your comment
   (optional): <font color="green"><?php echo $this->comment?></font>
   
   <p>Best Regards,</p>
   
   <p>Website: <a href="http://vietnamvisatours.com" target="_blank">vietnamvisatours.com</a></p>
   <p>Phone: <?php echo $this->hotline;?></p>
   <p>Office Address: <?php echo $this->address;?></p>
</div>