<div id="mainbody-wr">
	<div id="mainbody">
		<div id="left-cell">
			<div id="fb-box">
			<!--
				<iframe src="http://www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fhanaku.vn&amp;width=190&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:190px; height:290px;" allowTransparency="true"></iframe>
			-->
			</div>
			<div style="clear: both; height: 8px"></div>
			<div class="left_tab">
				<div class="left_tab_text">Loại sản phẩm</div>
			</div>
			<div class="leftmenu_box">
			<?php foreach ($this->types as $type) {?>
				<div class="leftmenu-item">
					<a href="/index/filter?type=<?php echo $type->id?>"><?php echo $type->name?></a>
				</div>
			<?php }?>
			</div>
			<div style="clear: both; height: 8px"></div>
			<div class="left_tab">
				<div class="left_tab_text">Khoảng giá</div>
			</div>
			<div class="leftmenu_box">
				<div class="leftmenu-item">
					<a href="/index/filter?min=200000">Dưới 200.000</a>
				</div>
				<div class="leftmenu-item">
					<a href="/index/filter?min=200000&max=500000">200.000 - 500.000</a>
				</div>
				<div class="leftmenu-item">
					<a href="/index/filter?min=500000&max=1000000">500.000 - 1.000.000</a>
				</div>
				<div class="leftmenu-item">
					<a href="/index/filter?min=1000000&max=1500000">1.000.000 - 1.500.000</a>
				</div>
				<div class="leftmenu-item">
					<a href="/index/filter?max=1500000">Trên 1.500.000</a>
				</div>
			</div>
		</div>

		<div id="right-cell">
			<div id="top-slider">
				<div class="box_skitter box_skitter_large">
					<ul>
						<li>
							<a href="#cut"><img src="/images/slider/001.jpg" class="cut" /></a>
							<div class="label_text"><p>cut</p></div>
						</li>
						<li>
							<a href="#swapBlocks"><img src="/images/slider/002.jpg" class="swapBlocks" /></a>
							<div class="label_text"><p>swapBlocks</p></div>
						</li>
						<li>
							<a href="#swapBarsBack"><img src="/images/slider/003.jpg" class="swapBarsBack" /></a>
							<div class="label_text"><p>swapBarsBack</p></div>
						</li>
						<li>
							<a href="#swapBars"><img src="/images/slider/004.jpg" class="swapBars" /></a>
							<div class="label_text"><p>swapBars</p></div>
						</li>
					</ul>
				</div>
			</div>
			
			<!-- loop -->
			<div style="clear:both; height: 10px"> &nbsp; </div>
		<?php foreach ($this->products as $product){?>
			<div class="center_tab">
				<div class="center_tab_text" style="white-space: nowrap;"><?php echo $product->typeName?></div>
				<div class="center_tab_text_right"><a  href="" title="Xem tất cả">Xem tất cả</a> &raquo;</div>
			</div>
			<div style="clear:both; height: 10px"> &nbsp; </div>
			<div class="product_content_home">
				<div style="clear:both; height:15px;">&nbsp;</div>
				<div id="product_line">
				<?php foreach ($product->priorities as $priority){?>
					<div class="box01">
						<div class="product_img">
							<a href="" title=""><img title="" alt="" src="<?php echo $priority['IMAGE_MAIN']?>" width="180px" /></a>
							<!-- hien thi khi co giam gia-->
							<?php if(!is_null($priority['DISCOUNT_PRICE'])){?>
							<div class="product-discount">-<?php echo floor((1 - $priority['DISCOUNT_PRICE']/$priority['PRICE'])*100)?>%</div>
							<?php }?>
						</div>
						<div class="product_factory"><?php echo $priority['CODE']?></div>
						<div class="product_title"><a href="" title="<?php echo $priority['NAME']?>"><?php echo $priority['NAME']?></a></div>
						<?php if(is_null($priority['DISCOUNT_PRICE'])) {?>
						<div class="product_home_price" align="center"><?php echo number_format($priority['PRICE'], $decimals = 0 , $dec_point = "," , $thousands_sep = ".")?></div>
						<?php } else {?>
						<div class="product_home_price" align="center">Giá: <span style="font-size: 12px; color: #888; text-decoration: line-through;"><?php echo number_format($priority['PRICE'],$decimals = 0 , $dec_point = "," , $thousands_sep = ".")?></span></div>
						<div class="product_home_price" align="center"><?php echo number_format($priority['DISCOUNT_PRICE'], $decimals = 0 , $dec_point = "," , $thousands_sep = ".")?></div>
						<?php }?>
						<?php if(!is_null($priority['PROMOTION'])) {?><div class="product_home_promotional" align="center"><span style="font-weight: bold; color: #CC0000;">Khuyến mại:</span> <?php echo $priority['PROMOTION']?></div><?php } ?>
					</div>
				<?php }?>
				</div>
			</div>
			<div style="clear:both;">&nbsp;</div><div style="clear:both; height: 10px"> &nbsp; </div>
			<!-- end loop product-line -->
		<?php }?>
			<div style="clear:both;">&nbsp;</div>	
		</div>
	</div>
</div>