<style>
h3,h4 {
 color: #191818;
}
</style>
<div class="home">
		<div id="bienthuy-mainbody" class="container bienthuy-mainbody one-sidebar-right">
	<div class="row">
		<!-- MAIN CONTENT -->
		<div id="bienthuy-content" class="bienthuy-content col-xs-12 col-sm-12 col-md-8">
		<div class="page-header">
    		<h2>
    			<span class="contact-name" itemprop="name">FAQ</span>
    		</h2>
		</div>
		<div class="visa_faq">
				<?php echo $this->setting->visafaq?>
		</div>
		</div>
	</div>	
</div>