<div style="border:rgb(221,221,221) 1px solid;padding:10px">
        <p>Hi <?php echo $this->contact_name?>,</p>

        <p>Thank you for booking with <a href="https://vietnamvisatours.com/" target="_blank">vietnamvisatours.com</a></p>

        <h4>Your booking code is <mark><strong><?php echo $this->booking_code;?></strong></mark></h4>

        <p>Kindly inform you that we have got your payment.</p>
        <p>We are processing your invitation letter.
		Once the letter is issued, we will send it to you immediately.</p>
        <br>
        <p>If you have any question, please do not hesitate to contact us.</p>
        <p>Best wishes,</p>
       
       <p>Website: <a href="http://vietnamvisatours.com" target="_blank">vietnamvisatours.com</a></p>
       <p>Phone: <?php echo $this->hotline;?></p>
       <p>Office Address: <?php echo $this->address;?></p>

</div>