<div style="border:rgb(221,221,221) 1px solid;padding:10px">
        <p>Hi <?php echo $this->contact_name?>,</p>

        <p>Thank you for booking with <a href="https://vietnamvisatours.com/" target="_blank">vietnamvisatours.com</a></p>

        <h4>Your booking code is <mark><strong><?php echo $this->booking_code;?></strong></mark></h4>

        <p>We have received your information, please check information below again.</p>
        <div class="m_4850890863703252059row" style="padding-left:20px;padding-right:20px">
            <ul class="m_4850890863703252059list-group">
               
                <li>Visa type:  <span style="font-weight:bold"><?php echo $this->purposeOfVisit;?>, <?php echo $this->type_of_visa;?></span>

                </li>
                <li>Arrival Date:  <span style="font-weight:bold"><?php echo $this->arrival_date;?></span>

                </li>

                <li>Processing Time:  <span style="font-weight:bold"><?php echo $this->processing_time;?></span>

                </li>

                <li>Shared Visa or Private Visa:  <span style="font-weight:bold"><?php echo $this->private;?></span>

                </li>

            </ul>
        </div>
        <hr>
<table>
    <tbody><tr>
        <td>
             <h3><?php echo $this->fullname1?></h3>
        </td>
        <td style="text-align:right">  
        </td>
    </tr>
    <tr>
        <td>
            <img src="https://vietnamvisatours.com<?php echo $this->image1?>">
        </td>
        <td>
            		<ul>
            			<li>Nationality: <b><?php echo $this->nationality1?></b></li>
            			<li>Date Of Birth: <b><?php echo $this->dateOfBirth1?></b></li>
            			<li>Passport number: <b><?php echo $this->passport_number1?></b></li>
            			<li>Expiry date: <b><?php echo $this->passportExpiryDate1?></b></li>
                        <li>Gender: <b><?php echo $this->gender1?></b></li>                                                                        
                    </ul>
        </td>
    </tr>
	</tbody>
</table>
<?php if($this->numberApp >= 2){?>
<hr>
<table>
    <tbody><tr>
        <td>
             <h3><?php echo $this->fullname2?></h3>
        </td>
        <td style="text-align:right">        	
        </td>
    </tr>
    <tr>
        <td>
            <img src="https://vietnamvisatours.com<?php echo $this->image2?>">
        </td>
        <td>
            		<ul>
            			<li>Nationality: <b><?php echo $this->nationality2?></b></li>
            			<li>Date Of Birth: <b><?php echo $this->dateOfBirth2?></b></li>
                        <li>Passport number: <b><?php echo $this->passport_number2?></b></li>
                        <li>Expiry date: <b><?php echo $this->passportExpiryDate2?></b></li>
                        <li>Gender: <b><?php echo $this->gender2?></b></li>                        
                    </ul>
        </td>
    </tr>
	</tbody>
</table>
<?php }?>
<?php if($this->numberApp >= 3){?>
<hr>
<table>
    <tbody><tr>
        <td>
             <h3><?php echo $this->fullname3?></h3>
        </td>
        <td style="text-align:right">
        </td>
    </tr>
    <tr>
        <td>
            <img src="https://vietnamvisatours.com<?php echo $this->image3?>">
        </td>
        <td>
            		<ul>
            			<li>Nationality: <b><?php echo $this->nationality3?></b></li>
                        <li>Date Of Birth: <b><?php echo $this->dateOfBirth3?></b></li>                        
                        <li>Passport number: <b><?php echo $this->passport_number3?></b></li>
                        <li>Expiry date: <b><?php echo $this->passportExpiryDate3?></b></li>
                        <li>Gender: <b><?php echo $this->gender3?></b></li>                        
                    </ul>
        </td>
    </tr>
	</tbody>
</table>
<?php }?>
<?php if($this->numberApp >= 4){?>
<hr>
<table>
    <tbody><tr>
        <td>
             <h3><?php echo $this->fullname4?></h3>
        </td>
        <td style="text-align:right">
        </td>
    </tr>
    <tr>
        <td>
            <img src="https://vietnamvisatours.com<?php echo $this->image4?>">
        </td>
        <td>
            		<ul>     
            			<li>Nationality: <b><?php echo $this->nationality4?></b></li>                   
                        <li>Date Of Birth: <b><?php echo $this->dateOfBirth4?></b></li>
                        <li>Passport number: <b><?php echo $this->passport_number4?></b></li>
                        <li>Expiry date: <b><?php echo $this->passportExpiryDate4?></b></li>
                        <li>Gender: <b><?php echo $this->gender4?></b></li>
                    </ul>
        </td>
    </tr>
	</tbody>
</table>
<?php }?>
<?php if($this->numberApp >= 5){?>
<hr>
<table>
    <tbody><tr>
        <td>
             <h3><?php echo $this->fullname5?></h3>
        </td>
        <td style="text-align:right">
        </td>
    </tr>
    <tr>
        <td>
            <img src="https://vietnamvisatours.com<?php echo $this->image5?>">
        </td>
        <td>
            		<ul>      
            			<li>Nationality: <b><?php echo $this->nationality5?></b></li>                 
                        <li>Date Of Birth: <b><?php echo $this->dateOfBirth5?></b></li>
                        <li>Passport number: <b><?php echo $this->passport_number5?></b></li>
                        <li>Expiry date: <b><?php echo $this->passportExpiryDate5?></b></li>
                        <li>Gender: <b><?php echo $this->gender5?></b></li>
                    </ul>
        </td>
    </tr>
	</tbody>
</table>
<?php }?>
<?php if($this->numberApp >= 6){?>
<hr>
<table>
    <tbody><tr>
        <td>
             <h3><?php echo $this->fullname6?></h3>
        </td>
        <td style="text-align:right">
        </td>
    </tr>
    <tr>
        <td>
            <img src="https://vietnamvisatours.com<?php echo $this->image6?>">
        </td>
        <td>
            		<ul>    
            		   	<li>Nationality: <b><?php echo $this->nationality6?></b></li>                    
                        <li>Date Of Birth: <b><?php echo $this->dateOfBirth6?></b></li>
                        <li>Passport number: <b><?php echo $this->passport_number6?></b></li>
                        <li>Expiry date: <b><?php echo $this->passportExpiryDate6?></b></li>
                        <li>Gender: <b><?php echo $this->gender6?></b></li>
                    </ul>
        </td>
    </tr>
	</tbody>
</table>
<?php }?>
<hr>

        <br>
        <p>If there is any mistake, please correct the mistake through this</p>
        <p><a href="https://vietnamvisatours.com/visa-apply-online/<?php echo $this->booking_code;?>" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://vietnamvisatours.com/visa-apply-online/<?php echo $this->booking_code;?>;source=gmail&amp;ust=1544002809935000&amp;usg=AFQjCNHwIbJF_W6Prhqo0jOhZWm5GxV5wg">https://vietnamvisatours.com/visa-apply-online/<?php echo $this->booking_code;?></a></p>
        <br>
        <p>Kindly support us to pay <b><?php echo $this->totalPrice?><?php echo $this->totalPriceVND?></b> with the link payment:</p>
        <p><b>Visa/Master/American Express/JCB Card:</b>  <a href="http://vietnamvisatours.com/secure/onepay/<?php echo $this->booking_code?>" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://vietnamvisatours.com/secure/onepay/<?php echo $this->booking_code?>">http://vietnamvisatours.com/secure/onepay/<?php echo $this->booking_code?></a><br>

        <p>We look forward to hearing from you,</p>


       <p>Best Regards,</p>
       
       <p>Website: <a href="http://vietnamvisatours.com" target="_blank">vietnamvisatours.com</a></p>
       <p>Phone: <?php echo $this->hotline;?></p>
       <p>Office Address: <?php echo $this->address;?></p>

</div>