<style>
.search {
    margin: 15px;
}
input {
    border-radius: 5px;
    border: 1px solid #BBBBBB;
    height: 20px;
    color: #666666;
}
.btn-primary {

}
</style>
<article class="module width_full">

		<form name="form_add" method="GET" class="search">						
			<input type="text" name="keyword" id="keyword" value="<?php echo $this->keyword;?>"/>
			<input type="submit" value="Search" class="btn-primary"/>									
		</form>
		<header><h3 class="tabs_involved">Manage Tour Booking</h3>
		</header>
		<div class="tab_container">
			<div class="tab_content" id="tab1" style="display: block;">
			<table cellspacing="0" class="tablesorter"> 
			<thead> 
				<tr> 
   					<th class="header" style="width:15%;">Tour</th>
    				<th class="header">Type</th> 
    				<th class="header">Pax</th>
    				<th class="header">Total Price</th>
    				<th class="header">Customer Name</th>
    				<th class="header">Customer Phone</th>
    				<th class="header">Customer Email</th>
    				<th class="header">Arrival Date</th>
    				<th class="header">Status</th> 
    				<th class="header"></th> 
				</tr> 
			</thead> 
			<tbody> 
			   <?php $i=0; foreach ($this->bookings as $booking) {
				       // Zend_Debug::dump($product);die;
									
				?>
				<tr>
    				<td><?php echo $booking->tour_name;?></td> 
    				<td><?php echo $booking->price_group_name;?></td>
    				<td><?php echo $booking->no;?></td>
    				<td><?php echo $booking->total_price;?></td>
    				<td><?php echo $booking->name;?></td>
    				<td><?php echo $booking->phone;?></td>
    				<td><?php echo $booking->email;?></td>
    				<td><?php echo $booking->arrival_date;?></td>
    				<td><?php echo $booking->status;?></td>
    				<td>
						<a style="display: none" href="/admin/tour/bookingEdit/id/<?php echo $booking->id;?>"><image src="/images/edit.png" alt="Edit" style="padding-right:30px;"/></a>						
					</td> 
				</tr> 
				
				<?php }	?>
				  
			</tbody> 
			</table>
			</div><!-- end of #tab1 -->
			
			
		
		</article>