
			
			
<?php 
  if($this->errorMessage != null && $this->errorMessage != ''){
	echo "<h4 class='alert_error'>".$this->errorMessage."</h4>";
  }
?>

<article class="module width_full">
			<header><h3>Edit tour</h3></header>
				<div class="module_content">
						<fieldset>
							<label>Upload small image</label>
							  <form action="/admin/tour/upload" method="POST" id="uploadform">
							   <input type="file" name="file"/>
							   <input type="submit" name="btnUpload" value="Upload"/><br/><br/>
							   
							   <div id="onsuccessmsg" style="padding:15px;">
							   		<image src="<?php echo $this->tour->image_small;?>" />
							   </div>
							  </form>
						</fieldset>
						<fieldset>
							<label>Upload main image</label>
							  <form action="/admin/tour/upload2" method="POST" id="uploadform2">
							   <input type="file" name="file"/>
							   <input type="submit" name="btnUpload" value="Upload"/><br/><br/>
							   
							   <div id="onsuccessmsg2" style="padding:15px;">
							   		<image src="<?php echo $this->tour->image;?>" />
							   </div>
							  </form>
						</fieldset>
						<form name="form_add" method="POST" action="/admin/tour/edit" onSubmit="document.form_add.editor_contents.value  = $('#editor #edit .froala-element').html()">
							<input  type="hidden" name="id" id="id" value="<?php echo $this->tour->tour_type_id;?>" />
							<input  type="hidden" name="img_uploaded" id="img_uploaded" value="<?php echo $this->tour->image_small;?>" />
							<input  type="hidden" name="img_uploaded2" id="img_uploaded2" value="<?php echo $this->tour->image;?>" />	
							<input  type="hidden" name="tour_type_parent_id" id="tour_type_parent_id" value="<?php echo $this->sub_tour_type->parent_id;?>" />
							<fieldset>
								<label>Name(*)</label>
								<input type="text" name="name" value="<?php echo $this->sub_tour_type->name;?>">
							</fieldset>
							<fieldset>
								<label>Short description(*)</label>
								<textarea name="short_desc" id="short_desc" rows="4" cols="10"><?php echo $this->tour->short_desc;?></textarea>
							</fieldset>											
							<fieldset>
								<label>Tour Code</label>
								<input type="text" name="code" value="<?php echo $this->tour->code;?>">
							</fieldset>
							<fieldset>
								<label>Duration</label>
								<input type="text" name="duration" value="<?php echo $this->tour->duration;?>">
							</fieldset>
							<fieldset>
								<label>Price</label>
								<input type="text" name="price" value="<?php echo $this->tour->price;?>">
							</fieldset>
							<fieldset>
								<p>
									<label>Hot Tour</label>
									<input type="hidden" name="is_hot" value="0" />
									<input type="checkbox" name="is_hot" value="1"  <?php if($this->tour->is_hot == 1){ echo 'checked';};?>  >
								</p>
							</fieldset>
							<fieldset>
								<label>Details</label>
								<textarea id="editor_contents" name="editor_contents" style="display:none;"></textarea>
								<!-- -->
								<section id="editor">
								  <div id='edit' style="margin-top: 30px;">
									 <?php echo $this->tour->details; ?>
								  </div>
							    </section>

								<!-- -->
							</fieldset>
							<div class="clear"></div>
							<footer>
								<div class="submit_link">
									<input type="submit" name="btnSubmit" class="alt_btn" value="Update">
								</div>
							</footer>
						</form>
						
				</div>
		
		</article>
