<article class="module width_full">

		<form name="form_add" method="GET" action="/admin/product/index">						
			<table style="margin:10px 5px 20px 10px">
				<tr>
					<td><label>Loại sản phẩm(*)</label></td>
					<td>
						<select name="product_type_id" id="product_type_id" style="width: 200px;">
						<option value="0">--------------------------------------</option>
						<?php foreach ($this->product_type as $pt){
							if($pt->id == $this->product_type_id ){
								echo "<option selected='selected' value = '".$pt->id."'>".$pt->name."</option>";
							}else {
								echo '<option value="'.$pt->id.'">'.$pt->name.'</option>';			
							}
						}?>
					</select>	
					</td>
					<td>Loại con sản phẩm</td>
					<td>
						<select name="sub_product_type_id" id="sub_product_type_id" style="width: 200px;">
					    <?php 
					     if($this->product_type_id > 0){
					     	foreach ($this->sub_product_type as $spt){
				     			if($spt->id == $this->sub_product_type_id ){
				     				echo "<option selected='selected' value = '".$spt->id."'>".$spt->name."</option>";
				     			}else {
				     				echo '<option value="'.$spt->id.'">'.$spt->name.'</option>';
				     			}	
					     	}					     						     							    
					     }
					    ?>
					
						</select>
					</td>
					<td><input type="submit" class="alt_btn" value="Tìm" style="float:left;"></td>
					
				</tr>
			</table>	
													
		</form>
		<header><h3 class="tabs_involved">List tours</h3>
		<ul class="tabs">
   			<li class="active"><a href="/admin/product/add">Add new</a></li>
		</ul>
		</header>
		<div class="tab_container">
			<div class="tab_content" id="tab1" style="display: block;">
			<table cellspacing="0" class="tablesorter"> 
			<thead> 
				<tr> 
   					<th class="header">STT</th> 
    				<th class="header">Ảnh</th> 
    				<th class="header">Tên</th> 
    				<th class="header"></th> 
				</tr> 
			</thead> 
			<tbody> 
			   <?php $i=0; foreach ($this->products as $product) {
				       // Zend_Debug::dump($product);die;
									
				?>
				<tr> 
   					<td><?php echo ++$i;?></td> 
    				<td><image src="<?php echo $product['IMAGE_MAIN'];?>" style="width:30%;"/></td> 
    				<td><?php echo $product['NAME'];?></td> 
    				<td>
						<a href="/admin/product/edit/id/<?php echo $product['ID'];?>"><image src="/images/edit.png" alt="Sửa" style="padding-right:30px;"/></a>
						<a href="/admin/product/delete/id/<?php echo $product['ID'];?>"  onclick="return confirm('Bạn có chắc chắn muốn xóa?')"><image src="/images/delete.png" alt="Xóa" /></a>
					</td> 
				</tr> 
				
				<?php }	?>
				  
			</tbody> 
			</table>
			</div><!-- end of #tab1 -->
			
			
		
		</article>