<style>
.search {
    margin: 15px;
}
input {
    border-radius: 5px;
    border: 1px solid #BBBBBB;
    height: 20px;
    color: #666666;
}
.btn-primary {

}
</style>
<article class="module width_full">

		<form name="form_add" method="GET" action="/admin/tour/index" class="search">						
			<input type="text" name="keyword" id="keyword" value="<?php echo $this->keyword;?>"/>
			<input type="submit" value="Search" class="btn-primary"/>									
		</form>
		<header><h3 class="tabs_involved">List tours</h3>
		<ul class="tabs">
   			<li class="active"><a href="/admin/product/add">Add new</a></li>
		</ul>
		</header>
		<div class="tab_container">
			<div class="tab_content" id="tab1" style="display: block;">
			<table cellspacing="0" class="tablesorter"> 
			<thead> 
				<tr> 
   					<th class="header">No</th> 
   					<th class="header">Tour Type</th>
    				<th class="header">Name</th> 
    				<th class="header">Code</th>
    				<th class="header">Hot</th>
    				<th class="header">Short Description</th> 
    				<th class="header"></th> 
				</tr> 
			</thead> 
			<tbody> 
			   <?php $i=0; foreach ($this->tour as $tour) {
				       // Zend_Debug::dump($product);die;
									
				?>
				<tr> 
   					<td><?php echo ++$i;?></td> 
   					<td><?php echo $tour->parent_name;?></td>
    				<td><?php echo $tour->name;?></td> 
    				<td><?php echo $tour->code;?></td>
    				<td><?php if($tour->is_hot) echo 'Yes'; else echo 'No';?></td>
    				<td style="max-width: 600px"><?php echo $tour->short_desc;?></td>  
    				<td>
						<a href="/admin/tour/edit/id/<?php echo $tour->tour_type_id;?>"><image src="/images/edit.png" alt="Edit" style="padding-right:30px;"/></a>
						<a href="/admin/tour/delete/id/<?php echo $tour->tour_type_id;?>"  onclick="return confirm('Are you sure you delete this tour?')"><image src="/images/delete.png" alt="Delete" /></a>
					</td> 
				</tr> 
				
				<?php }	?>
				  
			</tbody> 
			</table>
			</div><!-- end of #tab1 -->
			
			
		
		</article>