<!DOCTYPE html>
<!-- saved from url=(0045)http://medialoot.com/preview/admin-template/# -->
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>Vietnam Visa Tour Administration</title>
        <link href="/images/favicon.png" rel="shortcut icon" type="image/vnd.microsoft.icon">
		<script src="//code.jquery.com/jquery-latest.min.js"></script>
		<script src="http://malsup.github.io/jquery.form.js"></script>
        <link rel="stylesheet" href="/css/admin_layout.css" type="text/css" media="screen">
        <!--[if lt IE 9]>
        <link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen" />
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif] -->
		
        <!-- <script src="/js/jquery-1.5.2.min.js" type="text/javascript"></script> -->
        <script src="/js/hideshow.js" type="text/javascript"></script>
        <script src="/js/jquery.tablesorter.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="/js/jquery.equalHeight.js"></script>
		<!-- froala_editor -->
		<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="/css/froala_editor.min.css" rel="stylesheet" type="text/css">
		<link href="/css/froala_reset.min.css" rel="stylesheet" type="text/css">
		
		<!-- <script src="/js/libs/jquery-1.10.2.min.js"></script> -->
		<script src="/js/libs/beautify/beautify-html.js"></script>
		<script src="/js/froala_editor.min.js"></script>
		<!--[if lt IE 9]>
			<script src="../js/froala_editor_ie8.min.js"></script>
		<![endif]-->
		<script src="/js/froala_editor.min.js"></script>
		<script src="/js/plugins/tables.min.js"></script>
		<script src="/js/plugins/colors.min.js"></script>
		<script src="/js/plugins/fonts/fonts.min.js"></script>
		<script src="/js/plugins/fonts/font_family.min.js"></script>
		<script src="/js/plugins/fonts/font_size.min.js"></script>
		<script src="/js/plugins/block_styles.min.js"></script>
		<script src="/js/plugins/video.min.js"></script>

		<script>
			$(function(){
				   $('#edit').editable({					
					inlineMode: false,
					// Set the image upload URL.
					imageUploadURL: '/admin/product/editor',

					imageUploadParams: {id: "my_editor"}
				});	
			});
		</script>
		
		<script type="text/javascript">
			$(document).ready(function(){
				  $('#product_type_id').change(function () {
				       //console.log( $(this).val());
					  $parent_id =  $(this).val();
		
		
					  $.ajax({
						  type: "POST",
						  url: "/admin/product/get-sub-product-type",
						  data: { parent_id: $parent_id },
						  success: function(response,status)
						  {   
							 // console.log(response);    
							  $html = "<option value='0'>--------------------------------------</option>";
		
							  $.each(JSON.parse(response), function(idx, obj) {
									//console.log(obj.name);
									 $html+="<option value='"+obj.id+"'>"+obj.name+"</option>"
								});
								
							  $("#sub_product_type_id").html($html);
						  }
						});							    
				   });
				  $('#tour_type_id').change(function () {
				       //console.log( $(this).val());
				       // admin/tour/menu
				      $form = $(this).parent();
				      if($form.attr('id') == 'form_search'){
						$form.submit();
						return;
					  }
					  $parent_id =  $(this).val();
		
		
					  $.ajax({
						  type: "POST",
						  url: "/admin/tour/get-sub-tour-type",
						  data: { parent_id: $parent_id },
						  success: function(response,status)
						  {   
							 // console.log(response);    
							  $html = "<option value='0' selected disabled>Please select</option>";
		
							  $.each(JSON.parse(response), function(idx, obj) {
									//console.log(obj.name);
									 $html+="<option value='"+obj.id+"'>"+obj.name+"</option>"
								});
							  // console.log($html);    
							  $("#sub_tour_type_id").html($html);
						  }
						});							    
				   });
				  //selection box
				  $('#price_type').change(function () {
				       //console.log( $(this).val());
				       // admin/tour/menu
				      
					$price_type =  $(this).val();
					$div = "price_type_" + $price_type;
					//alert($price_type );
					//hide 
					$("#price_type_1").hide();
					$("#price_type_2").hide();
					$("#price_type_3").hide();
					
					$("#"+$div).show();
					switch ($price_type) {
    					case 1:
    						//show group/private tour
    						break;
    					case 2:
    						//on land 2*, 3* tour
    						break;
    					case 3:
    						//on cruise
    						break;
    					default:
    						break;
					};					   
				});
					
			    $( "#add_addtional_price_type_2" ).button().on( "click", function(event) {
			     	  event.preventDefault();
			     	  //console.log($('#price_type_2 table tbody').html());
			     	  var no_tag= ($('input[name*="additional_price_text[]"').length);
			     	  if(no_tag >=3){
                         alert('Allow up to 3 addtional prices');
					  } else {
				     	  $add_price_html = '<tr>' +
                    	 						"<td><input type='text' name='additional_price_text[]' class='star_hotel'></td>" +
                       							"<td><input type='number' name='additional_price[]'></td>"+
                         					'</tr>';
                          $('#price_type_2 table tbody').append($add_price_html);   
					  }
			    });

				//validate data before submitting tour data				
			    $( "#btnSumitTour").button().on( "click", function() {
			     	  //console.log($('#price_type_2 table tbody').html());
			     	  //alert('OK');
			     	 var type = $("#price_type").val();
			     	 if(type == 1){

					    event.preventDefault();
					    
			     		var from_values = [];
			     		var to_values = [];
			     		$("input[name='from_pax_type_1_group[]']").each(function() {
			     			from_values.push($(this).val().trim());			     		    
			     		});
			     		$("input[name='from_pax_type_1_private[]']").each(function() {
			     			from_values.push($(this).val().trim());			     		    
			     		});
			     		$("input[name='to_pax_type_1_group[]'").each(function() {
			     			to_values.push($(this).val().trim());			     		    
			     		});
			     		$("input[name='to_pax_type_1_private[]'").each(function() {
			     			to_values.push($(this).val().trim());			     		    
			     		});

						//validate number left < right < next left
			     		var msg = null;
			     		for(i=0; i< from_values.length; i++){
				     		if(parseInt(from_values[i]) <= 0){
				     			msg = "Invalid 'From Pax' = 0";
			     				break;
					     	}
				     		if(to_values[i].length != 0){
				     			if(parseInt(to_values[i]) <= parseInt(from_values[i])){
				     				msg = "'To Pax' value must greater than 'From Pax' value";
				     				break;							
						     	}
						    }
							
						    if(i < 2  && i < from_values.length - 1 && to_values[i].length != 0 && parseInt(to_values[i]) >= parseInt(from_values[i+1])){
							    //console.log(parseInt(to_values[i]) +'==' + parseInt(from_values[i+1]));
								msg = "'To Pax' value of next option must less than 'From Pax' of previous one";
								break;
							}

						    if(i >= 3  && i < from_values.length - 1 && to_values[i].length != 0 && parseInt(to_values[i]) >= parseInt(from_values[i+1])){
						    	//console.log(parseInt(to_values[i]) +'==' + parseInt(from_values[i+1]));
								msg = "'To Pax' value of next option must less than 'From Pax' of previous one";
								break;
							} 
				     	}
				     	
				     	if(msg == null){ //submit data
				     		$('#form_tour_detail').submit();				     		
					    } else {
					    	alert(msg);
						}

				     	
				     }
			    });
			});
				
		</script>
		<!-- end -->
        <script type="text/javascript">
            $(document).ready(function() 
               	{ 
                 	  $(".tablesorter").tablesorter(); 
              	 } 
            );
            $(document).ready(function() {
            
            //When page loads...
            $(".tab_content").hide(); //Hide all content
            $("ul.tabs li:first").addClass("active").show(); //Activate first tab
            $(".tab_content:first").show(); //Show first tab content
            
            //On Click Event
            $("ul.tabs li").click(function() {
            
            	$("ul.tabs li").removeClass("active"); //Remove any "active" class
            	$(this).addClass("active"); //Add "active" class to selected tab
            	$(".tab_content").hide(); //Hide all tab content
            
            	var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
            	$(activeTab).fadeIn(); //Fade in the active ID content
            	return false;
            });
            
            });
               
        </script>
        <script type="text/javascript">
            $(function(){
                $('.column').equalHeight();
            });
        </script>
		<script>
			$(document).ready(function(){
			 function onsuccess(response,status){
			    $("#onsuccessmsg").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
		        //console.log(response);
			   }
			 $("#uploadform").on('submit',function(){
			  var options={
			   url     : $(this).attr("action"),
			   success : onsuccess
			  };
			  $(this).ajaxSubmit(options);
			 return false;
			 });

			 function onsuccess1(response,status){
				    $("#onsuccessmsg1").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform1").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess1
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 });
				 
			 function onsuccess2(response,status){
				    $("#onsuccessmsg2").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform2").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess2
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 });

				 $("#uploadImages").on('submit',function(){
					  var options={
					   url     : $(this).attr("action"),
					   success : onsuccessImages
					  };
					  $(this).ajaxSubmit(options);
					 return false;
				});
				 function onsuccessImages(response,status){		   

				        response = JSON.parse(response);
				        console.log(response.files);
				        if(response.errors.length > 0){
				        	$("#onerrorimgs").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">Error file:'+response.errors+'</div>');				        	
						} else {
							var html =$("#onsuccessmsgimgs").html();
							//console.log($("#img_uploaded_images").val());
							var iniVal = $("#img_uploaded_images").val();
							var val = [];
							if(iniVal.trim().length > 0){
								try{ //add case
								  val = JSON.parse($("#img_uploaded_images").val());
								} catch (e) { //edit case
								  val = $("#img_uploaded_images").val().split(',');
								}
							}
							for($i = 0; $i < response.files.length; $i++){
								html += '<div id="msg" style="border:5px solid #CCC;padding:15px;"><img style="margin-left:10px;" src="'+response.files[$i]+'"><button style="margin-left:10px;" class="delete_img" data-src="'+response.files[$i]+'">Delete</button></div>'								
								val.push(response.files[$i]);
							}
							//console.log(html);
							$("#onsuccessmsgimgs").html(html);
							
							$("#img_uploaded_images").val(JSON.stringify(val));
						}
					   }
				 $(document).on("click", ".delete_img", function(e) { //user click on delete image button
				        e.preventDefault();
				        $file = $(this).attr('data-src');
				        $(this).parent().remove();
				        //update data in hidden field
				        var iniVal = $("#img_uploaded_images").val();
				        if(iniVal.trim().length > 0){
					        try{ //add case
				        		iniVal = JSON.parse($("#img_uploaded_images").val());
					        } catch (e) { //edit case
					        	iniVal = $("#img_uploaded_images").val().split(',');
							}
				        	iniVal.splice($.inArray($file, iniVal),1);
				        	$("#img_uploaded_images").val(JSON.stringify(iniVal));				        	
					    }
				        //delete image on server
						$.ajax({
    					  type: "POST",
    					  url: "/admin/tour/delete-file",
    					  data: { delete_file: $file },
    					  success: function(response,status)
    					  {   
    						 console.log(response);
    					  }
						});	
				    })
				   
			 function onsuccess3(response,status){
				    $("#onsuccessmsg3").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform3").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess3
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 });	
			 function onsuccess4(response,status){
				    $("#onsuccessmsg4").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform4").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess4
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 });

				 $(document).on("click", ".update_normal_nationality", function(e) { //user click on delete image button
				        e.preventDefault();
						var $row = $(this).closest("tr");    // selected the row
				        var conf = confirm('Are you sure you want to update prices for ' + $row.find(".nationality_name").val());
						if(conf){
							  var $nationality_id = $row.find(".nationality_id").val();
							  var $1MSE = $row.find(".1MSE");					 
							  var $1MME = $row.find(".1MME");
							  var $3MSE = $row.find(".3MSE");
							  var $3MME = $row.find(".3MME");
							  var $6MME = $row.find(".6MME");
							  var $1YME = $row.find(".1YME");
							  var $U15min = $row.find(".U15min");
							  var $U30min = $row.find(".U30min");
							  var $U2hour = $row.find(".U2hour");
							  var $U4hour = $row.find(".U4hour");
							  var $U8hour = $row.find(".U8hour");
							  var $U1Day = $row.find(".U1Day");
							  var $UHoliday = $row.find(".UHoliday");

							  //warning input negative price
							  if($1MSE.val() < 0 || $1MME.val() < 0 || $3MSE.val() < 0 || $6MME.val() < 0 || $1YME.val() < 0 
									  || $U15min.val() < 0 || $U30min.val() < 0 || $U2hour.val() < 0 || $U4hour.val() < 0 || $U8hour.val()< 0 
									  || $U1Day.val() < 0 || $UHoliday.val() < 0){
								alert('Wrong input data , number is negative');
								return;
							  }
							  
                              var data = {};
                              data.nationality_id = $row.find(".nationality_id").val();
                              data.visa_type = [
                            	  {'id': $1MSE.attr('id'), 'price': $1MSE.val()},
                            	  {'id': $1MME.attr('id'), 'price': $1MME.val()},
                            	  {'id': $3MSE.attr('id'), 'price': $3MSE.val()},
                            	  {'id': $3MME.attr('id'), 'price': $3MME.val()},
                            	  {'id': $6MME.attr('id'), 'price': $6MME.val()},
                            	  {'id': $1YME.attr('id'), 'price': $1YME.val()},
                              ];
                              data.processing_time_type = [
                            	  {'id': $U15min.attr('id'), 'price': $U15min.val()},
                            	  {'id': $U30min.attr('id'), 'price': $U30min.val()},
                            	  {'id': $U2hour.attr('id'), 'price': $U2hour.val()},
                            	  {'id': $U4hour.attr('id'), 'price': $U4hour.val()},
                            	  {'id': $U8hour.attr('id'), 'price': $U8hour.val()},
                            	  {'id': $U1Day.attr('id'), 'price': $U1Day.val()},
                            	  {'id': $UHoliday.attr('id'), 'price': $UHoliday.val()},
                              ];
						        //delete image on server
								$.ajax({
		 					  type: "POST",
		 					  url: "/admin/visa/update-price",
		 					  data: { 'data': JSON.stringify(data)},
		 					  success: function(response,status)
		 					  {   
		 						 alert(response);
		 					  }
								});	
						}
				        
				    }) 	
			});
	</script>			
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="http://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script>
	$(document).ready(function(){
		
		});
  $( function() {
    var dialog, form,
      
      name = $( "#name" ),
      allFields = $( [] ).add( name ),
      tips = $( ".validateTips" );
 
    function updateTips( t ) {
      tips
        .text( t )
        .addClass( "ui-state-highlight" );
      setTimeout(function() {
        tips.removeClass( "ui-state-highlight", 1500 );
      }, 500 );
    }
 
    function checkLength( o, n, min, max ) {
      if ( o.val().length > max || o.val().length < min ) {
        o.addClass( "ui-state-error" );
        updateTips( "Length of " + n + " must be between " +
          min + " and " + max + "." );
        return false;
      } else {
        return true;
      }
    }
 
    function checkRegexp( o, regexp, n ) {
      if ( !( regexp.test( o.val() ) ) ) {
        o.addClass( "ui-state-error" );
        updateTips( n );
        return false;
      } else {
        return true;
      }
    }
 
    function addTourType() {
      var valid = true;
      allFields.removeClass( "ui-state-error" );
 
      valid = valid && checkLength( name, "name", 3, 50 );
 
      if ( valid ) {
		  $parent_id =  $("#tour_type_id").val();						
		  $.ajax({
			  type: "POST",
			  url: "/admin/tour/save-sub-tour-type",
			  data: { parent_id: $parent_id, name: name.val() },
			  success: function(response,status)
			  { 
				 location.reload();
			  }
			});
	      dialog.dialog( "close" );
      }
      return valid;
    }

    function editTourType() {
        var valid = true;
        allFields.removeClass( "ui-state-error" );
     	name = $( "#edit-dialog-form" ).find("#name");
     	//alert(name);
        valid = valid && checkLength( name, "name", 3, 50 );
   
        if ( valid ) {
  		  $id =  $( "#edit-dialog-form" ).find("#id").val();
  		  //alert($id+"--"+name.val());  		  		
  		  $.ajax({
  			  type: "POST",
  			  url: "/admin/tour/save-sub-tour-type",
  			  data: { id: $id, name: name.val() },
  			  success: function(response,status)
  			  { 
  				 location.reload();
  			  }
  			});
  	      dialog.dialog( "close" );
        }
        return valid;
      }
 
    dialog = $( "#dialog-form" ).dialog({
      autoOpen: false,
      height: 250,
      width: 350,
      modal: true,
      buttons: {
        "Create": addTourType,
        Cancel: function() {
          dialog.dialog( "close" );
        }
      },
      close: function() {
        form[ 0 ].reset();
        allFields.removeClass( "ui-state-error" );
      }
    });

    editDialog = $( "#edit-dialog-form" ).dialog({
        autoOpen: false,
        height: 250,
        width: 350,
        modal: true,
        buttons: {
          "Create": editTourType,
          Cancel: function() {
        	  editDialog.dialog( "close" );
          }
        },
        close: function() {
          form[ 0 ].reset();
          allFields.removeClass( "ui-state-error" );
        }
      });
 
    form = dialog.find( "form" ).on( "submit", function( event ) {
      event.preventDefault();
      addTourType();
    });
 
    $( "#add-tour-type" ).button().on( "click", function() {
   	  event.preventDefault();
      dialog.dialog( "open" );
    });
    $( ".edit_tour_type_name" ).button().on( "click", function() {
     	event.preventDefault();
     	var id = $(this).data("tour-type-id");
     	var name = $(this).data("tour-type-name");
     	//alert(name);
     	$( "#edit-dialog-form" ).find("#id").val(id);
     	$( "#edit-dialog-form" ).find("#name").val(name);
     	editDialog.dialog( "open" );
      });

    $( ".detete_tour_type_name" ).button().on( "click", function() {
     	event.preventDefault();
     	var id = $(this).data("tour-type-id");
     	var con = confirm('Are you sure you delete this tour?')
     	if(con == true){
  		  $.ajax({
			  type: "POST",
			  url: "/admin/tour/delete-sub-tour-type",
			  data: { id: id },
			  success: function(response,status)
			  { 
				 if(response.length > 0){
					 alert('Cannot delete this tour type because there are some tours linked to it');
			     } else {
			    	 location.reload();
				 }
				 //location.reload();
			  }
			});
        }
      });
    
  } );
  </script>

    </head>
    <body>
        <header id="header">
            <hgroup>
                <h1 class="site_title"><a href="/admin">Visa Tours Admin</a></h1>
                <h2 class="section_title">Dashboard</h2>
            </hgroup>
        </header>
        <?php  $auth = Zend_Auth::getInstance();
        	   $identity = $auth->getIdentity();
        ;?>
        <section id="secondary_bar">
            <div class="user">
                <p><?php echo $identity->USER_NAME;?>&nbsp;&nbsp;&nbsp; <a href="/admin/user/change-pass">Change password</a>  &nbsp;&nbsp;&nbsp;  (<a href="/admin/auth/logout">Log out</a>)</p>
                <p></p>
            </div>
            <div class="breadcrumbs_container">
                <article class="breadcrumbs">
                    <a href="/admin">Website Admin</a> 
                    <div class="breadcrumb_divider"></div>
                    <a class="current">Dashboard</a>
                </article>
            </div>
        </section>
        <aside id="sidebar" class="column" style="height: 1710px;">
        	<?php if($identity->ROLE == 0 || $identity->ROLE == 1){?>
	            <h3 class="toggleLink">Tour</h3>
	            <ul class="toggle">
	            	<li class="icn_edit_article"><a href="/admin/tour/booking">Tour Booking</a></li>
	            	<li class="icn_edit_article"><a href="/admin/tour/index">Manage</a></li>
	                <li class="icn_new_article"><a href="/admin/tour/add">Add Tour</a></li>
	                <li class="icn_edit_article"><a href="/admin/tour/menu">Tour Menu</a></li>	                
	            </ul>
            <?php } ?>
            <?php if($identity->ROLE == 0 || $identity->ROLE == 1){?>
	            <h3 class="toggleLink">Visa</h3>
	            <ul class="toggle">
	            	<li class="icn_edit_article"><a href="/admin/visa/booking">Visa Booking</a></li>
	            	<li class="icn_edit_article"><a href="/admin/visa/normal">Normal Nationality (Tourirst Visa)</a></li>
	                <li class="icn_new_article"><a href="/admin/visa/difficult">Difficult Nationality (Tourirst Visa)</a></li>
	                <li class="icn_edit_article"><a href="/admin/visa/business">Business Visa</a></li>
	                <li class="icn_edit_article"><a href="/admin/visa/exemption">Vietnam Visa Exemption</a></li>	                
	            </ul>
            <?php } ?>
            <div style="display: none">
            <?php if($identity->ROLE == 0 || $identity->ROLE == 1){?>
	            <h3>Sản phẩm <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_new_article"><a href="/admin/product/add">Thêm mới</a></li>
	                <li class="icn_edit_article"><a href="/admin/product/index">Quản lý</a></li>
	                <li class="icn_categories" style="display:none"><a href="javascript:void(0);">Categories</a></li>
	            </ul>
            <?php } ?>
            <?php if($identity->ROLE == 0 || $identity->ROLE == 3){?>
	            <h3>Tin tức <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_new_article"><a href="/admin/news/add">Thêm mới</a></li>
	                <li class="icn_edit_article"><a href="/admin/news/index">Quản lý</a></li>
	            </ul>
            <?php }?>
            </div>
             <?php if($identity->ROLE == 0){?>
	            <h3>Slide images <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_edit_article"><a href="/admin/image/index">Config</a></li>
	            </ul>
            <?php }?>
            <?php if($identity->ROLE == 0 || $identity->ROLE == 2){?>
	             <h3 class="toggleLink">Setting</h3>
	            <ul class="toggle">
	            	<li class="icn_edit_article"><a href="/admin/index/contact">Contact</a></li>
	            	<li class="icn_edit_article"><a href="/admin/index/why-us">Why us</a></li>
	            	<li class="icn_edit_article"><a href="/admin/index/tour-term">Tour Term&Condition</a></li>
	            	<li class="icn_edit_article"><a href="/admin/index/visa-step">Visa Steps</a></li>
	            	<li class="icn_edit_article"><a href="/admin/index/visa-faq">Visa FAQ</a></li>
	            	<li class="icn_edit_article"><a href="/admin/index/visa-term">Visa Term&Condition</a></li>
	            </ul>
            <?php }?>
            <footer>
                <hr>
                <p><strong>Copyright©2018 Website Visa Tours Admin</strong></p>
            </footer>
        </aside>
        <section id="main" class="column" style="height: 1710px;">
            <?php echo $this->layout()->content; ?> 
            <div class="clear"></div>
            <div class="spacer"></div>
        </section>
    </body>
</html>