<!DOCTYPE html>
<!-- saved from url=(0045)http://medialoot.com/preview/admin-template/# -->
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>Vietnam Visa Tour Administration</title>
		<script src="//code.jquery.com/jquery-latest.min.js"></script>
		<script src="http://malsup.github.io/jquery.form.js"></script>
        <link rel="stylesheet" href="/css/admin_layout.css" type="text/css" media="screen">
        <!--[if lt IE 9]>
        <link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen" />
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif] -->
		
        <!-- <script src="/js/jquery-1.5.2.min.js" type="text/javascript"></script> -->
        <script src="/js/hideshow.js" type="text/javascript"></script>
        <script src="/js/jquery.tablesorter.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="/js/jquery.equalHeight.js"></script>
		<!-- froala_editor -->
		<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="/css/froala_editor.min.css" rel="stylesheet" type="text/css">
		<link href="/css/froala_reset.min.css" rel="stylesheet" type="text/css">
		
		<!-- <script src="/js/libs/jquery-1.10.2.min.js"></script> -->
		<script src="/js/libs/beautify/beautify-html.js"></script>
		<script src="/js/froala_editor.min.js"></script>
		<!--[if lt IE 9]>
			<script src="../js/froala_editor_ie8.min.js"></script>
		<![endif]-->
		<script src="/js/froala_editor.min.js"></script>
		<script src="/js/plugins/tables.min.js"></script>
		<script src="/js/plugins/colors.min.js"></script>
		<script src="/js/plugins/fonts/fonts.min.js"></script>
		<script src="/js/plugins/fonts/font_family.min.js"></script>
		<script src="/js/plugins/fonts/font_size.min.js"></script>
		<script src="/js/plugins/block_styles.min.js"></script>
		<script src="/js/plugins/video.min.js"></script>

		<script>
			$(function(){
				   $('#edit').editable({					
					inlineMode: false,
					// Set the image upload URL.
					imageUploadURL: '/admin/product/editor',

					imageUploadParams: {id: "my_editor"}
				});	
			});
		</script>
		
		<script type="text/javascript">
			$(document).ready(function(){
				  $('#product_type_id').change(function () {
				       //console.log( $(this).val());
					  $parent_id =  $(this).val();
		
		
					  $.ajax({
						  type: "POST",
						  url: "/admin/product/get-sub-product-type",
						  data: { parent_id: $parent_id },
						  success: function(response,status)
						  {   
							 // console.log(response);    
							  $html = "<option value='0'>--------------------------------------</option>";
		
							  $.each(JSON.parse(response), function(idx, obj) {
									//console.log(obj.name);
									 $html+="<option value='"+obj.id+"'>"+obj.name+"</option>"
								});
								
							  $("#sub_product_type_id").html($html);
						  }
						});							    
				   });
				  $('#tour_type_id').change(function () {
				       //console.log( $(this).val());
					  $parent_id =  $(this).val();
		
		
					  $.ajax({
						  type: "POST",
						  url: "/admin/tour/get-sub-tour-type",
						  data: { parent_id: $parent_id },
						  success: function(response,status)
						  {   
							 // console.log(response);    
							  $html = "<option value='0' selected disabled>Please select</option>";
		
							  $.each(JSON.parse(response), function(idx, obj) {
									//console.log(obj.name);
									 $html+="<option value='"+obj.id+"'>"+obj.name+"</option>"
								});
							  // console.log($html);    
							  $("#sub_tour_type_id").html($html);
						  }
						});							    
				   });  
			});
		</script>
		<!-- end -->
        <script type="text/javascript">
            $(document).ready(function() 
               	{ 
                 	  $(".tablesorter").tablesorter(); 
              	 } 
            );
            $(document).ready(function() {
            
            //When page loads...
            $(".tab_content").hide(); //Hide all content
            $("ul.tabs li:first").addClass("active").show(); //Activate first tab
            $(".tab_content:first").show(); //Show first tab content
            
            //On Click Event
            $("ul.tabs li").click(function() {
            
            	$("ul.tabs li").removeClass("active"); //Remove any "active" class
            	$(this).addClass("active"); //Add "active" class to selected tab
            	$(".tab_content").hide(); //Hide all tab content
            
            	var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
            	$(activeTab).fadeIn(); //Fade in the active ID content
            	return false;
            });
            
            });
               
        </script>
        <script type="text/javascript">
            $(function(){
                $('.column').equalHeight();
            });
        </script>
		<script>
			$(document).ready(function(){
			 function onsuccess(response,status){
			    $("#onsuccessmsg").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
		        //console.log(response);
			   }
			 $("#uploadform").on('submit',function(){
			  var options={
			   url     : $(this).attr("action"),
			   success : onsuccess
			  };
			  $(this).ajaxSubmit(options);
			 return false;
			 });

			 function onsuccess1(response,status){
				    $("#onsuccessmsg1").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform1").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess1
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 });
				 
			 function onsuccess2(response,status){
				    $("#onsuccessmsg2").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform2").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess2
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 });
			 function onsuccess3(response,status){
				    $("#onsuccessmsg3").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform3").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess3
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 });	
			 function onsuccess4(response,status){
				    $("#onsuccessmsg4").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform4").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess4
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 }); 
			});
	</script>
			
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="http://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>


    </head>
    <body>
        <header id="header">
            <hgroup>
                <h1 class="site_title"><a href="/admin">Visa Tours Admin</a></h1>
                <h2 class="section_title">Dashboard</h2>
            </hgroup>
        </header>
        <?php  $auth = Zend_Auth::getInstance();
        	   $identity = $auth->getIdentity();
        ;?>
        <section id="secondary_bar">
            <div class="user">
                <p><?php echo $identity->USER_NAME;?>&nbsp;&nbsp;&nbsp; <a href="/admin/user/change-pass">Đổi mật khẩu</a>  &nbsp;&nbsp;&nbsp;  (<a href="/admin/auth/logout">Thoát</a>)</p>
                <p></p>
            </div>
            <div class="breadcrumbs_container">
                <article class="breadcrumbs">
                    <a href="/admin">Website Admin</a> 
                    <div class="breadcrumb_divider"></div>
                    <a class="current">Dashboard</a>
                </article>
            </div>
        </section>
        <aside id="sidebar" class="column" style="height: 1710px;">
        	<?php if($identity->ROLE == 0 || $identity->ROLE == 1){?>
	            <h3 class="toggleLink">Tour</h3>
	            <ul class="toggle">
	            	<li class="icn_edit_article"><a href="/admin/tour/index">Manage</a></li>
	                <li class="icn_new_article"><a href="/admin/tour/add">Add</a></li>
	            </ul>
            <?php } ?>
            <?php if($identity->ROLE == 0 || $identity->ROLE == 2){?>
	            <h3>Đơn hàng <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_view_users"><a href="/admin/order/index">Quản lý</a></li>                
	            </ul>
            <?php }?>
            <?php if($identity->ROLE == 0 || $identity->ROLE == 1){?>
	            <h3>Sản phẩm <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_new_article"><a href="/admin/product/add">Thêm mới</a></li>
	                <li class="icn_edit_article"><a href="/admin/product/index">Quản lý</a></li>
	                <li class="icn_categories" style="display:none"><a href="javascript:void(0);">Categories</a></li>
	            </ul>
            <?php } ?>
            <?php if($identity->ROLE == 0 || $identity->ROLE == 3){?>
	            <h3>Tin tức <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_new_article"><a href="/admin/news/add">Thêm mới</a></li>
	                <li class="icn_edit_article"><a href="/admin/news/index">Quản lý</a></li>
	            </ul>
            <?php }?>
             <?php if($identity->ROLE == 0){?>
	            <h3>Ảnh <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_edit_article"><a href="/admin/image/index">Quản lý</a></li>
	            </ul>
            <?php }?>
            <footer>
                <hr>
                <p><strong>Copyright©2018 Website Visa Tours Admin</strong></p>
            </footer>
        </aside>
        <section id="main" class="column" style="height: 1710px;">
            <?php echo $this->layout()->content; ?> 
            <div class="clear"></div>
            <div class="spacer"></div>
        </section>
    </body>
</html>