<!DOCTYPE html>
<!-- saved from url=(0045)http://medialoot.com/preview/admin-template/# -->
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>Vietnam Visa Tour Administration</title>
		<script src="//code.jquery.com/jquery-latest.min.js"></script>
		<script src="http://malsup.github.io/jquery.form.js"></script>
        <link rel="stylesheet" href="/css/admin_layout.css" type="text/css" media="screen">
        <!--[if lt IE 9]>
        <link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen" />
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif] -->
		
        <!-- <script src="/js/jquery-1.5.2.min.js" type="text/javascript"></script> -->
        <script src="/js/hideshow.js" type="text/javascript"></script>
        <script src="/js/jquery.tablesorter.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="/js/jquery.equalHeight.js"></script>
		<!-- froala_editor -->
		<link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css">
		<link href="/css/froala_editor.min.css" rel="stylesheet" type="text/css">
		<link href="/css/froala_reset.min.css" rel="stylesheet" type="text/css">
		
		<!-- <script src="/js/libs/jquery-1.10.2.min.js"></script> -->
		<script src="/js/libs/beautify/beautify-html.js"></script>
		<script src="/js/froala_editor.min.js"></script>
		<!--[if lt IE 9]>
			<script src="../js/froala_editor_ie8.min.js"></script>
		<![endif]-->
		<script src="/js/froala_editor.min.js"></script>
		<script src="/js/plugins/tables.min.js"></script>
		<script src="/js/plugins/colors.min.js"></script>
		<script src="/js/plugins/fonts/fonts.min.js"></script>
		<script src="/js/plugins/fonts/font_family.min.js"></script>
		<script src="/js/plugins/fonts/font_size.min.js"></script>
		<script src="/js/plugins/block_styles.min.js"></script>
		<script src="/js/plugins/video.min.js"></script>

		<script>
			$(function(){
				   $('#edit').editable({					
					inlineMode: false,
					// Set the image upload URL.
					imageUploadURL: '/admin/product/editor',

					imageUploadParams: {id: "my_editor"}
				});	
			});
		</script>
		
		<script type="text/javascript">
			$(document).ready(function(){
				  $('#product_type_id').change(function () {
				       //console.log( $(this).val());
					  $parent_id =  $(this).val();
		
		
					  $.ajax({
						  type: "POST",
						  url: "/admin/product/get-sub-product-type",
						  data: { parent_id: $parent_id },
						  success: function(response,status)
						  {   
							 // console.log(response);    
							  $html = "<option value='0'>--------------------------------------</option>";
		
							  $.each(JSON.parse(response), function(idx, obj) {
									//console.log(obj.name);
									 $html+="<option value='"+obj.id+"'>"+obj.name+"</option>"
								});
								
							  $("#sub_product_type_id").html($html);
						  }
						});							    
				   });
				  $('#tour_type_id').change(function () {
				       //console.log( $(this).val());
				       // admin/tour/menu
				      $form = $(this).parent();
				      if($form.attr('id') == 'form_search'){
						$form.submit();
						return;
					  }
					  $parent_id =  $(this).val();
		
		
					  $.ajax({
						  type: "POST",
						  url: "/admin/tour/get-sub-tour-type",
						  data: { parent_id: $parent_id },
						  success: function(response,status)
						  {   
							 // console.log(response);    
							  $html = "<option value='0' selected disabled>Please select</option>";
		
							  $.each(JSON.parse(response), function(idx, obj) {
									//console.log(obj.name);
									 $html+="<option value='"+obj.id+"'>"+obj.name+"</option>"
								});
							  // console.log($html);    
							  $("#sub_tour_type_id").html($html);
						  }
						});							    
				   });  
			});
		</script>
		<!-- end -->
        <script type="text/javascript">
            $(document).ready(function() 
               	{ 
                 	  $(".tablesorter").tablesorter(); 
              	 } 
            );
            $(document).ready(function() {
            
            //When page loads...
            $(".tab_content").hide(); //Hide all content
            $("ul.tabs li:first").addClass("active").show(); //Activate first tab
            $(".tab_content:first").show(); //Show first tab content
            
            //On Click Event
            $("ul.tabs li").click(function() {
            
            	$("ul.tabs li").removeClass("active"); //Remove any "active" class
            	$(this).addClass("active"); //Add "active" class to selected tab
            	$(".tab_content").hide(); //Hide all tab content
            
            	var activeTab = $(this).find("a").attr("href"); //Find the href attribute value to identify the active tab + content
            	$(activeTab).fadeIn(); //Fade in the active ID content
            	return false;
            });
            
            });
               
        </script>
        <script type="text/javascript">
            $(function(){
                $('.column').equalHeight();
            });
        </script>
		<script>
			$(document).ready(function(){
			 function onsuccess(response,status){
			    $("#onsuccessmsg").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
		        //console.log(response);
			   }
			 $("#uploadform").on('submit',function(){
			  var options={
			   url     : $(this).attr("action"),
			   success : onsuccess
			  };
			  $(this).ajaxSubmit(options);
			 return false;
			 });

			 function onsuccess1(response,status){
				    $("#onsuccessmsg1").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform1").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess1
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 });
				 
			 function onsuccess2(response,status){
				    $("#onsuccessmsg2").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform2").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess2
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 });

				 $("#uploadImages").on('submit',function(){
					  var options={
					   url     : $(this).attr("action"),
					   success : onsuccessImages
					  };
					  $(this).ajaxSubmit(options);
					 return false;
				});
				 function onsuccessImages(response,status){		   

				        response = JSON.parse(response);
				        console.log(response.files);
				        if(response.errors.length > 0){
				        	$("#onerrorimgs").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">Error file:'+response.errors+'</div>');				        	
						} else {
							var html =$("#onsuccessmsgimgs").html();
							//console.log($("#img_uploaded_images").val());
							var iniVal = $("#img_uploaded_images").val();
							var val = [];
							if(iniVal.trim().length > 0){
								try{ //add case
								  val = JSON.parse($("#img_uploaded_images").val());
								} catch (e) { //edit case
								  val = $("#img_uploaded_images").val().split(',');
								}
							}
							for($i = 0; $i < response.files.length; $i++){
								html += '<div id="msg" style="border:5px solid #CCC;padding:15px;"><img style="margin-left:10px;" src="'+response.files[$i]+'"><button style="margin-left:10px;" class="delete_img" data-src="'+response.files[$i]+'">Delete</button></div>'								
								val.push(response.files[$i]);
							}
							//console.log(html);
							$("#onsuccessmsgimgs").html(html);
							
							$("#img_uploaded_images").val(JSON.stringify(val));
						}
					   }
				 $(document).on("click", ".delete_img", function(e) { //user click on delete image button
				        e.preventDefault();
				        $file = $(this).attr('data-src');
				        $(this).parent().remove();
				        //update data in hidden field
				        var iniVal = $("#img_uploaded_images").val();
				        if(iniVal.trim().length > 0){
					        try{ //add case
				        		iniVal = JSON.parse($("#img_uploaded_images").val());
					        } catch (e) { //edit case
					        	iniVal = $("#img_uploaded_images").val().split(',');
							}
				        	iniVal.splice($.inArray($file, iniVal),1);
				        	$("#img_uploaded_images").val(JSON.stringify(iniVal));				        	
					    }
				        //delete image on server
						$.ajax({
    					  type: "POST",
    					  url: "/admin/tour/delete-file",
    					  data: { delete_file: $file },
    					  success: function(response,status)
    					  {   
    						 console.log(response);
    					  }
						});	
				    })
				   
			 function onsuccess3(response,status){
				    $("#onsuccessmsg3").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform3").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess3
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 });	
			 function onsuccess4(response,status){
				    $("#onsuccessmsg4").html('<div id="msg" style="border:5px solid #CCC;padding:15px;">'+response+'</div>');
			        //console.log(response);
				   }
				 $("#uploadform4").on('submit',function(){
				  var options={
				   url     : $(this).attr("action"),
				   success : onsuccess4
				  };
				  $(this).ajaxSubmit(options);
				 return false;
				 }); 
			});
	</script>			
	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="http://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css" />
	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
	<script>
	$(document).ready(function(){
		
		});
  $( function() {
    var dialog, form,
      
      name = $( "#name" ),
      allFields = $( [] ).add( name ),
      tips = $( ".validateTips" );
 
    function updateTips( t ) {
      tips
        .text( t )
        .addClass( "ui-state-highlight" );
      setTimeout(function() {
        tips.removeClass( "ui-state-highlight", 1500 );
      }, 500 );
    }
 
    function checkLength( o, n, min, max ) {
      if ( o.val().length > max || o.val().length < min ) {
        o.addClass( "ui-state-error" );
        updateTips( "Length of " + n + " must be between " +
          min + " and " + max + "." );
        return false;
      } else {
        return true;
      }
    }
 
    function checkRegexp( o, regexp, n ) {
      if ( !( regexp.test( o.val() ) ) ) {
        o.addClass( "ui-state-error" );
        updateTips( n );
        return false;
      } else {
        return true;
      }
    }
 
    function addTourType() {
      var valid = true;
      allFields.removeClass( "ui-state-error" );
 
      valid = valid && checkLength( name, "name", 3, 50 );
 
      if ( valid ) {
		  $parent_id =  $("#tour_type_id").val();						
		  $.ajax({
			  type: "POST",
			  url: "/admin/tour/save-sub-tour-type",
			  data: { parent_id: $parent_id, name: name.val() },
			  success: function(response,status)
			  { 
				 location.reload();
			  }
			});
	      dialog.dialog( "close" );
      }
      return valid;
    }

    function editTourType() {
        var valid = true;
        allFields.removeClass( "ui-state-error" );
     	name = $( "#edit-dialog-form" ).find("#name");
     	//alert(name);
        valid = valid && checkLength( name, "name", 3, 50 );
   
        if ( valid ) {
  		  $id =  $( "#edit-dialog-form" ).find("#id").val();
  		  //alert($id+"--"+name.val());  		  		
  		  $.ajax({
  			  type: "POST",
  			  url: "/admin/tour/save-sub-tour-type",
  			  data: { id: $id, name: name.val() },
  			  success: function(response,status)
  			  { 
  				 location.reload();
  			  }
  			});
  	      dialog.dialog( "close" );
        }
        return valid;
      }
 
    dialog = $( "#dialog-form" ).dialog({
      autoOpen: false,
      height: 250,
      width: 350,
      modal: true,
      buttons: {
        "Create": addTourType,
        Cancel: function() {
          dialog.dialog( "close" );
        }
      },
      close: function() {
        form[ 0 ].reset();
        allFields.removeClass( "ui-state-error" );
      }
    });

    editDialog = $( "#edit-dialog-form" ).dialog({
        autoOpen: false,
        height: 250,
        width: 350,
        modal: true,
        buttons: {
          "Create": editTourType,
          Cancel: function() {
        	  editDialog.dialog( "close" );
          }
        },
        close: function() {
          form[ 0 ].reset();
          allFields.removeClass( "ui-state-error" );
        }
      });
 
    form = dialog.find( "form" ).on( "submit", function( event ) {
      event.preventDefault();
      addTourType();
    });
 
    $( "#add-tour-type" ).button().on( "click", function() {
   	  event.preventDefault();
      dialog.dialog( "open" );
    });
    $( ".edit_tour_type_name" ).button().on( "click", function() {
     	event.preventDefault();
     	var id = $(this).data("tour-type-id");
     	var name = $(this).data("tour-type-name");
     	//alert(name);
     	$( "#edit-dialog-form" ).find("#id").val(id);
     	$( "#edit-dialog-form" ).find("#name").val(name);
     	editDialog.dialog( "open" );
      });

    $( ".detete_tour_type_name" ).button().on( "click", function() {
     	event.preventDefault();
     	var id = $(this).data("tour-type-id");
     	var con = confirm('Are you sure you delete this tour?')
     	if(con == true){
  		  $.ajax({
			  type: "POST",
			  url: "/admin/tour/delete-sub-tour-type",
			  data: { id: id },
			  success: function(response,status)
			  { 
				 if(response.length > 0){
					 alert('Cannot delete this tour type because there are some tours linked to it');
			     } else {
			    	 location.reload();
				 }
				 //location.reload();
			  }
			});
        }
      });
    
  } );
  </script>

    </head>
    <body>
        <header id="header">
            <hgroup>
                <h1 class="site_title"><a href="/admin">Visa Tours Admin</a></h1>
                <h2 class="section_title">Dashboard</h2>
            </hgroup>
        </header>
        <?php  $auth = Zend_Auth::getInstance();
        	   $identity = $auth->getIdentity();
        ;?>
        <section id="secondary_bar">
            <div class="user">
                <p><?php echo $identity->USER_NAME;?>&nbsp;&nbsp;&nbsp; <a href="/admin/user/change-pass">Change password</a>  &nbsp;&nbsp;&nbsp;  (<a href="/admin/auth/logout">Log out</a>)</p>
                <p></p>
            </div>
            <div class="breadcrumbs_container">
                <article class="breadcrumbs">
                    <a href="/admin">Website Admin</a> 
                    <div class="breadcrumb_divider"></div>
                    <a class="current">Dashboard</a>
                </article>
            </div>
        </section>
        <aside id="sidebar" class="column" style="height: 1710px;">
        	<?php if($identity->ROLE == 0 || $identity->ROLE == 1){?>
	            <h3 class="toggleLink">Tour</h3>
	            <ul class="toggle">
	            	<li class="icn_edit_article"><a href="/admin/tour/index">Manage</a></li>
	                <li class="icn_new_article"><a href="/admin/tour/add">Add Tour</a></li>
	                <li class="icn_edit_article"><a href="/admin/tour/menu">Tour Menu</a></li>
	            </ul>
            <?php } ?>
            <div style="display: none">
            <?php if($identity->ROLE == 0 || $identity->ROLE == 2){?>
	            <h3>Đơn hàng <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_view_users"><a href="/admin/order/index">Quản lý</a></li>                
	            </ul>
            <?php }?>
            <?php if($identity->ROLE == 0 || $identity->ROLE == 1){?>
	            <h3>Sản phẩm <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_new_article"><a href="/admin/product/add">Thêm mới</a></li>
	                <li class="icn_edit_article"><a href="/admin/product/index">Quản lý</a></li>
	                <li class="icn_categories" style="display:none"><a href="javascript:void(0);">Categories</a></li>
	            </ul>
            <?php } ?>
            <?php if($identity->ROLE == 0 || $identity->ROLE == 3){?>
	            <h3>Tin tức <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_new_article"><a href="/admin/news/add">Thêm mới</a></li>
	                <li class="icn_edit_article"><a href="/admin/news/index">Quản lý</a></li>
	            </ul>
            <?php }?>
            </div>
             <?php if($identity->ROLE == 0){?>
	            <h3>Slide images <a href="javascript:void(0);" class="toggleLink">Hide</a></h3>
	            <ul class="toggle">
	                <li class="icn_edit_article"><a href="/admin/image/index">Config</a></li>
	            </ul>
            <?php }?>
            <footer>
                <hr>
                <p><strong>Copyright©2018 Website Visa Tours Admin</strong></p>
            </footer>
        </aside>
        <section id="main" class="column" style="height: 1710px;">
            <?php echo $this->layout()->content; ?> 
            <div class="clear"></div>
            <div class="spacer"></div>
        </section>
    </body>
</html>