<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
	<meta name="google-site-verification" content="90Dvd6HDbDiK1uCOaes4Zb4j1kN0z6zdvXPgFp2RoEI" />
	<title>Visa Tours - Vietnam Tour &amp; Travel Deals - Best Vietnam Vacation Packages for your Holiday. Checkout our massive ranges of Vietnam Discovery, Vietnam Adventures, Halong Bay Cruises, Vietnam Beach break, Vietnam Hotels, Vietnam Tour Packages 2019</title>
	<link rel="icon" href="/images/favicon.png" type="image/x-icon" />

	<link rel="stylesheet" href="/css/style.css" type="text/css" />
	<link rel="stylesheet" href="/css/ddlevelsmenu-base.css" type="text/css" />
	<link rel="stylesheet" href="/css/ddlevelsmenu-topbar.css" type="text/css" />
	<link type="text/css" href="/css/skitter.styles.css" media="all" rel="stylesheet" />
	<link rel="stylesheet" href="/css/jquery.jqzoom.css" type="text/css">
	<link rel="stylesheet" href="/css/SpryTabbedPanels.css" type="text/css">
	
	<script src="/js/jquery-1.6.js" type="text/javascript"></script>
	<script type="text/javascript" src="/js/ddsmoothmenu.js"></script>
	<script type="text/javascript" src="/js/ddlevelsmenu.js"></script>
	<script type="text/javascript" src="/js/jquery.skitter.min.js"></script>
	<script type="text/javascript" src="/js/animate-colors-min.js"></script>
	<script type="text/javascript" src="/js/jquery.easing.1.3.js"></script>
	<script type="text/javascript" src="/js/jquery.jqzoom-core.js"></script>
	<script type="text/javascript" src="/js/SpryTabbedPanels.js"></script>

	<meta name="description" content="Vietnam Tour &amp; Travel Deals - Best Vietnam Vacation Packages for your Holiday. Checkout our massive ranges of Vietnam Discovery, Vietnam Adventures, Halong Bay Cruises, Vietnam Beach break, Vietnam Hotels, Vietnam Tour Packages 2019">
	
	<meta name="keywords" content= "vietname visa, vietname tour, vietnam visatour, vietnamtours" />

	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="ROBOTS" content= "INDEX, FOLLOW" />
	<meta name="author" content= "hanaku.vn" />
	<meta name="distribution" content= "global" />
	<meta name="Copyright" content="hanaku.vn" />
	<meta name="Design" content="Thiet ke web - BK-WEB" />
	<link rel="icon" href="" type="image/x-icon" />

	<script type="text/javascript">
		$(document).ready(function() {
			$('.box_skitter_large').skitter({
				theme: 'clean',
				dots: true, 
				preview: true,
				numbers_align: 'center',
				enable_navigation_keys: true,
				interval: 2500
			});
		});
	</script>
	
	<style type="text/css">
			body{margin:0px;padding:0px;font-family:Arial;}
			a img,:link img,:visited img { border: none; }
			table { border-collapse: collapse; border-spacing: 0; }
			:focus { outline: none; }
			*{margin:0;padding:0;}
			p, blockquote, dd, dt{margin:0 0 8px 0;line-height:1.5em;}
			fieldset {padding:0px;padding-left:7px;padding-right:7px;padding-bottom:7px;}
			fieldset legend{margin-left:15px;padding-left:3px;padding-right:3px;color:#333;}
			dl dd{margin:0px;}
			dl dt{}
	
			.clearfix:after{clear:both;content:".";display:block;font-size:0;height:0;line-height:0;visibility:hidden;}
			.clearfix{display:block;zoom:1}
	
	
			ul#thumblist{display:block;}
			ul#thumblist li{float:left;margin-right:2px;list-style:none;}
			ul#thumblist li a{display:block;border:1px solid #CCC;}
			ul#thumblist li a.zoomThumbActive{
				border:1px solid red;
			}
	
			.jqzoom{
				text-decoration:none;
				float:left;
			}
		</style>
</head>

<body>
	<div id="toplogo-wr">
		<div id="toplogo">
			<table border="0" cellpadding="0" cellspacing="0" width="100%">
				<tr>
					<td align="left" valign="middle">
						<a class="logo-hanaku" href="/"><img src="/images/logo.png"></a>
					</td>
					<td align="right" valign="middle">
						<div id="topsearch-wr">
							<form method="post">
								<div style="float:left; padding-right:3px;">
									<input id="search_text" type="text"  name="" value="" placeholder="Nhập từ khóa tìm kiếm" class="box-text-search"></input>
								</div>
									<input id="search_key" style="cursor: pointer;" onclick="javascript:searchSubmit()" class="box-search-bt" value=""></input>
							</form>
						</div>
					</td>
				</tr>
			</table>
		</div>
	</div>
	
	<script type="text/javascript">
		function searchSubmit(){
			var input = document.getElementById("search_text");
			window.location = "/index/search?key=" + input.value;
		}
	</script>
	
	<div id="topmenu-wr">
		<div id="top-menu-wr">
			<div class="topmenu">
			<?php $i = 0; foreach ($this->menuTypes as $type) { if(is_null($type->parent_id)) { $i++;?>
				<div class="topmenu_text" id="ddtopmenubar<?php echo $i?>" style="padding-top:6px"><a rel="ddsubmenu<?php echo $i?>" href="/index/type?typeId=<?php echo $type->id?>" title="<?php echo $type->name?>"><?php echo $type->name?></a></div>
				<div class="topmenu_space"></div>
				<script type="text/javascript">
					ddlevelsmenu.setup("ddtopmenubar<?php echo $i?>", "topbar")
				</script>
				<ul id="ddsubmenu<?php echo $i?>" class="ddsubmenustyle">
				<?php foreach ($this->menuTypes as $t) { if($t->parent_id == $type->id) {?>
					<li style=""><a href="/index/subtype?stype=<?php echo $t->id?>"><?php echo $t->name?></a></li>
				<?php } }?>
				</ul>
			<?php } }?>

				<div class="topmenu_text" style="padding-top:6px"><a rel="ddsubmenu1" href="" title="Khuyến mại">Khuyến mại</a></div>
			</div>
		</div>
	</div>
			
    <?php echo $this->layout()->content ?>
	
	<div style="clear:both;">&nbsp;</div>
	<div id="site-info-wr">
		<div id="site-info">
			<div class="site-info-block">
				<div class="info-block-item info-block-head">Giới thiệu</div>
				<div class="info-block-item"><a href="" title="">Giới thiệu</a></div>
				<div class="info-block-item"><a href="" title="">Địa chỉ giao dịch</a></div>
			</div>
			<div class="site-info-block space-info">
				<div class="info-block-item info-block-head">Trợ giúp</div>
				<div class="info-block-item"><a href="" title="">Hướng dẫn mua hàng</a></div>
				<div class="info-block-item"><a href="" title="">Phương thức vận chuyển</a></div>
				<div class="info-block-item"><a href="" title="">Hình thức thanh toán</a></div>
			</div>
			<div class="site-info-block space-info">
				<div class="info-block-item info-block-head">Chính sách</div>
				<div class="info-block-item"><a href="" title="">Chính sách bảo hành</a></div>
				<div class="info-block-item"><a href="" title="">Chính sách đổi hàng</a></div>
			</div>
			<div class="site-info-block space-info">
				<div class="info-block-item info-block-head">Tin tức</div>
				<div class="info-block-item"><a href="" title="">Thông tin khuyến mại</a></div>
				<div class="info-block-item"><a href="" title="">Thông tin tuyển dụng</a></div>
			</div>

				<div id="footer-inner">
				<p style="font-family: Verdana,sans-serif; font-size: 11px; font-weight: bold; line-height: 18px">Hanaku Shop:</p>
				<p style="font-family: Verdana,sans-serif; font-size: 11px; line-height: 13px">Số 14, ngõ 9, Lương Định Của, Đống Đa, Hà Nội</p>
				<p style="font-family: Verdana,sans-serif; font-size: 11px; line-height: 13px">Phone: 04. 0123 4567 | Hotline: 098 123 4567</p>
				</div>

			<div style="clear:both;">&nbsp;</div>
		</div>
	</div>
	

</body>
</html>