<div id="left-cell">
		<div id="fb-box">
		<!-- 
			<iframe src="http://www.facebook.com/plugins/likebox.php?href=https%3A%2F%2Fwww.facebook.com%2Fhanaku.vn&amp;width=190&amp;height=290&amp;colorscheme=light&amp;show_faces=true&amp;header=true&amp;stream=false&amp;show_border=true" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:190px; height:290px;" allowTransparency="true"></iframe>
		-->
		</div>
		<div style="clear: both; height: 8px"></div>
		<div class="left_tab">
			<div class="left_tab_text">Loại sản phẩm</div>
		</div>
		<div class="leftmenu_box">
			<div class="leftmenu-item">
				<a href="">Giày</a>
			</div>
			<div class="leftmenu-item">
				<a href="">Ví da</a>
			</div>
			<div class="leftmenu-item">
				<a href="">Thắt lưng</a>
			</div>
			<div class="leftmenu-item">
				<a href="">Áo da</a>
			</div>
			<div class="leftmenu-item">
				<a href="">Cặp da</a>
			</div>
			<div class="leftmenu-item">
				<a href="">Phụ kiện đồ da</a>
			</div>
		</div>
		<div style="clear: both; height: 8px"></div>
		<div class="left_tab">
			<div class="left_tab_text">Khoảng giá</div>
		</div>
		<div class="leftmenu_box">
			<div class="leftmenu-item">
				<a href="">Dưới 200.000</a>
			</div>
			<div class="leftmenu-item">
				<a href="">200.000 - 500.000</a>
			</div>
			<div class="leftmenu-item">
				<a href="">500.000 - 1 triệu</a>
			</div>
			<div class="leftmenu-item">
				<a href="">1 triệu - 1,5 triệu</a>
			</div>
			<div class="leftmenu-item">
				<a href="">trên 1,5 triệu</a>
			</div>
		</div>
</div>