      <div id="menutop">
         <div style="z-index: 7000;" id="ctl00_HorizontalTopPrimary_mnMenu" class="RadMenu RadMenu_Top">
            <!-- 2012.1.215.40 -->
            <ul class="rmRootGroup rmHorizontal">
               <li class="rmItem rmFirst">
					<a href="/" class="rmLink rmRootLink  menu25" target="_self">
						 <span class="rmText">
							Home
							<div class="fix_left"></div>
							<div class="fix_right"></div>
						 </span>
					</a>
               </li>
               <li class="rmItem ">
					<a href="/index/intro" class="rmLink rmRootLink  menu7" target="_self">
						 <span class="rmText">
							Giới thiệu
							<div class="fix_left"></div>
							<div class="fix_right"></div>
						 </span>
					</a>
               </li>
               <li class="rmItem ">
                  <a href="javascript:void(0);" class="rmLink rmRootLink  menu2" target="_self">
                     <span class="rmText rmExpandDown">
                        Sản phẩm
                        <div class="fix_left"></div>
                        <div class="fix_right"></div>
                     </span>
                  </a>
                  <div class="rmSlide" >
                     <ul class="rmVertical rmGroup rmLevel1">
                        <li class="rmItem rmFirst"><a href="/index/product-details/product_id/32" class="rmLink" target="_self"><span class="rmText">CumirNano</span></a></li>
                        <li class="rmItem "><a href="/index/product-details/product_id/33" class="rmLink" target="_self"><span class="rmText">Enzym Gold 6+</span></a></li>
                        <li class="rmItem rmLast"><a href="/index/product-details/product_id/30" class="rmLink" target="_self"><span class="rmText">Neopapain</span></a></li>
                     </ul>
                  </div>
               </li>
			   <li class="rmItem ">
                  <a href="javascript:void(0);" class="rmLink rmRootLink  menu6" target="_self">
                     <span class="rmText rmExpandDown">
                         Tin sức khỏe
                        <div class="fix_left"></div>
                        <div class="fix_right"></div>
                     </span>
                  </a>
                  <div class="rmSlide" >
                     <ul class="rmVertical rmGroup rmLevel1">
                        <li class="rmItem rmFirst"><a href="/index/news/catId/1" class="rmLink" target="_self"><span class="rmText">Tin y dược</span></a></li>
                        <li class="rmItem "><a href="/index/news/catId/2" class="rmLink" target="_self"><span class="rmText">Y học cổ truyền</span></a></li>
                        <li class="rmItem rmLast"><a href="/index/news/catId/3" class="rmLink" target="_self"><span class="rmText">Mẹ & Bé</span></a></li>
                     </ul>
                  </div>
               </li>
               <li class="rmItem ">
                  <a href="/index/places" class="rmLink rmRootLink  menu288" target="_self">
                     <span class="rmText rmExpandDown">
                        Hệ thống phân phối
                        <div class="fix_left"></div>
                        <div class="fix_right"></div>
                     </span>
                  </a>
               </li>
               <li class="rmItem ">
                  <a href="/index/question" class="rmLink rmRootLink  menu134" target="_self">
                     <span class="rmText">
                        Tư vấn
                        <div class="fix_left"></div>
                        <div class="fix_right"></div>
                     </span>
                  </a>
               </li>
               <li class="rmItem rmLast">
                  <a href="/index/contact" class="rmLink rmRootLink  menu9" target="_self">
                     <span class="rmText">
                        Liên hệ
                        <div class="fix_left"></div>
                        <div class="fix_right"></div>
                     </span>
                  </a>
               </li>
            </ul>
            <input autocomplete="off" id="ctl00_HorizontalTopPrimary_mnMenu_ClientState" name="ctl00_HorizontalTopPrimary_mnMenu_ClientState" type="hidden">
         </div>
      </div>
	  
	  
<script type="text/javascript">
//<![CDATA[

theForm.oldSubmit = theForm.submit;
theForm.submit = WebForm_SaveScrollPositionSubmit;

theForm.oldOnSubmit = theForm.onsubmit;
theForm.onsubmit = WebForm_SaveScrollPositionOnSubmit;
Sys.Application.add_init(function() {
    $create(Telerik.Web.UI.RadMenu, {"_childListElementCssClass":null,"_skin":"Top",
									"clientStateFieldID":"ctl00_HorizontalTopPrimary_mnMenu_ClientState",
									"collapseAnimation":"{\"duration\":450}",
									"expandAnimation":"{\"duration\":450}",
									"itemData":[
										{"value":"25","navigateUrl":"/","target":"_self","cssClass":" menu25"},
										{"items":[
											{"value":"291","navigateUrl":"/vi/tai-sao-chon-cumargold.pl291.html","target":"_self"},
											{"value":"285","navigateUrl":"/vi/cumargold-vien-nang-mem.pl285.html","target":"_self"},
											{"value":"284","navigateUrl":"/vi/cumargold-dung-dich-uong.pl284.html","target":"_self"}
											],
											"value":"7","navigateUrl":"/vi/san-pham.pl7.html","target":"_self","cssClass":" menu7"
										}
										,{"items":[
											{"value":"286","navigateUrl":"/vi/nano-curcumin-la-gi.nl286.html","target":"_self"},
											{"value":"287","navigateUrl":"/vi/tac-dung-cua-nano-curcumin.nl287.html","target":"_self"},
											{"value":"295","navigateUrl":"/vi/qui-trinh-san-xuat-nano-curcumin.nl295.html","target":"_self"}
											],
											"value":"2","navigateUrl":"/vi/nano-curcumin.nl2.html","target":"_self","cssClass":" menu2"
										},
										{"items":[
											{"value":"2866","navigateUrl":"/vi/nano-curcumin-la-gi.nl286.html","target":"_self"},
											{"value":"2876","navigateUrl":"/vi/tac-dung-cua-nano-curcumin.nl287.html","target":"_self"},
											{"value":"2956","navigateUrl":"/vi/qui-trinh-san-xuat-nano-curcumin.nl295.html","target":"_self"}
											],
											"value":"6","navigateUrl":"/vi/khach-hang-trai-nghiem.nl6.html","target":"_self","cssClass":" menu6"
										},
										
										{"items":[
											{"value":"289","navigateUrl":"/vi/y-kien-chuyen-gia.nl289.html","target":"_self"},
											{"value":"290","navigateUrl":"/vi/nghien-cuu-khoa-hoc.nl290.html","target":"_self"}],
											"value":"288","navigateUrl":"/vi/y-kien-chuyen-gia-ve-nano-curcumin-tinh-nghe-nano.nl288.html","target":"_self","cssClass":" menu288"
										},
										{"value":"134","navigateUrl":"/vi/hoi-dap-chuyen-gia.sc134.html","target":"_self","cssClass":" menu134"},
										{"value":"222","navigateUrl":"/vi/tin-tuc.nl222.html","target":"_self","cssClass":" menu222"},
										{"value":"9","navigateUrl":"/vi/lien-he.c9.html","target":"_self","cssClass":" menu9"}],
										"webServiceSettings":"{\"path\":\"/WebService/MenuService.asmx\",\"method\":\"GetMenuCategories\"}"}
										, null, null, $get("ctl00_HorizontalTopPrimary_mnMenu"));
});
//]]>
</script>