<div id="right-cell">
				<div id="top-slider">
					<div class="box_skitter box_skitter_large">
						<ul>
							<li>
								<a href="#cut"><img src="/images/slider/S1.jpg" class="cut" /></a>
								<div class="label_text"><p>cut</p></div>
							</li>
							<li>
								<a href="#swapBlocks"><img src="/images/slider/S2.jpg" class="swapBlocks" /></a>
								<div class="label_text"><p>swapBlocks</p></div>
							</li>
							<li>
								<a href="#swapBarsBack"><img src="/images/slider/S3.jpg" class="swapBarsBack" /></a>
								<div class="label_text"><p>swapBarsBack</p></div>
							</li>
							<li>
								<a href="#swapBars"><img src="/images/slider/S4.jpg" class="swapBars" /></a>
								<div class="label_text"><p>swapBars</p></div>
							</li>
						</ul>
					</div>
				</div>
				
				<!-- loop -->
				<div style="clear:both; height: 10px"> &nbsp; </div>
				<div class="center_tab">
					<div class="center_tab_text" style="white-space: nowrap;">Sản phẩm hot</div>
					<div class="center_tab_text_right"><a  href="/pa47/hopruou.html?type=new" title="Sản phẩm mới">Xem tất cả</a> &raquo;</div>
				</div>
				<div style="clear:both; height: 10px"> &nbsp; </div>
				<div class="product_content_home">
					<div style="clear:both; height:15px;">&nbsp;</div>
					<div id="product_line">
						<div class="box01">
							<div class="product_img">
								<a href="/pb1212/ho-ruou-don/034a-co-bo-mo.html" title="G034A (4 phụ kiện)"><img title="G034A (4 phụ kiện)" alt="G034A (4 phụ kiện)" src="/images/products/001.jpg" width="180px" /></a>
								<!-- hien thi khi co giam gia-->
								<div class="product-discount">-20%</div>
							</div>
							<div class="product_factory">HM</div>
							<div class="product_title"><a href="/pb1212/ho-ruou-don/034a-co-bo-mo.html" title="G034A (4 phụ kiện)">G034A (4 phụ kiện)</a>
							</div>
							<div class="product_home_price" align="center">Giá: <span style="font-size: 12px; color: #888; text-decoration: line-through;">250.000</span></div>
							<div class="product_home_price" align="center">200.000</div>
						</div>
						<div class="box_space"></div>
						<div class="box01">
							<div class="product_img">
								<a href="/pb1188/ho-ruou-don/hop-ruou-027.html" title="G034 (4 phụ kiện)"><img title="G034 (4 phụ kiện)" alt="G034 (4 phụ kiện)" src="/images/products/002.jpg" width="180px" /></a>
								<div class="product-discount">-20%</div>
							</div>
							<div class="product_factory">HM</div>
							<div class="product_title"><a href="/pb1188/ho-ruou-don/hop-ruou-027.html" title="G034 (4 phụ kiện)">G034 (4 phụ kiện)</a>
							</div>
							<div class="product_home_price" align="center">Giá: 240.000</div>
							<div class="product_home_promotional" align="center"><span style="font-weight: bold; color: #CC0000;">Khuyến mại:</span> Tặng kèm 1 ví da nam cao cấp</div>
						</div>
						<div class="box_space"></div>
						<div class="box01">
							<div class="product_img">
								<a href="/pb1190/ho-ruou-don/hop-ruou-127-a.html" title="127A (Không phụ kiện)"><img title="127A (Không phụ kiện)" alt="127A (Không phụ kiện)" src="/images/products/003.jpg" width="180px" />
								</a>
							</div>
							<div class="product_factory">HM</div>
							<div class="product_title"><a href="/pb1190/ho-ruou-don/hop-ruou-127-a.html" title="127A (Không phụ kiện)">127A (Không phụ kiện)</a>
							</div>
							<div class="product_home_price" align="center">Giá: Liên hệ</div>
						</div>
						<div class="box_space"></div>
						<div class="box01">
							<div class="product_img">
								<a href="/pb1206/ho-ruou-don/hop-ruou-034-co-bo-mo.html" title="127 (3 phụ kiện)"><img title="127 (3 phụ kiện)" alt="127 (3 phụ kiện)" src="/images/products/004.jpg" width="180px" /></a>
							</div>
							<div class="product_factory">HM</div>
							<div class="product_title"><a href="/pb1206/ho-ruou-don/hop-ruou-034-co-bo-mo.html" title="127 (3 phụ kiện)">127 (3 phụ kiện)</a>
							</div>
							<div class="product_home_price" align="center">Giá: Liên hệ</div>
						</div>
					</div>
					<div style="clear:both;">&nbsp;</div><div style="clear:both; height: 10px"> &nbsp; </div>
				</div>
</div>
