

		<script type="text/javascript">
			$(document).ready(function(){		
				$(".addProductToCart").click(function() {
			  	  $product_id = $(this).attr('id');

			  	  $.ajax({
					  type: "POST",
					  url: "/cart/add-product-to-cart",
					  data: { product_id: $product_id },
					  success: function(response,status)
					  {   
						 //console.log(response);    	
						 window.location.href = "/cart/";					
					  }
					});	
				}); 
			});
		</script>
	<div id="mainbody-wr">
		<div id="mainbody">
			<div id="product-d-name">G034A (4 phụ kiện)</div>
			<div id="product-detail">
				<div class="product-d-right">
					<div class="p-detail-img-left">
						<script type="text/javascript">
							$(document).ready(function() {
								$('.jqzoom').jqzoom({
										zoomType: 'reverse',
										preloadImages: false,
										alwaysOn:false,
										zoomHeight: 400,
										zoomWidth: 448,
										imageOpacity: 0.8,
										lens: false
									});
								//$('.jqzoom').jqzoom();
							});
						</script>
						<div style="width: 100%; text-align: center; color: #444; font-family: Arial,Helvetica,sans-serif; font-size: 12px; font-weight: bold; margin: 5px 0px 5px 0px;">Di chuột vào ảnh để phóng to</div>
						<div class="clearfix" id="content" style="height:400px;width:330px;" >
							<div class="clearfix">
								<a href="<?php echo $this->product->image_main?>" class="jqzoom" rel='gal1'  title="zoom" > <!-- zoom image -->
									<img style="width: 308px; height: 247px; border: 1px solid #666" src="<?php echo $this->product->image_main?>"  title="" > <!-- ảnh đại diện -->
								</a>
							</div>
							<br/>
							<div class="clearfix" >
							<ul id="thumblist" class="clearfix" >
								<li><a class="zoomThumbActive" href='javascript:void(0);' rel="{gallery: 'gal1', smallimage: '<?php echo $this->product->image_main?>', largeimage: '<?php echo $this->product->image_main?>'}"><img class="product-d-image-list" src='<?php echo $this->product->image_main?>'></a></li>
								<li><a href='javascript:void(0);' rel="{gallery: 'gal1', smallimage: '<?php echo $this->product->image_second;?>',largeimage: '<?php echo $this->product->image_second;?>'}"><img class="product-d-image-list" src='<?php echo $this->product->image_second;?>'></a></li>
								<li><a  href='javascript:void(0);' rel="{gallery: 'gal1', smallimage: '<?php echo $this->product->image_third;?>',largeimage: '<?php echo $this->product->image_third;?>'}"><img class="product-d-image-list" src='<?php echo $this->product->image_third;?>'></a></li>
							</ul>
							</div>
						</div>
					</div>
					<div class="p-detail-info">
						<div class="detail-item">
							<div class="detail-title">Mã sản phẩm:</div>
							<div class="detail-value"><?php echo $this->product->code;?></div>
						</div>
						<div class="detail-item">
							<div class="detail-title">Màu sắc:</div>
							<div class="detail-value"><?php echo $this->product->color;?></div>
						</div>
						<div class="detail-item">
							<div class="detail-title">Chất liệu:</div>
							<div class="detail-value"><?php echo $this->product->material;?></div>
						</div>
						<div class="detail-item">
							<div class="detail-title">Xuất xứ:</div>
							<div class="detail-value"><?php echo $this->product->origin;?></div>
						</div>
						<div class="detail-item">
							<div class="detail-title proDetail_price">Giá:</div>
							<div class="detail-value proDetail_price">
							<?php if(!is_null($this->product->discount_price)){?>
								<span class="detail-old-price"><?php echo number_format($this->product->price, $decimals = 0 , $dec_point = "," , $thousands_sep = ".");?></span><?php echo number_format($this->product->discount_price, $decimals = 0 , $dec_point = "," , $thousands_sep = ".");;?>
							<?php } else echo number_format($this->product->price, $decimals = 0 , $dec_point = "," , $thousands_sep = ".");?>
							</div>						</div>
						<div class="detail-item" style="height:auto;">
							<div class="detail-title proDetail_markRed" style="height:auto;">Khuyến mại:</div>
							<div class="detail-value" style="height:auto; width: 260px;"><?php echo $this->product->promotion;?></div>
						</div>
						<div class="p-detail-order">
						<!-- order -->
							<a href="javascript:void(0);" class ="addProductToCart" id="<?php echo $this->product->id;?>"><img style="margin-top: 10px;" src="/images/order.png" /></a>
						</div>
						<div class="detail-item" style="color: #D40000; margin-top: 10px" >
							Hotline: 098 123 45678
						</div>
						<div class="detail-item">
							<a href="" >[Hướng dẫn mua hàng]</a>
						</div>
					</div>
					
					<div class="p-detail-describe">
						<div id="TabbedPanels1" class="TabbedPanels">
						  <ul class="TabbedPanelsTabGroup">
							<li class="TabbedPanelsTab" tabindex="0">Mô tả sản phẩm</li>
							<li class="TabbedPanelsTab" tabindex="0">Thông tin chi tiết</li>
						  </ul>
						<div class="TabbedPanelsContentGroup">
							<div class="TabbedPanelsContent"><?php echo $this->product->short_desc;?></div>
							<div class="TabbedPanelsContent"><?php echo $this->product->details;?></div>
						  </div></div>
						<script type="text/javascript">
						var TabbedPanels1 = new Spry.Widget.TabbedPanels("TabbedPanels1");
						</script>	
					</div>
				</div>
				<div class="product-d-left">
					<div class="product-de-hotlist">
					<div style="padding-bottom: 5px; clear: both;font-size: 14px;font-weight: bold;font-family: Arial,Helvetica,sans-serif;border-bottom: 1px solid #CCC; text-align: center">SẢN PHẨM HOT</div>
				<?php foreach ($this->hots as $hot){?>
					<div class="product-rightlist-img"><a href="" title=""><img src="<?php echo $hot['IMAGE_MAIN']?>" /></a><div class="discount_hotlist">-<?php echo floor((1 - $hot['DISCOUNT_PRICE']/$hot['PRICE'])*100)?>%</div></div>
					<div class="product-rightlist-title"><a href=""><?php echo $hot['NAME']?></a></div>
					<div class="product-rightlist-price detail-mark-red">Giá: 
					<?php if(!is_null($hot['DISCOUNT_PRICE'])){?><span class="hotlist_old_price"><?php echo number_format($hot['PRICE'],$decimals = 0 , $dec_point = "," , $thousands_sep = ".")?></span></br><?php echo number_format($hot['DISCOUNT_PRICE'],$decimals = 0 , $dec_point = "," , $thousands_sep = ".")?><?php } else echo number_format($hot['PRICE'],$decimals = 0 , $dec_point = "," , $thousands_sep = ".")?>
					</div>
					<?php if(!is_null($hot['PROMOTION'])){?><div class="product-rightlist-promotion detail-mark-red">Khuyến mại:<span style="font-size: 12px; color: #888; text-align: center; font-weight: normal"><?php echo $hot['PROMOTION']?></span></div><?php }?>
				<?php }?>
					</div>
				</div>
			</div>
		</div>
	</div>