ALTER TABLE `BOOK_VISA` ADD `ONEPAY_LINK` VARCHAR(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL AFTER `STATUS`;
ALTER TABLE `BOOK_VISA` CHANGE `STATUS` `STATUS` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'NEW';
ALTER TABLE `BOOK_VISA` ADD `TRANS_CODE` VARCHAR(100) NULL DEFAULT NULL AFTER `STATUS`;